In [12]:
import pandas as pd
import math
duplicated = []
for i in ['1','2','3','4','5','6','7','8','9','10','11','12']:
    print("month is", i)
    df = pd.read_excel ('/Users/luentong/Desktop/Futures/MarketData_Year_2019/所内合约行情报表2019.' + i + '.xls')
    #print (df)

    result = []
    found = False
    print(df)
    print("dddfff")
    for i, row in df.iterrows():
        sub = []
    #     print(i)
    #     print(row[0])
    #     print(row[0] == 'ag2101')
    #     print(row[0] == 'nan')
    #     print(type(row[0]))
        if row[0] == 'ag1911':
            found = True
            sub = row[4:14]
            result.append(sub)
        elif type(row[0]) is float and math.isnan(row[0]) and found:
            sub = row[4:14]
            result.append(sub)
        elif found:
            break
    if len(result) > 0:
        print(result)
        print(len(result))
        print("length")
        tosubtract = [result[0][0], result[0][1], result[0][2], result[0][3], result[0][4], 0, 0, result[0][7], result[0][8], result[0][9]]
        print(tosubtract)
        print(len(result))
        for i in range(len(result)-4):
            print(result[4+i])
            toadd = (result[0+i] - tosubtract).tolist() + (result[1+i]- tosubtract).tolist()  + (result[2+i]- tosubtract).tolist() + (result[3+i]- tosubtract).tolist() + [result[4+i][3] - result[4+i][0]]
            print(toadd)
            print("done")
            duplicated.append(toadd)

month is 1
                    所内合约行情报表  \
0      日期： 20190101-20190131
1                         合约
2                     ag1901
3                        NaN
4                        NaN
...                      ...
10130                    NaN
10131                    注：
10132                    NaN
10133                    NaN
10134                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190102       3642
3                                               20190103       3658
4                                               20190104       3710
...                                                  ...        ...
10130                                                NaN        NaN
10131  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
10132  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
10133            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
10134                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3646       3631       3667       3628       3658       3649
3           3649       3690       3710       3690       3710       3702
4           3702       3715       3755       3715       3726       3735
...          ...        ...        ...        ...        ...        ...
10130        NaN        NaN        NaN        NaN        NaN        NaN
10131        NaN        NaN        NaN        NaN        NaN        NaN
10132        NaN        NaN        NaN        NaN        NaN        NaN
10133        NaN        NaN        NaN        NaN        NaN        NaN
10134        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2             12           3         548     3000.29         800 NaN
3             61          53          44      244.38         788 NaN
4             24          33          72     403.464         756 NaN
...          ...         ...         ...         ...         ...  ..
10130        NaN         NaN         NaN         NaN         NaN NaN
10131        NaN         NaN         NaN         NaN         NaN NaN
10132        NaN         NaN         NaN         NaN         NaN NaN
10133        NaN         NaN         NaN         NaN         NaN NaN
10134        NaN         NaN         NaN         NaN         NaN NaN

[10135 rows x 15 columns]
dddfff
[Unnamed: 4      3754
Unnamed: 5      3762
Unnamed: 6      3754
Unnamed: 7      3762
Unnamed: 8      3756
Unnamed: 9        45
Unnamed: 10       39
Unnamed: 11        6
Unnamed: 12    33.81
Unnamed: 13       36
Name: 210, dtype: object, Unnamed: 4       3797
Unnamed: 5       3805
Unnamed: 6       3797
Unnamed: 7       3805
Unnamed: 8       3801
Unnamed: 9         49
Unnamed: 10        45
Unnamed: 11         4
Unnamed: 12    22.806
Unnamed: 13        38
Name: 211, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3840
Unnamed: 8     3840
Unnamed: 9       39
Unnamed: 10      39
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      38
Name: 212, dtype: object, Unnamed: 4       3826
Unnamed: 5       3840
Unnamed: 6       3826
Unnamed: 7       3840
Unnamed: 8       3833
Unnamed: 9          0
Unnamed: 10        -7
Unnamed: 11         4
Unnamed: 12    22.998
Unnamed: 13        38
Name: 213, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3833
Unnamed: 8     3833
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      38
Name: 214, dtype: object, Unnamed: 4       3789
Unnamed: 5       3790
Unnamed: 6       3789
Unnamed: 7       3790
Unnamed: 8       3789
Unnamed: 9        -43
Unnamed: 10       -44
Unnamed: 11         4
Unnamed: 12    22.737
Unnamed: 13        40
Name: 215, dtype: object, Unnamed: 4       3795
Unnamed: 5       3806
Unnamed: 6       3795
Unnamed: 7       3806
Unnamed: 8       3802
Unnamed: 9         17
Unnamed: 10        13
Unnamed: 11         6
Unnamed: 12    34.221
Unnamed: 13        42
Name: 216, dtype: object, Unnamed: 4        3791
Unnamed: 5        3796
Unnamed: 6        3776
Unnamed: 7        3778
Unnamed: 8        3784
Unnamed: 9         -24
Unnamed: 10        -18
Unnamed: 11         26
Unnamed: 12    147.588
Unnamed: 13         64
Name: 217, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3784
Unnamed: 8     3784
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      64
Name: 218, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3790
Unnamed: 8     3790
Unnamed: 9        6
Unnamed: 10       6
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      64
Name: 219, dtype: object, Unnamed: 4       3753
Unnamed: 5       3753
Unnamed: 6       3753
Unnamed: 7       3753
Unnamed: 8       3753
Unnamed: 9        -37
Unnamed: 10       -37
Unnamed: 11         2
Unnamed: 12    11.259
Unnamed: 13        66
Name: 220, dtype: object, Unnamed: 4       3748
Unnamed: 5       3759
Unnamed: 6       3748
Unnamed: 7       3757
Unnamed: 8       3751
Unnamed: 9          4
Unnamed: 10        -2
Unnamed: 11        12
Unnamed: 12    67.524
Unnamed: 13        72
Name: 221, dtype: object, Unnamed: 4      3757
Unnamed: 5      3766
Unnamed: 6      3757
Unnamed: 7      3766
Unnamed: 8      3760
Unnamed: 9        15
Unnamed: 10        9
Unnamed: 11        6
Unnamed: 12    33.84
Unnamed: 13       74
Name: 222, dtype: object, Unnamed: 4       3748
Unnamed: 5       3748
Unnamed: 6       3715
Unnamed: 7       3715
Unnamed: 8       3730
Unnamed: 9        -45
Unnamed: 10       -30
Unnamed: 11        10
Unnamed: 12    55.953
Unnamed: 13        72
Name: 223, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9      -23
Unnamed: 10     -23
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 224, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 225, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 226, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 227, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 228, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 229, dtype: object, Unnamed: 4       3778
Unnamed: 5       3778
Unnamed: 6       3778
Unnamed: 7       3778
Unnamed: 8       3778
Unnamed: 9         71
Unnamed: 10        71
Unnamed: 11         2
Unnamed: 12    11.334
Unnamed: 13        72
Name: 230, dtype: object, Unnamed: 4       3774
Unnamed: 5       3806
Unnamed: 6       3774
Unnamed: 7       3798
Unnamed: 8       3792
Unnamed: 9         20
Unnamed: 10        14
Unnamed: 11         6
Unnamed: 12    34.134
Unnamed: 13        76
Name: 231, dtype: object]
22
length
[3754, 3762, 3754, 3762, 3756, 0, 0, 6, 33.81, 36]
22
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3833
Unnamed: 8     3833
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      38
Name: 214, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, 45.0, 39.0, 0.0, 0.0, 0.0, 43.0, 43.0, 43.0, 43.0, 45.0, 49.0, 45.0, -2.0, -11.004000000000001, 2.0, nan, nan, nan, 78.0, 84.0, 39.0, 39.0, -6.0, -33.81, 2.0, 72.0, 78.0, 72.0, 78.0, 77.0, 0.0, -7.0, -2.0, -10.812000000000001, 2.0, nan]
done
Unnamed: 4       3789
Unnamed: 5       3790
Unnamed: 6       3789
Unnamed: 7       3790
Unnamed: 8       3789
Unnamed: 9        -43
Unnamed: 10       -44
Unnamed: 11         4
Unnamed: 12    22.737
Unnamed: 13        40
Name: 215, dtype: object
[43.0, 43.0, 43.0, 43.0, 45.0, 49.0, 45.0, -2.0, -11.004000000000001, 2.0, nan, nan, nan, 78.0, 84.0, 39.0, 39.0, -6.0, -33.81, 2.0, 72.0, 78.0, 72.0, 78.0, 77.0, 0.0, -7.0, -2.0, -10.812000000000001, 2.0, nan, nan, nan, 71.0, 77.0, 0.0, 0.0, -6.0, -33.81, 2.0, 1]
done
Unnamed: 4       3795
Unnamed: 5       3806
Unnamed: 6       3795
Unnamed: 7       3806
Unnamed: 8       3802
Unnamed: 9         17
Unnamed: 10        13
Unnamed: 11         6
Unnamed: 12    34.221
Unnamed: 13        42
Name: 216, dtype: object
[nan, nan, nan, 78.0, 84.0, 39.0, 39.0, -6.0, -33.81, 2.0, 72.0, 78.0, 72.0, 78.0, 77.0, 0.0, -7.0, -2.0, -10.812000000000001, 2.0, nan, nan, nan, 71.0, 77.0, 0.0, 0.0, -6.0, -33.81, 2.0, 35.0, 28.0, 35.0, 28.0, 33.0, -43.0, -44.0, -2.0, -11.073000000000004, 4.0, 11]
done
Unnamed: 4        3791
Unnamed: 5        3796
Unnamed: 6        3776
Unnamed: 7        3778
Unnamed: 8        3784
Unnamed: 9         -24
Unnamed: 10        -18
Unnamed: 11         26
Unnamed: 12    147.588
Unnamed: 13         64
Name: 217, dtype: object
[72.0, 78.0, 72.0, 78.0, 77.0, 0.0, -7.0, -2.0, -10.812000000000001, 2.0, nan, nan, nan, 71.0, 77.0, 0.0, 0.0, -6.0, -33.81, 2.0, 35.0, 28.0, 35.0, 28.0, 33.0, -43.0, -44.0, -2.0, -11.073000000000004, 4.0, 41.0, 44.0, 41.0, 44.0, 46.0, 17.0, 13.0, 0.0, 0.41099999999999426, 6.0, -13]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3784
Unnamed: 8     3784
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      64
Name: 218, dtype: object
[nan, nan, nan, 71.0, 77.0, 0.0, 0.0, -6.0, -33.81, 2.0, 35.0, 28.0, 35.0, 28.0, 33.0, -43.0, -44.0, -2.0, -11.073000000000004, 4.0, 41.0, 44.0, 41.0, 44.0, 46.0, 17.0, 13.0, 0.0, 0.41099999999999426, 6.0, 37.0, 34.0, 22.0, 16.0, 28.0, -24.0, -18.0, 20.0, 113.77799999999999, 28.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3790
Unnamed: 8     3790
Unnamed: 9        6
Unnamed: 10       6
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      64
Name: 219, dtype: object
[35.0, 28.0, 35.0, 28.0, 33.0, -43.0, -44.0, -2.0, -11.073000000000004, 4.0, 41.0, 44.0, 41.0, 44.0, 46.0, 17.0, 13.0, 0.0, 0.41099999999999426, 6.0, 37.0, 34.0, 22.0, 16.0, 28.0, -24.0, -18.0, 20.0, 113.77799999999999, 28.0, nan, nan, nan, 22.0, 28.0, 0.0, 0.0, -6.0, -33.81, 28.0, nan]
done
Unnamed: 4       3753
Unnamed: 5       3753
Unnamed: 6       3753
Unnamed: 7       3753
Unnamed: 8       3753
Unnamed: 9        -37
Unnamed: 10       -37
Unnamed: 11         2
Unnamed: 12    11.259
Unnamed: 13        66
Name: 220, dtype: object
[41.0, 44.0, 41.0, 44.0, 46.0, 17.0, 13.0, 0.0, 0.41099999999999426, 6.0, 37.0, 34.0, 22.0, 16.0, 28.0, -24.0, -18.0, 20.0, 113.77799999999999, 28.0, nan, nan, nan, 22.0, 28.0, 0.0, 0.0, -6.0, -33.81, 28.0, nan, nan, nan, 28.0, 34.0, 6.0, 6.0, -6.0, -33.81, 28.0, 0]
done
Unnamed: 4       3748
Unnamed: 5       3759
Unnamed: 6       3748
Unnamed: 7       3757
Unnamed: 8       3751
Unnamed: 9          4
Unnamed: 10        -2
Unnamed: 11        12
Unnamed: 12    67.524
Unnamed: 13        72
Name: 221, dtype: object
[37.0, 34.0, 22.0, 16.0, 28.0, -24.0, -18.0, 20.0, 113.77799999999999, 28.0, nan, nan, nan, 22.0, 28.0, 0.0, 0.0, -6.0, -33.81, 28.0, nan, nan, nan, 28.0, 34.0, 6.0, 6.0, -6.0, -33.81, 28.0, -1.0, -9.0, -1.0, -9.0, -3.0, -37.0, -37.0, -4.0, -22.551000000000002, 30.0, 9]
done
Unnamed: 4      3757
Unnamed: 5      3766
Unnamed: 6      3757
Unnamed: 7      3766
Unnamed: 8      3760
Unnamed: 9        15
Unnamed: 10        9
Unnamed: 11        6
Unnamed: 12    33.84
Unnamed: 13       74
Name: 222, dtype: object
[nan, nan, nan, 22.0, 28.0, 0.0, 0.0, -6.0, -33.81, 28.0, nan, nan, nan, 28.0, 34.0, 6.0, 6.0, -6.0, -33.81, 28.0, -1.0, -9.0, -1.0, -9.0, -3.0, -37.0, -37.0, -4.0, -22.551000000000002, 30.0, -6.0, -3.0, -6.0, -5.0, -5.0, 4.0, -2.0, 6.0, 33.714, 36.0, 9]
done
Unnamed: 4       3748
Unnamed: 5       3748
Unnamed: 6       3715
Unnamed: 7       3715
Unnamed: 8       3730
Unnamed: 9        -45
Unnamed: 10       -30
Unnamed: 11        10
Unnamed: 12    55.953
Unnamed: 13        72
Name: 223, dtype: object
[nan, nan, nan, 28.0, 34.0, 6.0, 6.0, -6.0, -33.81, 28.0, -1.0, -9.0, -1.0, -9.0, -3.0, -37.0, -37.0, -4.0, -22.551000000000002, 30.0, -6.0, -3.0, -6.0, -5.0, -5.0, 4.0, -2.0, 6.0, 33.714, 36.0, 3.0, 4.0, 3.0, 4.0, 4.0, 15.0, 9.0, 0.0, 0.030000000000001137, 38.0, -33]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9      -23
Unnamed: 10     -23
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 224, dtype: object
[-1.0, -9.0, -1.0, -9.0, -3.0, -37.0, -37.0, -4.0, -22.551000000000002, 30.0, -6.0, -3.0, -6.0, -5.0, -5.0, 4.0, -2.0, 6.0, 33.714, 36.0, 3.0, 4.0, 3.0, 4.0, 4.0, 15.0, 9.0, 0.0, 0.030000000000001137, 38.0, -6.0, -14.0, -39.0, -47.0, -26.0, -45.0, -30.0, 4.0, 22.143, 36.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 225, dtype: object
[-6.0, -3.0, -6.0, -5.0, -5.0, 4.0, -2.0, 6.0, 33.714, 36.0, 3.0, 4.0, 3.0, 4.0, 4.0, 15.0, 9.0, 0.0, 0.030000000000001137, 38.0, -6.0, -14.0, -39.0, -47.0, -26.0, -45.0, -30.0, 4.0, 22.143, 36.0, nan, nan, nan, -55.0, -49.0, -23.0, -23.0, -6.0, -33.81, 36.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 226, dtype: object
[3.0, 4.0, 3.0, 4.0, 4.0, 15.0, 9.0, 0.0, 0.030000000000001137, 38.0, -6.0, -14.0, -39.0, -47.0, -26.0, -45.0, -30.0, 4.0, 22.143, 36.0, nan, nan, nan, -55.0, -49.0, -23.0, -23.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 227, dtype: object
[-6.0, -14.0, -39.0, -47.0, -26.0, -45.0, -30.0, 4.0, 22.143, 36.0, nan, nan, nan, -55.0, -49.0, -23.0, -23.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 228, dtype: object
[nan, nan, nan, -55.0, -49.0, -23.0, -23.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3707
Unnamed: 8     3707
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      72
Name: 229, dtype: object
[nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan]
done
Unnamed: 4       3778
Unnamed: 5       3778
Unnamed: 6       3778
Unnamed: 7       3778
Unnamed: 8       3778
Unnamed: 9         71
Unnamed: 10        71
Unnamed: 11         2
Unnamed: 12    11.334
Unnamed: 13        72
Name: 230, dtype: object
[nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, 0]
done
Unnamed: 4       3774
Unnamed: 5       3806
Unnamed: 6       3774
Unnamed: 7       3798
Unnamed: 8       3792
Unnamed: 9         20
Unnamed: 10        14
Unnamed: 11         6
Unnamed: 12    34.134
Unnamed: 13        76
Name: 231, dtype: object
[nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, nan, nan, nan, -55.0, -49.0, 0.0, 0.0, -6.0, -33.81, 36.0, 24.0, 16.0, 24.0, 16.0, 22.0, 71.0, 71.0, -4.0, -22.476000000000003, 36.0, 24]
done
month is 2

                    所内合约行情报表  \
0      日期： 20190201-20190228
1                         合约
2                     ag1902
3                        NaN
4                        NaN
...                      ...
10453                    NaN
10454                    注：
10455                    NaN
10456                    NaN
10457                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190201       3710
3                                               20190211       3720
4                                               20190212       3703
...                                                  ...        ...
10453                                                NaN        NaN
10454  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
10455  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
10456            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
10457                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3704       3710       3720       3654       3720       3703
3           3703        NaN        NaN        NaN       3703       3703
4           3703       3703       3703       3703       3703       3703
...          ...        ...        ...        ...        ...        ...
10453        NaN        NaN        NaN        NaN        NaN        NaN
10454        NaN        NaN        NaN        NaN        NaN        NaN
10455        NaN        NaN        NaN        NaN        NaN        NaN
10456        NaN        NaN        NaN        NaN        NaN        NaN
10457        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2             16          -1          72      400.02         372 NaN
3              0           0           0           0         372 NaN
4              0           0           4      22.218         372 NaN
...          ...         ...         ...         ...         ...  ..
10453        NaN         NaN         NaN         NaN         NaN NaN
10454        NaN         NaN         NaN         NaN         NaN NaN
10455        NaN         NaN         NaN         NaN         NaN NaN
10456        NaN         NaN         NaN         NaN         NaN NaN
10457        NaN         NaN         NaN         NaN         NaN NaN

[10458 rows x 15 columns]
dddfff
[Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3792
Unnamed: 8     3792
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      76
Name: 128, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3792
Unnamed: 8     3792
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      76
Name: 129, dtype: object, Unnamed: 4       3774
Unnamed: 5       3783
Unnamed: 6       3768
Unnamed: 7       3768
Unnamed: 8       3776
Unnamed: 9        -24
Unnamed: 10       -16
Unnamed: 11        12
Unnamed: 12    67.971
Unnamed: 13        78
Name: 130, dtype: object, Unnamed: 4      3784
Unnamed: 5      3784
Unnamed: 6      3783
Unnamed: 7      3783
Unnamed: 8      3783
Unnamed: 9         7
Unnamed: 10        7
Unnamed: 11        6
Unnamed: 12    34.05
Unnamed: 13       80
Name: 131, dtype: object, Unnamed: 4       3748
Unnamed: 5       3748
Unnamed: 6       3748
Unnamed: 7       3748
Unnamed: 8       3748
Unnamed: 9        -35
Unnamed: 10       -35
Unnamed: 11         2
Unnamed: 12    11.244
Unnamed: 13        82
Name: 132, dtype: object, Unnamed: 4       3735
Unnamed: 5       3740
Unnamed: 6       3735
Unnamed: 7       3740
Unnamed: 8       3737
Unnamed: 9         -8
Unnamed: 10       -11
Unnamed: 11         4
Unnamed: 12    22.425
Unnamed: 13        84
Name: 133, dtype: object, Unnamed: 4       3755
Unnamed: 5       3755
Unnamed: 6       3755
Unnamed: 7       3755
Unnamed: 8       3755
Unnamed: 9         18
Unnamed: 10        18
Unnamed: 11         2
Unnamed: 12    11.265
Unnamed: 13        84
Name: 134, dtype: object, Unnamed: 4       3799
Unnamed: 5       3799
Unnamed: 6       3790
Unnamed: 7       3790
Unnamed: 8       3794
Unnamed: 9         35
Unnamed: 10        39
Unnamed: 11         4
Unnamed: 12    22.767
Unnamed: 13        84
Name: 135, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3794
Unnamed: 8     3794
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      84
Name: 136, dtype: object, Unnamed: 4       3818
Unnamed: 5       3818
Unnamed: 6       3808
Unnamed: 7       3808
Unnamed: 8       3815
Unnamed: 9         14
Unnamed: 10        21
Unnamed: 11         8
Unnamed: 12    45.786
Unnamed: 13        86
Name: 137, dtype: object, Unnamed: 4       3785
Unnamed: 5       3785
Unnamed: 6       3785
Unnamed: 7       3785
Unnamed: 8       3785
Unnamed: 9        -30
Unnamed: 10       -30
Unnamed: 11         2
Unnamed: 12    11.355
Unnamed: 13        86
Name: 138, dtype: object, Unnamed: 4       3775
Unnamed: 5       3782
Unnamed: 6       3775
Unnamed: 7       3782
Unnamed: 8       3777
Unnamed: 9         -3
Unnamed: 10        -8
Unnamed: 11         8
Unnamed: 12    45.327
Unnamed: 13        88
Name: 139, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3777
Unnamed: 8     3777
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      88
Name: 140, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3777
Unnamed: 8     3777
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      88
Name: 141, dtype: object, Unnamed: 4       3714
Unnamed: 5       3714
Unnamed: 6       3714
Unnamed: 7       3714
Unnamed: 8       3714
Unnamed: 9        -63
Unnamed: 10       -63
Unnamed: 11         4
Unnamed: 12    22.284
Unnamed: 13        90
Name: 142, dtype: object]
15
length
[nan, nan, nan, 3792, 3792, 0, 0, 0, 0, 76]
15
Unnamed: 4       3748
Unnamed: 5       3748
Unnamed: 6       3748
Unnamed: 7       3748
Unnamed: 8       3748
Unnamed: 9        -35
Unnamed: 10       -35
Unnamed: 11         2
Unnamed: 12    11.244
Unnamed: 13        82
Name: 132, dtype: object
[nan, nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, -24.0, -16.0, -24.0, -16.0, 12.0, 67.971, 2.0, nan, nan, nan, -9.0, -9.0, 7.0, 7.0, 6.0, 34.05, 4.0, 0]
done
Unnamed: 4       3735
Unnamed: 5       3740
Unnamed: 6       3735
Unnamed: 7       3740
Unnamed: 8       3737
Unnamed: 9         -8
Unnamed: 10       -11
Unnamed: 11         4
Unnamed: 12    22.425
Unnamed: 13        84
Name: 133, dtype: object
[nan, nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, -24.0, -16.0, -24.0, -16.0, 12.0, 67.971, 2.0, nan, nan, nan, -9.0, -9.0, 7.0, 7.0, 6.0, 34.05, 4.0, nan, nan, nan, -44.0, -44.0, -35.0, -35.0, 2.0, 11.244, 6.0, 5]
done
Unnamed: 4       3755
Unnamed: 5       3755
Unnamed: 6       3755
Unnamed: 7       3755
Unnamed: 8       3755
Unnamed: 9         18
Unnamed: 10        18
Unnamed: 11         2
Unnamed: 12    11.265
Unnamed: 13        84
Name: 134, dtype: object
[nan, nan, nan, -24.0, -16.0, -24.0, -16.0, 12.0, 67.971, 2.0, nan, nan, nan, -9.0, -9.0, 7.0, 7.0, 6.0, 34.05, 4.0, nan, nan, nan, -44.0, -44.0, -35.0, -35.0, 2.0, 11.244, 6.0, nan, nan, nan, -52.0, -55.0, -8.0, -11.0, 4.0, 22.425, 8.0, 0]
done
Unnamed: 4       3799
Unnamed: 5       3799
Unnamed: 6       3790
Unnamed: 7       3790
Unnamed: 8       3794
Unnamed: 9         35
Unnamed: 10        39
Unnamed: 11         4
Unnamed: 12    22.767
Unnamed: 13        84
Name: 135, dtype: object
[nan, nan, nan, -9.0, -9.0, 7.0, 7.0, 6.0, 34.05, 4.0, nan, nan, nan, -44.0, -44.0, -35.0, -35.0, 2.0, 11.244, 6.0, nan, nan, nan, -52.0, -55.0, -8.0, -11.0, 4.0, 22.425, 8.0, nan, nan, nan, -37.0, -37.0, 18.0, 18.0, 2.0, 11.265, 8.0, -9]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3794
Unnamed: 8     3794
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      84
Name: 136, dtype: object
[nan, nan, nan, -44.0, -44.0, -35.0, -35.0, 2.0, 11.244, 6.0, nan, nan, nan, -52.0, -55.0, -8.0, -11.0, 4.0, 22.425, 8.0, nan, nan, nan, -37.0, -37.0, 18.0, 18.0, 2.0, 11.265, 8.0, nan, nan, nan, -2.0, 2.0, 35.0, 39.0, 4.0, 22.767, 8.0, nan]
done
Unnamed: 4       3818
Unnamed: 5       3818
Unnamed: 6       3808
Unnamed: 7       3808
Unnamed: 8       3815
Unnamed: 9         14
Unnamed: 10        21
Unnamed: 11         8
Unnamed: 12    45.786
Unnamed: 13        86
Name: 137, dtype: object
[nan, nan, nan, -52.0, -55.0, -8.0, -11.0, 4.0, 22.425, 8.0, nan, nan, nan, -37.0, -37.0, 18.0, 18.0, 2.0, 11.265, 8.0, nan, nan, nan, -2.0, 2.0, 35.0, 39.0, 4.0, 22.767, 8.0, nan, nan, nan, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 8.0, -10]
done
Unnamed: 4       3785
Unnamed: 5       3785
Unnamed: 6       3785
Unnamed: 7       3785
Unnamed: 8       3785
Unnamed: 9        -30
Unnamed: 10       -30
Unnamed: 11         2
Unnamed: 12    11.355
Unnamed: 13        86
Name: 138, dtype: object
[nan, nan, nan, -37.0, -37.0, 18.0, 18.0, 2.0, 11.265, 8.0, nan, nan, nan, -2.0, 2.0, 35.0, 39.0, 4.0, 22.767, 8.0, nan, nan, nan, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 8.0, nan, nan, nan, 16.0, 23.0, 14.0, 21.0, 8.0, 45.786, 10.0, 0]
done
Unnamed: 4       3775
Unnamed: 5       3782
Unnamed: 6       3775
Unnamed: 7       3782
Unnamed: 8       3777
Unnamed: 9         -3
Unnamed: 10        -8
Unnamed: 11         8
Unnamed: 12    45.327
Unnamed: 13        88
Name: 139, dtype: object
[nan, nan, nan, -2.0, 2.0, 35.0, 39.0, 4.0, 22.767, 8.0, nan, nan, nan, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 8.0, nan, nan, nan, 16.0, 23.0, 14.0, 21.0, 8.0, 45.786, 10.0, nan, nan, nan, -7.0, -7.0, -30.0, -30.0, 2.0, 11.355, 10.0, 7]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3777
Unnamed: 8     3777
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      88
Name: 140, dtype: object
[nan, nan, nan, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 8.0, nan, nan, nan, 16.0, 23.0, 14.0, 21.0, 8.0, 45.786, 10.0, nan, nan, nan, -7.0, -7.0, -30.0, -30.0, 2.0, 11.355, 10.0, nan, nan, nan, -10.0, -15.0, -3.0, -8.0, 8.0, 45.327, 12.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3777
Unnamed: 8     3777
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      88
Name: 141, dtype: object
[nan, nan, nan, 16.0, 23.0, 14.0, 21.0, 8.0, 45.786, 10.0, nan, nan, nan, -7.0, -7.0, -30.0, -30.0, 2.0, 11.355, 10.0, nan, nan, nan, -10.0, -15.0, -3.0, -8.0, 8.0, 45.327, 12.0, nan, nan, nan, -15.0, -15.0, 0.0, 0.0, 0.0, 0.0, 12.0, nan]
done
Unnamed: 4       3714
Unnamed: 5       3714
Unnamed: 6       3714
Unnamed: 7       3714
Unnamed: 8       3714
Unnamed: 9        -63
Unnamed: 10       -63
Unnamed: 11         4
Unnamed: 12    22.284
Unnamed: 13        90
Name: 142, dtype: object
[nan, nan, nan, -7.0, -7.0, -30.0, -30.0, 2.0, 11.355, 10.0, nan, nan, nan, -10.0, -15.0, -3.0, -8.0, 8.0, 45.327, 12.0, nan, nan, nan, -15.0, -15.0, 0.0, 0.0, 0.0, 0.0, 12.0, nan, nan, nan, -15.0, -15.0, 0.0, 0.0, 0.0, 0.0, 12.0, 0]
done
month is 3

                    所内合约行情报表  \
0      日期： 20190301-20190331
1                         合约
2                     ag1903
3                        NaN
4                        NaN
...                      ...
16095                    NaN
16096                    注：
16097                    NaN
16098                    NaN
16099                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190301       3665
3                                               20190304       3649
4                                               20190305       3600
...                                                  ...        ...
16095                                                NaN        NaN
16096  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
16097  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
16098            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
16099                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3673       3655       3655       3649       3649       3652
3           3652       3586       3600       3586       3600       3586
4           3586       3551       3570       3545       3570       3564
...          ...        ...        ...        ...        ...        ...
16095        NaN        NaN        NaN        NaN        NaN        NaN
16096        NaN        NaN        NaN        NaN        NaN        NaN
16097        NaN        NaN        NaN        NaN        NaN        NaN
16098        NaN        NaN        NaN        NaN        NaN        NaN
16099        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2            -24         -21          24     131.496         340 NaN
3            -52         -66         124      667.08         216 NaN
4            -16         -22         164     876.804         232 NaN
...          ...         ...         ...         ...         ...  ..
16095        NaN         NaN         NaN         NaN         NaN NaN
16096        NaN         NaN         NaN         NaN         NaN NaN
16097        NaN         NaN         NaN         NaN         NaN NaN
16098        NaN         NaN         NaN         NaN         NaN NaN
16099        NaN         NaN         NaN         NaN         NaN NaN

[16100 rows x 15 columns]
dddfff
[Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3714
Unnamed: 8     3714
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      90
Name: 160, dtype: object, Unnamed: 4       3689
Unnamed: 5       3689
Unnamed: 6       3623
Unnamed: 7       3623
Unnamed: 8       3647
Unnamed: 9        -91
Unnamed: 10       -67
Unnamed: 11        12
Unnamed: 12    65.652
Unnamed: 13        90
Name: 161, dtype: object, Unnamed: 4       3636
Unnamed: 5       3636
Unnamed: 6       3589
Unnamed: 7       3589
Unnamed: 8       3605
Unnamed: 9        -58
Unnamed: 10       -42
Unnamed: 11         8
Unnamed: 12    43.269
Unnamed: 13        88
Name: 162, dtype: object, Unnamed: 4       3584
Unnamed: 5       3605
Unnamed: 6       3584
Unnamed: 7       3596
Unnamed: 8       3597
Unnamed: 9         -9
Unnamed: 10        -8
Unnamed: 11        10
Unnamed: 12    53.958
Unnamed: 13        92
Name: 163, dtype: object, Unnamed: 4       3602
Unnamed: 5       3602
Unnamed: 6       3596
Unnamed: 7       3596
Unnamed: 8       3599
Unnamed: 9         -1
Unnamed: 10         2
Unnamed: 11         4
Unnamed: 12    21.594
Unnamed: 13        94
Name: 164, dtype: object, Unnamed: 4       3592
Unnamed: 5       3607
Unnamed: 6       3592
Unnamed: 7       3607
Unnamed: 8       3600
Unnamed: 9          8
Unnamed: 10         1
Unnamed: 11        10
Unnamed: 12    54.006
Unnamed: 13        96
Name: 165, dtype: object, Unnamed: 4      3620
Unnamed: 5      3653
Unnamed: 6      3620
Unnamed: 7      3653
Unnamed: 8      3645
Unnamed: 9        53
Unnamed: 10       45
Unnamed: 11       14
Unnamed: 12    76.56
Unnamed: 13       94
Name: 166, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3645
Unnamed: 8     3645
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 167, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3645
Unnamed: 8     3645
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 168, dtype: object, Unnamed: 4        3672
Unnamed: 5        3672
Unnamed: 6        3643
Unnamed: 7        3645
Unnamed: 8        3649
Unnamed: 9           0
Unnamed: 10          4
Unnamed: 11         84
Unnamed: 12    459.864
Unnamed: 13         94
Name: 169, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3649
Unnamed: 8     3649
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 170, dtype: object, Unnamed: 4       3646
Unnamed: 5       3646
Unnamed: 6       3646
Unnamed: 7       3646
Unnamed: 8       3646
Unnamed: 9         -3
Unnamed: 10        -3
Unnamed: 11         4
Unnamed: 12    21.876
Unnamed: 13        94
Name: 171, dtype: object, Unnamed: 4       3658
Unnamed: 5       3665
Unnamed: 6       3658
Unnamed: 7       3665
Unnamed: 8       3661
Unnamed: 9         19
Unnamed: 10        15
Unnamed: 11         4
Unnamed: 12    21.969
Unnamed: 13        96
Name: 172, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3661
Unnamed: 8     3661
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      96
Name: 173, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3661
Unnamed: 8     3661
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      96
Name: 174, dtype: object, Unnamed: 4       3686
Unnamed: 5       3690
Unnamed: 6       3685
Unnamed: 7       3685
Unnamed: 8       3686
Unnamed: 9         24
Unnamed: 10        25
Unnamed: 11        16
Unnamed: 12    88.473
Unnamed: 13       104
Name: 175, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3686
Unnamed: 8     3686
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     104
Name: 176, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3686
Unnamed: 8     3686
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     104
Name: 177, dtype: object, Unnamed: 4       3680
Unnamed: 5       3680
Unnamed: 6       3668
Unnamed: 7       3676
Unnamed: 8       3674
Unnamed: 9        -10
Unnamed: 10       -12
Unnamed: 11         6
Unnamed: 12    33.072
Unnamed: 13       102
Name: 178, dtype: object, Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3656
Unnamed: 7       3656
Unnamed: 8       3656
Unnamed: 9        -18
Unnamed: 10       -18
Unnamed: 11         4
Unnamed: 12    21.936
Unnamed: 13       106
Name: 179, dtype: object, Unnamed: 4      3616
Unnamed: 5      3616
Unnamed: 6      3586
Unnamed: 7      3586
Unnamed: 8      3604
Unnamed: 9       -70
Unnamed: 10      -52
Unnamed: 11       14
Unnamed: 12    75.69
Unnamed: 13      106
Name: 180, dtype: object]
21
length
[nan, nan, nan, 3714, 3714, 0, 0, 0, 0, 90]
21
Unnamed: 4       3602
Unnamed: 5       3602
Unnamed: 6       3596
Unnamed: 7       3596
Unnamed: 8       3599
Unnamed: 9         -1
Unnamed: 10         2
Unnamed: 11         4
Unnamed: 12    21.594
Unnamed: 13        94
Name: 164, dtype: object
[nan, nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, -91.0, -67.0, -91.0, -67.0, 12.0, 65.652, 0.0, nan, nan, nan, -125.0, -109.0, -58.0, -42.0, 8.0, 43.269, -2.0, nan, nan, nan, -118.0, -117.0, -9.0, -8.0, 10.0, 53.958, 2.0, -6]
done
Unnamed: 4       3592
Unnamed: 5       3607
Unnamed: 6       3592
Unnamed: 7       3607
Unnamed: 8       3600
Unnamed: 9          8
Unnamed: 10         1
Unnamed: 11        10
Unnamed: 12    54.006
Unnamed: 13        96
Name: 165, dtype: object
[nan, nan, nan, -91.0, -67.0, -91.0, -67.0, 12.0, 65.652, 0.0, nan, nan, nan, -125.0, -109.0, -58.0, -42.0, 8.0, 43.269, -2.0, nan, nan, nan, -118.0, -117.0, -9.0, -8.0, 10.0, 53.958, 2.0, nan, nan, nan, -118.0, -115.0, -1.0, 2.0, 4.0, 21.594, 4.0, 15]
done
Unnamed: 4      3620
Unnamed: 5      3653
Unnamed: 6      3620
Unnamed: 7      3653
Unnamed: 8      3645
Unnamed: 9        53
Unnamed: 10       45
Unnamed: 11       14
Unnamed: 12    76.56
Unnamed: 13       94
Name: 166, dtype: object
[nan, nan, nan, -125.0, -109.0, -58.0, -42.0, 8.0, 43.269, -2.0, nan, nan, nan, -118.0, -117.0, -9.0, -8.0, 10.0, 53.958, 2.0, nan, nan, nan, -118.0, -115.0, -1.0, 2.0, 4.0, 21.594, 4.0, nan, nan, nan, -107.0, -114.0, 8.0, 1.0, 10.0, 54.006, 6.0, 33]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3645
Unnamed: 8     3645
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 167, dtype: object
[nan, nan, nan, -118.0, -117.0, -9.0, -8.0, 10.0, 53.958, 2.0, nan, nan, nan, -118.0, -115.0, -1.0, 2.0, 4.0, 21.594, 4.0, nan, nan, nan, -107.0, -114.0, 8.0, 1.0, 10.0, 54.006, 6.0, nan, nan, nan, -61.0, -69.0, 53.0, 45.0, 14.0, 76.56, 4.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3645
Unnamed: 8     3645
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 168, dtype: object
[nan, nan, nan, -118.0, -115.0, -1.0, 2.0, 4.0, 21.594, 4.0, nan, nan, nan, -107.0, -114.0, 8.0, 1.0, 10.0, 54.006, 6.0, nan, nan, nan, -61.0, -69.0, 53.0, 45.0, 14.0, 76.56, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan]
done
Unnamed: 4        3672
Unnamed: 5        3672
Unnamed: 6        3643
Unnamed: 7        3645
Unnamed: 8        3649
Unnamed: 9           0
Unnamed: 10          4
Unnamed: 11         84
Unnamed: 12    459.864
Unnamed: 13         94
Name: 169, dtype: object
[nan, nan, nan, -107.0, -114.0, 8.0, 1.0, 10.0, 54.006, 6.0, nan, nan, nan, -61.0, -69.0, 53.0, 45.0, 14.0, 76.56, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, -27]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3649
Unnamed: 8     3649
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      94
Name: 170, dtype: object
[nan, nan, nan, -61.0, -69.0, 53.0, 45.0, 14.0, 76.56, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -65.0, 0.0, 4.0, 84.0, 459.864, 4.0, nan]
done
Unnamed: 4       3646
Unnamed: 5       3646
Unnamed: 6       3646
Unnamed: 7       3646
Unnamed: 8       3646
Unnamed: 9         -3
Unnamed: 10        -3
Unnamed: 11         4
Unnamed: 12    21.876
Unnamed: 13        94
Name: 171, dtype: object
[nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -65.0, 0.0, 4.0, 84.0, 459.864, 4.0, nan, nan, nan, -65.0, -65.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0]
done
Unnamed: 4       3658
Unnamed: 5       3665
Unnamed: 6       3658
Unnamed: 7       3665
Unnamed: 8       3661
Unnamed: 9         19
Unnamed: 10        15
Unnamed: 11         4
Unnamed: 12    21.969
Unnamed: 13        96
Name: 172, dtype: object
[nan, nan, nan, -69.0, -69.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -69.0, -65.0, 0.0, 4.0, 84.0, 459.864, 4.0, nan, nan, nan, -65.0, -65.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -68.0, -68.0, -3.0, -3.0, 4.0, 21.876, 4.0, 7]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3661
Unnamed: 8     3661
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      96
Name: 173, dtype: object
[nan, nan, nan, -69.0, -65.0, 0.0, 4.0, 84.0, 459.864, 4.0, nan, nan, nan, -65.0, -65.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -68.0, -68.0, -3.0, -3.0, 4.0, 21.876, 4.0, nan, nan, nan, -49.0, -53.0, 19.0, 15.0, 4.0, 21.969, 6.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3661
Unnamed: 8     3661
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      96
Name: 174, dtype: object
[nan, nan, nan, -65.0, -65.0, 0.0, 0.0, 0.0, 0.0, 4.0, nan, nan, nan, -68.0, -68.0, -3.0, -3.0, 4.0, 21.876, 4.0, nan, nan, nan, -49.0, -53.0, 19.0, 15.0, 4.0, 21.969, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan]
done
Unnamed: 4       3686
Unnamed: 5       3690
Unnamed: 6       3685
Unnamed: 7       3685
Unnamed: 8       3686
Unnamed: 9         24
Unnamed: 10        25
Unnamed: 11        16
Unnamed: 12    88.473
Unnamed: 13       104
Name: 175, dtype: object
[nan, nan, nan, -68.0, -68.0, -3.0, -3.0, 4.0, 21.876, 4.0, nan, nan, nan, -49.0, -53.0, 19.0, 15.0, 4.0, 21.969, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, -1]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3686
Unnamed: 8     3686
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     104
Name: 176, dtype: object
[nan, nan, nan, -49.0, -53.0, 19.0, 15.0, 4.0, 21.969, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -29.0, -28.0, 24.0, 25.0, 16.0, 88.473, 14.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3686
Unnamed: 8     3686
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     104
Name: 177, dtype: object
[nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -29.0, -28.0, 24.0, 25.0, 16.0, 88.473, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan]
done
Unnamed: 4       3680
Unnamed: 5       3680
Unnamed: 6       3668
Unnamed: 7       3676
Unnamed: 8       3674
Unnamed: 9        -10
Unnamed: 10       -12
Unnamed: 11         6
Unnamed: 12    33.072
Unnamed: 13       102
Name: 178, dtype: object
[nan, nan, nan, -53.0, -53.0, 0.0, 0.0, 0.0, 0.0, 6.0, nan, nan, nan, -29.0, -28.0, 24.0, 25.0, 16.0, 88.473, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, -4]
done
Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3656
Unnamed: 7       3656
Unnamed: 8       3656
Unnamed: 9        -18
Unnamed: 10       -18
Unnamed: 11         4
Unnamed: 12    21.936
Unnamed: 13       106
Name: 179, dtype: object
[nan, nan, nan, -29.0, -28.0, 24.0, 25.0, 16.0, 88.473, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan, nan, nan, -38.0, -40.0, -10.0, -12.0, 6.0, 33.072, 12.0, 0]
done
Unnamed: 4      3616
Unnamed: 5      3616
Unnamed: 6      3586
Unnamed: 7      3586
Unnamed: 8      3604
Unnamed: 9       -70
Unnamed: 10      -52
Unnamed: 11       14
Unnamed: 12    75.69
Unnamed: 13      106
Name: 180, dtype: object
[nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan, nan, nan, -28.0, -28.0, 0.0, 0.0, 0.0, 0.0, 14.0, nan, nan, nan, -38.0, -40.0, -10.0, -12.0, 6.0, 33.072, 12.0, nan, nan, nan, -58.0, -58.0, -18.0, -18.0, 4.0, 21.936, 16.0, -30]
done
month is 4

                    所内合约行情报表  \
0      日期： 20190401-20190430
1                         合约
2                     ag1904
3                        NaN
4                        NaN
...                      ...
17095                    NaN
17096                    注：
17097                    NaN
17098                    NaN
17099                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190401       3481
3                                               20190402       3535
4                                               20190403       3526
...                                                  ...        ...
17095                                                NaN        NaN
17096  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
17097  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
17098            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
17099                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3514       3535       3535       3535       3535       3535
3           3535       3520       3528       3520       3526       3524
4           3524       3540       3550       3540       3550       3544
...          ...        ...        ...        ...        ...        ...
17095        NaN        NaN        NaN        NaN        NaN        NaN
17096        NaN        NaN        NaN        NaN        NaN        NaN
17097        NaN        NaN        NaN        NaN        NaN        NaN
17098        NaN        NaN        NaN        NaN        NaN        NaN
17099        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2             21          21          12       63.63        1208 NaN
3             -9         -11         136     718.932        1200 NaN
4             26          20          20      106.32        1200 NaN
...          ...         ...         ...         ...         ...  ..
17095        NaN         NaN         NaN         NaN         NaN NaN
17096        NaN         NaN         NaN         NaN         NaN NaN
17097        NaN         NaN         NaN         NaN         NaN NaN
17098        NaN         NaN         NaN         NaN         NaN NaN
17099        NaN         NaN         NaN         NaN         NaN NaN

[17100 rows x 15 columns]
dddfff
[Unnamed: 4      3611
Unnamed: 5      3611
Unnamed: 6      3600
Unnamed: 7      3600
Unnamed: 8      3607
Unnamed: 9        -4
Unnamed: 10        3
Unnamed: 11        8
Unnamed: 12    43.29
Unnamed: 13      104
Name: 138, dtype: object, Unnamed: 4       3605
Unnamed: 5       3608
Unnamed: 6       3605
Unnamed: 7       3606
Unnamed: 8       3606
Unnamed: 9         -1
Unnamed: 10        -1
Unnamed: 11         6
Unnamed: 12    32.457
Unnamed: 13       102
Name: 139, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3606
Unnamed: 8     3606
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     102
Name: 140, dtype: object, Unnamed: 4       3603
Unnamed: 5       3622
Unnamed: 6       3603
Unnamed: 7       3622
Unnamed: 8       3612
Unnamed: 9         16
Unnamed: 10         6
Unnamed: 11         4
Unnamed: 12    21.675
Unnamed: 13       102
Name: 141, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3612
Unnamed: 8     3612
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     102
Name: 142, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3612
Unnamed: 8     3612
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     102
Name: 143, dtype: object, Unnamed: 4       3649
Unnamed: 5       3649
Unnamed: 6       3631
Unnamed: 7       3631
Unnamed: 8       3639
Unnamed: 9         19
Unnamed: 10        27
Unnamed: 11         8
Unnamed: 12    43.677
Unnamed: 13       100
Name: 144, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3639
Unnamed: 8     3639
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     100
Name: 145, dtype: object, Unnamed: 4       3604
Unnamed: 5       3614
Unnamed: 6       3593
Unnamed: 7       3597
Unnamed: 8       3599
Unnamed: 9        -42
Unnamed: 10       -40
Unnamed: 11        24
Unnamed: 12    129.57
Unnamed: 13        86
Name: 146, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3599
Unnamed: 8     3599
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      86
Name: 147, dtype: object, Unnamed: 4      3574
Unnamed: 5      3578
Unnamed: 6      3574
Unnamed: 7      3578
Unnamed: 8      3576
Unnamed: 9       -21
Unnamed: 10      -23
Unnamed: 11        6
Unnamed: 12    32.19
Unnamed: 13       86
Name: 148, dtype: object, Unnamed: 4        3576
Unnamed: 5        3581
Unnamed: 6        3574
Unnamed: 7        3581
Unnamed: 8        3576
Unnamed: 9           5
Unnamed: 10          0
Unnamed: 11         28
Unnamed: 12    150.198
Unnamed: 13        106
Name: 149, dtype: object, Unnamed: 4       3588
Unnamed: 5       3588
Unnamed: 6       3571
Unnamed: 7       3571
Unnamed: 8       3578
Unnamed: 9         -5
Unnamed: 10         2
Unnamed: 11        14
Unnamed: 12    75.153
Unnamed: 13       114
Name: 150, dtype: object, Unnamed: 4       3582
Unnamed: 5       3582
Unnamed: 6       3580
Unnamed: 7       3580
Unnamed: 8       3581
Unnamed: 9          2
Unnamed: 10         3
Unnamed: 11        14
Unnamed: 12    75.204
Unnamed: 13       122
Name: 151, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3581
Unnamed: 8     3581
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 152, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3575
Unnamed: 8     3575
Unnamed: 9       -6
Unnamed: 10      -6
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 153, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3575
Unnamed: 8     3575
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 154, dtype: object, Unnamed: 4        3569
Unnamed: 5        3577
Unnamed: 6        3569
Unnamed: 7        3576
Unnamed: 8        3575
Unnamed: 9           1
Unnamed: 10          0
Unnamed: 11         20
Unnamed: 12    107.265
Unnamed: 13        136
Name: 155, dtype: object, Unnamed: 4      3593
Unnamed: 5      3593
Unnamed: 6      3587
Unnamed: 7      3587
Unnamed: 8      3590
Unnamed: 9        12
Unnamed: 10       15
Unnamed: 11        4
Unnamed: 12    21.54
Unnamed: 13      140
Name: 156, dtype: object, Unnamed: 4       3596
Unnamed: 5       3596
Unnamed: 6       3593
Unnamed: 7       3593
Unnamed: 8       3594
Unnamed: 9          3
Unnamed: 10         4
Unnamed: 11         6
Unnamed: 12    32.349
Unnamed: 13       140
Name: 157, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3594
Unnamed: 8     3594
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     140
Name: 158, dtype: object]
21
length
[3611, 3611, 3600, 3600, 3607, 0, 0, 8, 43.29, 104]
21
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3612
Unnamed: 8     3612
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     102
Name: 142, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, -4.0, 3.0, 0.0, 0.0, 0.0, -6.0, -3.0, 5.0, 6.0, -1.0, -1.0, -1.0, -2.0, -10.832999999999998, -2.0, nan, nan, nan, 6.0, -1.0, 0.0, 0.0, -8.0, -43.29, -2.0, -8.0, 11.0, 3.0, 22.0, 5.0, 16.0, 6.0, -4.0, -21.615, -2.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3612
Unnamed: 8     3612
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     102
Name: 143, dtype: object
[-6.0, -3.0, 5.0, 6.0, -1.0, -1.0, -1.0, -2.0, -10.832999999999998, -2.0, nan, nan, nan, 6.0, -1.0, 0.0, 0.0, -8.0, -43.29, -2.0, -8.0, 11.0, 3.0, 22.0, 5.0, 16.0, 6.0, -4.0, -21.615, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, nan]
done
Unnamed: 4       3649
Unnamed: 5       3649
Unnamed: 6       3631
Unnamed: 7       3631
Unnamed: 8       3639
Unnamed: 9         19
Unnamed: 10        27
Unnamed: 11         8
Unnamed: 12    43.677
Unnamed: 13       100
Name: 144, dtype: object
[nan, nan, nan, 6.0, -1.0, 0.0, 0.0, -8.0, -43.29, -2.0, -8.0, 11.0, 3.0, 22.0, 5.0, 16.0, 6.0, -4.0, -21.615, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, -18]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3639
Unnamed: 8     3639
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     100
Name: 145, dtype: object
[-8.0, 11.0, 3.0, 22.0, 5.0, 16.0, 6.0, -4.0, -21.615, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, 38.0, 38.0, 31.0, 31.0, 32.0, 19.0, 27.0, 0.0, 0.38700000000000045, -4.0, nan]
done
Unnamed: 4       3604
Unnamed: 5       3614
Unnamed: 6       3593
Unnamed: 7       3597
Unnamed: 8       3599
Unnamed: 9        -42
Unnamed: 10       -40
Unnamed: 11        24
Unnamed: 12    129.57
Unnamed: 13        86
Name: 146, dtype: object
[nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, 38.0, 38.0, 31.0, 31.0, 32.0, 19.0, 27.0, 0.0, 0.38700000000000045, -4.0, nan, nan, nan, 39.0, 32.0, 0.0, 0.0, -8.0, -43.29, -4.0, -7]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3599
Unnamed: 8     3599
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13      86
Name: 147, dtype: object
[nan, nan, nan, 12.0, 5.0, 0.0, 0.0, -8.0, -43.29, -2.0, 38.0, 38.0, 31.0, 31.0, 32.0, 19.0, 27.0, 0.0, 0.38700000000000045, -4.0, nan, nan, nan, 39.0, 32.0, 0.0, 0.0, -8.0, -43.29, -4.0, -7.0, 3.0, -7.0, -3.0, -8.0, -42.0, -40.0, 16.0, 86.28, -18.0, nan]
done
Unnamed: 4      3574
Unnamed: 5      3578
Unnamed: 6      3574
Unnamed: 7      3578
Unnamed: 8      3576
Unnamed: 9       -21
Unnamed: 10      -23
Unnamed: 11        6
Unnamed: 12    32.19
Unnamed: 13       86
Name: 148, dtype: object
[38.0, 38.0, 31.0, 31.0, 32.0, 19.0, 27.0, 0.0, 0.38700000000000045, -4.0, nan, nan, nan, 39.0, 32.0, 0.0, 0.0, -8.0, -43.29, -4.0, -7.0, 3.0, -7.0, -3.0, -8.0, -42.0, -40.0, 16.0, 86.28, -18.0, nan, nan, nan, -1.0, -8.0, 0.0, 0.0, -8.0, -43.29, -18.0, 4]
done
Unnamed: 4        3576
Unnamed: 5        3581
Unnamed: 6        3574
Unnamed: 7        3581
Unnamed: 8        3576
Unnamed: 9           5
Unnamed: 10          0
Unnamed: 11         28
Unnamed: 12    150.198
Unnamed: 13        106
Name: 149, dtype: object
[nan, nan, nan, 39.0, 32.0, 0.0, 0.0, -8.0, -43.29, -4.0, -7.0, 3.0, -7.0, -3.0, -8.0, -42.0, -40.0, 16.0, 86.28, -18.0, nan, nan, nan, -1.0, -8.0, 0.0, 0.0, -8.0, -43.29, -18.0, -37.0, -33.0, -26.0, -22.0, -31.0, -21.0, -23.0, -2.0, -11.100000000000001, -18.0, 5]
done
Unnamed: 4       3588
Unnamed: 5       3588
Unnamed: 6       3571
Unnamed: 7       3571
Unnamed: 8       3578
Unnamed: 9         -5
Unnamed: 10         2
Unnamed: 11        14
Unnamed: 12    75.153
Unnamed: 13       114
Name: 150, dtype: object
[-7.0, 3.0, -7.0, -3.0, -8.0, -42.0, -40.0, 16.0, 86.28, -18.0, nan, nan, nan, -1.0, -8.0, 0.0, 0.0, -8.0, -43.29, -18.0, -37.0, -33.0, -26.0, -22.0, -31.0, -21.0, -23.0, -2.0, -11.100000000000001, -18.0, -35.0, -30.0, -26.0, -19.0, -31.0, 5.0, 0.0, 20.0, 106.90800000000002, 2.0, -17]
done
Unnamed: 4       3582
Unnamed: 5       3582
Unnamed: 6       3580
Unnamed: 7       3580
Unnamed: 8       3581
Unnamed: 9          2
Unnamed: 10         3
Unnamed: 11        14
Unnamed: 12    75.204
Unnamed: 13       122
Name: 151, dtype: object
[nan, nan, nan, -1.0, -8.0, 0.0, 0.0, -8.0, -43.29, -18.0, -37.0, -33.0, -26.0, -22.0, -31.0, -21.0, -23.0, -2.0, -11.100000000000001, -18.0, -35.0, -30.0, -26.0, -19.0, -31.0, 5.0, 0.0, 20.0, 106.90800000000002, 2.0, -23.0, -23.0, -29.0, -29.0, -29.0, -5.0, 2.0, 6.0, 31.863000000000007, 10.0, -2]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3581
Unnamed: 8     3581
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 152, dtype: object
[-37.0, -33.0, -26.0, -22.0, -31.0, -21.0, -23.0, -2.0, -11.100000000000001, -18.0, -35.0, -30.0, -26.0, -19.0, -31.0, 5.0, 0.0, 20.0, 106.90800000000002, 2.0, -23.0, -23.0, -29.0, -29.0, -29.0, -5.0, 2.0, 6.0, 31.863000000000007, 10.0, -29.0, -29.0, -20.0, -20.0, -26.0, 2.0, 3.0, 6.0, 31.913999999999994, 18.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3575
Unnamed: 8     3575
Unnamed: 9       -6
Unnamed: 10      -6
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 153, dtype: object
[-35.0, -30.0, -26.0, -19.0, -31.0, 5.0, 0.0, 20.0, 106.90800000000002, 2.0, -23.0, -23.0, -29.0, -29.0, -29.0, -5.0, 2.0, 6.0, 31.863000000000007, 10.0, -29.0, -29.0, -20.0, -20.0, -26.0, 2.0, 3.0, 6.0, 31.913999999999994, 18.0, nan, nan, nan, -19.0, -26.0, 0.0, 0.0, -8.0, -43.29, 18.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3575
Unnamed: 8     3575
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     122
Name: 154, dtype: object
[-23.0, -23.0, -29.0, -29.0, -29.0, -5.0, 2.0, 6.0, 31.863000000000007, 10.0, -29.0, -29.0, -20.0, -20.0, -26.0, 2.0, 3.0, 6.0, 31.913999999999994, 18.0, nan, nan, nan, -19.0, -26.0, 0.0, 0.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, -6.0, -6.0, -8.0, -43.29, 18.0, nan]
done
Unnamed: 4        3569
Unnamed: 5        3577
Unnamed: 6        3569
Unnamed: 7        3576
Unnamed: 8        3575
Unnamed: 9           1
Unnamed: 10          0
Unnamed: 11         20
Unnamed: 12    107.265
Unnamed: 13        136
Name: 155, dtype: object
[-29.0, -29.0, -20.0, -20.0, -26.0, 2.0, 3.0, 6.0, 31.913999999999994, 18.0, nan, nan, nan, -19.0, -26.0, 0.0, 0.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, -6.0, -6.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, 0.0, 0.0, -8.0, -43.29, 18.0, 7]
done
Unnamed: 4      3593
Unnamed: 5      3593
Unnamed: 6      3587
Unnamed: 7      3587
Unnamed: 8      3590
Unnamed: 9        12
Unnamed: 10       15
Unnamed: 11        4
Unnamed: 12    21.54
Unnamed: 13      140
Name: 156, dtype: object
[nan, nan, nan, -19.0, -26.0, 0.0, 0.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, -6.0, -6.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, 0.0, 0.0, -8.0, -43.29, 18.0, -42.0, -34.0, -31.0, -24.0, -32.0, 1.0, 0.0, 12.0, 63.975, 32.0, -6]
done
Unnamed: 4       3596
Unnamed: 5       3596
Unnamed: 6       3593
Unnamed: 7       3593
Unnamed: 8       3594
Unnamed: 9          3
Unnamed: 10         4
Unnamed: 11         6
Unnamed: 12    32.349
Unnamed: 13       140
Name: 157, dtype: object
[nan, nan, nan, -25.0, -32.0, -6.0, -6.0, -8.0, -43.29, 18.0, nan, nan, nan, -25.0, -32.0, 0.0, 0.0, -8.0, -43.29, 18.0, -42.0, -34.0, -31.0, -24.0, -32.0, 1.0, 0.0, 12.0, 63.975, 32.0, -18.0, -18.0, -13.0, -13.0, -17.0, 12.0, 15.0, -4.0, -21.75, 36.0, -3]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3594
Unnamed: 8     3594
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     140
Name: 158, dtype: object
[nan, nan, nan, -25.0, -32.0, 0.0, 0.0, -8.0, -43.29, 18.0, -42.0, -34.0, -31.0, -24.0, -32.0, 1.0, 0.0, 12.0, 63.975, 32.0, -18.0, -18.0, -13.0, -13.0, -17.0, 12.0, 15.0, -4.0, -21.75, 36.0, -15.0, -15.0, -7.0, -7.0, -13.0, 3.0, 4.0, -2.0, -10.941000000000003, 36.0, nan]
done
month is 5

                    所内合约行情报表  \
0      日期： 20190501-20190531
1                         合约
2                     ag1905
3                        NaN
4                        NaN
...                      ...
16818                    NaN
16819                    注：
16820                    NaN
16821                    NaN
16822                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190506       3527
3                                               20190507       3526
4                                               20190508       3528
...                                                  ...        ...
16818                                                NaN        NaN
16819  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
16820  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
16821            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
16822                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3522       3521       3528       3521       3526       3524
3           3524       3515       3548       3515       3528       3528
4           3528       3528       3536       3526       3536       3533
...          ...        ...        ...        ...        ...        ...
16818        NaN        NaN        NaN        NaN        NaN        NaN
16819        NaN        NaN        NaN        NaN        NaN        NaN
16820        NaN        NaN        NaN        NaN        NaN        NaN
16821        NaN        NaN        NaN        NaN        NaN        NaN
16822        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2              4           2          20     105.738         368 NaN
3              4           4         120       635.1         408 NaN
4              8           5         176     932.766         440 NaN
...          ...         ...         ...         ...         ...  ..
16818        NaN         NaN         NaN         NaN         NaN NaN
16819        NaN         NaN         NaN         NaN         NaN NaN
16820        NaN         NaN         NaN         NaN         NaN NaN
16821        NaN         NaN         NaN         NaN         NaN NaN
16822        NaN         NaN         NaN         NaN         NaN NaN

[16823 rows x 15 columns]
dddfff
[Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3594
Unnamed: 8     3594
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     140
Name: 110, dtype: object, Unnamed: 4        3584
Unnamed: 5        3584
Unnamed: 6        3583
Unnamed: 7        3584
Unnamed: 8        3583
Unnamed: 9         -10
Unnamed: 10        -11
Unnamed: 11         24
Unnamed: 12    129.012
Unnamed: 13        164
Name: 111, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3583
Unnamed: 8     3583
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     164
Name: 112, dtype: object, Unnamed: 4       3598
Unnamed: 5       3598
Unnamed: 6       3580
Unnamed: 7       3580
Unnamed: 8       3586
Unnamed: 9         -3
Unnamed: 10         3
Unnamed: 11        18
Unnamed: 12    96.825
Unnamed: 13       150
Name: 113, dtype: object, Unnamed: 4       3597
Unnamed: 5       3597
Unnamed: 6       3597
Unnamed: 7       3597
Unnamed: 8       3597
Unnamed: 9         11
Unnamed: 10        11
Unnamed: 11         4
Unnamed: 12    21.582
Unnamed: 13       150
Name: 114, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3597
Unnamed: 8     3597
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     150
Name: 115, dtype: object, Unnamed: 4       3619
Unnamed: 5       3620
Unnamed: 6       3619
Unnamed: 7       3620
Unnamed: 8       3619
Unnamed: 9         23
Unnamed: 10        22
Unnamed: 11         8
Unnamed: 12    43.431
Unnamed: 13       150
Name: 116, dtype: object, Unnamed: 4       3613
Unnamed: 5       3614
Unnamed: 6       3613
Unnamed: 7       3614
Unnamed: 8       3613
Unnamed: 9         -5
Unnamed: 10        -6
Unnamed: 11         6
Unnamed: 12    32.523
Unnamed: 13       156
Name: 117, dtype: object, Unnamed: 4       3612
Unnamed: 5       3612
Unnamed: 6       3612
Unnamed: 7       3612
Unnamed: 8       3612
Unnamed: 9         -1
Unnamed: 10        -1
Unnamed: 11         4
Unnamed: 12    21.672
Unnamed: 13       156
Name: 118, dtype: object, Unnamed: 4       3571
Unnamed: 5       3571
Unnamed: 6       3571
Unnamed: 7       3571
Unnamed: 8       3571
Unnamed: 9        -41
Unnamed: 10       -41
Unnamed: 11         4
Unnamed: 12    21.426
Unnamed: 13       158
Name: 119, dtype: object, Unnamed: 4       3549
Unnamed: 5       3549
Unnamed: 6       3547
Unnamed: 7       3547
Unnamed: 8       3548
Unnamed: 9        -24
Unnamed: 10       -23
Unnamed: 11         4
Unnamed: 12    21.288
Unnamed: 13       158
Name: 120, dtype: object, Unnamed: 4       3547
Unnamed: 5       3547
Unnamed: 6       3547
Unnamed: 7       3547
Unnamed: 8       3547
Unnamed: 9         -1
Unnamed: 10        -1
Unnamed: 11         6
Unnamed: 12    31.923
Unnamed: 13       164
Name: 121, dtype: object, Unnamed: 4        3549
Unnamed: 5        3555
Unnamed: 6        3546
Unnamed: 7        3555
Unnamed: 8        3549
Unnamed: 9           8
Unnamed: 10          2
Unnamed: 11         32
Unnamed: 12    170.367
Unnamed: 13        156
Name: 122, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3549
Unnamed: 8     3549
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     156
Name: 123, dtype: object, Unnamed: 4       3572
Unnamed: 5       3572
Unnamed: 6       3572
Unnamed: 7       3572
Unnamed: 8       3572
Unnamed: 9         23
Unnamed: 10        23
Unnamed: 11         2
Unnamed: 12    10.716
Unnamed: 13       156
Name: 124, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3572
Unnamed: 8     3572
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     156
Name: 125, dtype: object, Unnamed: 4        3559
Unnamed: 5        3565
Unnamed: 6        3558
Unnamed: 7        3565
Unnamed: 8        3560
Unnamed: 9          -7
Unnamed: 10        -12
Unnamed: 11         42
Unnamed: 12    224.337
Unnamed: 13        170
Name: 126, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3560
Unnamed: 8     3560
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     170
Name: 127, dtype: object, Unnamed: 4       3556
Unnamed: 5       3556
Unnamed: 6       3548
Unnamed: 7       3548
Unnamed: 8       3551
Unnamed: 9        -12
Unnamed: 10        -9
Unnamed: 11         8
Unnamed: 12    42.615
Unnamed: 13       168
Name: 128, dtype: object, Unnamed: 4       3556
Unnamed: 5       3556
Unnamed: 6       3556
Unnamed: 7       3556
Unnamed: 8       3556
Unnamed: 9          5
Unnamed: 10         5
Unnamed: 11         2
Unnamed: 12    10.668
Unnamed: 13       166
Name: 129, dtype: object]
20
length
[nan, nan, nan, 3594, 3594, 0, 0, 0, 0, 140]
20
Unnamed: 4       3597
Unnamed: 5       3597
Unnamed: 6       3597
Unnamed: 7       3597
Unnamed: 8       3597
Unnamed: 9         11
Unnamed: 10        11
Unnamed: 11         4
Unnamed: 12    21.582
Unnamed: 13       150
Name: 114, dtype: object
[nan, nan, nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, -10.0, -11.0, -10.0, -11.0, 24.0, 129.012, 24.0, nan, nan, nan, -11.0, -11.0, 0.0, 0.0, 0.0, 0.0, 24.0, nan, nan, nan, -14.0, -8.0, -3.0, 3.0, 18.0, 96.825, 10.0, 0]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3597
Unnamed: 8     3597
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     150
Name: 115, dtype: object
[nan, nan, nan, -10.0, -11.0, -10.0, -11.0, 24.0, 129.012, 24.0, nan, nan, nan, -11.0, -11.0, 0.0, 0.0, 0.0, 0.0, 24.0, nan, nan, nan, -14.0, -8.0, -3.0, 3.0, 18.0, 96.825, 10.0, nan, nan, nan, 3.0, 3.0, 11.0, 11.0, 4.0, 21.582, 10.0, nan]
done
Unnamed: 4       3619
Unnamed: 5       3620
Unnamed: 6       3619
Unnamed: 7       3620
Unnamed: 8       3619
Unnamed: 9         23
Unnamed: 10        22
Unnamed: 11         8
Unnamed: 12    43.431
Unnamed: 13       150
Name: 116, dtype: object
[nan, nan, nan, -11.0, -11.0, 0.0, 0.0, 0.0, 0.0, 24.0, nan, nan, nan, -14.0, -8.0, -3.0, 3.0, 18.0, 96.825, 10.0, nan, nan, nan, 3.0, 3.0, 11.0, 11.0, 4.0, 21.582, 10.0, nan, nan, nan, 3.0, 3.0, 0.0, 0.0, 0.0, 0.0, 10.0, 1]
done
Unnamed: 4       3613
Unnamed: 5       3614
Unnamed: 6       3613
Unnamed: 7       3614
Unnamed: 8       3613
Unnamed: 9         -5
Unnamed: 10        -6
Unnamed: 11         6
Unnamed: 12    32.523
Unnamed: 13       156
Name: 117, dtype: object
[nan, nan, nan, -14.0, -8.0, -3.0, 3.0, 18.0, 96.825, 10.0, nan, nan, nan, 3.0, 3.0, 11.0, 11.0, 4.0, 21.582, 10.0, nan, nan, nan, 3.0, 3.0, 0.0, 0.0, 0.0, 0.0, 10.0, nan, nan, nan, 26.0, 25.0, 23.0, 22.0, 8.0, 43.431, 10.0, 1]
done
Unnamed: 4       3612
Unnamed: 5       3612
Unnamed: 6       3612
Unnamed: 7       3612
Unnamed: 8       3612
Unnamed: 9         -1
Unnamed: 10        -1
Unnamed: 11         4
Unnamed: 12    21.672
Unnamed: 13       156
Name: 118, dtype: object
[nan, nan, nan, 3.0, 3.0, 11.0, 11.0, 4.0, 21.582, 10.0, nan, nan, nan, 3.0, 3.0, 0.0, 0.0, 0.0, 0.0, 10.0, nan, nan, nan, 26.0, 25.0, 23.0, 22.0, 8.0, 43.431, 10.0, nan, nan, nan, 20.0, 19.0, -5.0, -6.0, 6.0, 32.523, 16.0, 0]
done
Unnamed: 4       3571
Unnamed: 5       3571
Unnamed: 6       3571
Unnamed: 7       3571
Unnamed: 8       3571
Unnamed: 9        -41
Unnamed: 10       -41
Unnamed: 11         4
Unnamed: 12    21.426
Unnamed: 13       158
Name: 119, dtype: object
[nan, nan, nan, 3.0, 3.0, 0.0, 0.0, 0.0, 0.0, 10.0, nan, nan, nan, 26.0, 25.0, 23.0, 22.0, 8.0, 43.431, 10.0, nan, nan, nan, 20.0, 19.0, -5.0, -6.0, 6.0, 32.523, 16.0, nan, nan, nan, 18.0, 18.0, -1.0, -1.0, 4.0, 21.672, 16.0, 0]
done
Unnamed: 4       3549
Unnamed: 5       3549
Unnamed: 6       3547
Unnamed: 7       3547
Unnamed: 8       3548
Unnamed: 9        -24
Unnamed: 10       -23
Unnamed: 11         4
Unnamed: 12    21.288
Unnamed: 13       158
Name: 120, dtype: object
[nan, nan, nan, 26.0, 25.0, 23.0, 22.0, 8.0, 43.431, 10.0, nan, nan, nan, 20.0, 19.0, -5.0, -6.0, 6.0, 32.523, 16.0, nan, nan, nan, 18.0, 18.0, -1.0, -1.0, 4.0, 21.672, 16.0, nan, nan, nan, -23.0, -23.0, -41.0, -41.0, 4.0, 21.426, 18.0, -2]
done
Unnamed: 4       3547
Unnamed: 5       3547
Unnamed: 6       3547
Unnamed: 7       3547
Unnamed: 8       3547
Unnamed: 9         -1
Unnamed: 10        -1
Unnamed: 11         6
Unnamed: 12    31.923
Unnamed: 13       164
Name: 121, dtype: object
[nan, nan, nan, 20.0, 19.0, -5.0, -6.0, 6.0, 32.523, 16.0, nan, nan, nan, 18.0, 18.0, -1.0, -1.0, 4.0, 21.672, 16.0, nan, nan, nan, -23.0, -23.0, -41.0, -41.0, 4.0, 21.426, 18.0, nan, nan, nan, -47.0, -46.0, -24.0, -23.0, 4.0, 21.288, 18.0, 0]
done
Unnamed: 4        3549
Unnamed: 5        3555
Unnamed: 6        3546
Unnamed: 7        3555
Unnamed: 8        3549
Unnamed: 9           8
Unnamed: 10          2
Unnamed: 11         32
Unnamed: 12    170.367
Unnamed: 13        156
Name: 122, dtype: object
[nan, nan, nan, 18.0, 18.0, -1.0, -1.0, 4.0, 21.672, 16.0, nan, nan, nan, -23.0, -23.0, -41.0, -41.0, 4.0, 21.426, 18.0, nan, nan, nan, -47.0, -46.0, -24.0, -23.0, 4.0, 21.288, 18.0, nan, nan, nan, -47.0, -47.0, -1.0, -1.0, 6.0, 31.923, 24.0, 6]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3549
Unnamed: 8     3549
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     156
Name: 123, dtype: object
[nan, nan, nan, -23.0, -23.0, -41.0, -41.0, 4.0, 21.426, 18.0, nan, nan, nan, -47.0, -46.0, -24.0, -23.0, 4.0, 21.288, 18.0, nan, nan, nan, -47.0, -47.0, -1.0, -1.0, 6.0, 31.923, 24.0, nan, nan, nan, -39.0, -45.0, 8.0, 2.0, 32.0, 170.367, 16.0, nan]
done
Unnamed: 4       3572
Unnamed: 5       3572
Unnamed: 6       3572
Unnamed: 7       3572
Unnamed: 8       3572
Unnamed: 9         23
Unnamed: 10        23
Unnamed: 11         2
Unnamed: 12    10.716
Unnamed: 13       156
Name: 124, dtype: object
[nan, nan, nan, -47.0, -46.0, -24.0, -23.0, 4.0, 21.288, 18.0, nan, nan, nan, -47.0, -47.0, -1.0, -1.0, 6.0, 31.923, 24.0, nan, nan, nan, -39.0, -45.0, 8.0, 2.0, 32.0, 170.367, 16.0, nan, nan, nan, -45.0, -45.0, 0.0, 0.0, 0.0, 0.0, 16.0, 0]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3572
Unnamed: 8     3572
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     156
Name: 125, dtype: object
[nan, nan, nan, -47.0, -47.0, -1.0, -1.0, 6.0, 31.923, 24.0, nan, nan, nan, -39.0, -45.0, 8.0, 2.0, 32.0, 170.367, 16.0, nan, nan, nan, -45.0, -45.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -22.0, -22.0, 23.0, 23.0, 2.0, 10.716, 16.0, nan]
done
Unnamed: 4        3559
Unnamed: 5        3565
Unnamed: 6        3558
Unnamed: 7        3565
Unnamed: 8        3560
Unnamed: 9          -7
Unnamed: 10        -12
Unnamed: 11         42
Unnamed: 12    224.337
Unnamed: 13        170
Name: 126, dtype: object
[nan, nan, nan, -39.0, -45.0, 8.0, 2.0, 32.0, 170.367, 16.0, nan, nan, nan, -45.0, -45.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -22.0, -22.0, 23.0, 23.0, 2.0, 10.716, 16.0, nan, nan, nan, -22.0, -22.0, 0.0, 0.0, 0.0, 0.0, 16.0, 6]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3560
Unnamed: 8     3560
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     170
Name: 127, dtype: object
[nan, nan, nan, -45.0, -45.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -22.0, -22.0, 23.0, 23.0, 2.0, 10.716, 16.0, nan, nan, nan, -22.0, -22.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -29.0, -34.0, -7.0, -12.0, 42.0, 224.337, 30.0, nan]
done
Unnamed: 4       3556
Unnamed: 5       3556
Unnamed: 6       3548
Unnamed: 7       3548
Unnamed: 8       3551
Unnamed: 9        -12
Unnamed: 10        -9
Unnamed: 11         8
Unnamed: 12    42.615
Unnamed: 13       168
Name: 128, dtype: object
[nan, nan, nan, -22.0, -22.0, 23.0, 23.0, 2.0, 10.716, 16.0, nan, nan, nan, -22.0, -22.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -29.0, -34.0, -7.0, -12.0, 42.0, 224.337, 30.0, nan, nan, nan, -34.0, -34.0, 0.0, 0.0, 0.0, 0.0, 30.0, -8]
done
Unnamed: 4       3556
Unnamed: 5       3556
Unnamed: 6       3556
Unnamed: 7       3556
Unnamed: 8       3556
Unnamed: 9          5
Unnamed: 10         5
Unnamed: 11         2
Unnamed: 12    10.668
Unnamed: 13       166
Name: 129, dtype: object
[nan, nan, nan, -22.0, -22.0, 0.0, 0.0, 0.0, 0.0, 16.0, nan, nan, nan, -29.0, -34.0, -7.0, -12.0, 42.0, 224.337, 30.0, nan, nan, nan, -34.0, -34.0, 0.0, 0.0, 0.0, 0.0, 30.0, nan, nan, nan, -46.0, -43.0, -12.0, -9.0, 8.0, 42.615, 28.0, 0]
done
month is 6

                    所内合约行情报表  \
0      日期： 20190601-20190630
1                         合约
2                     ag1906
3                        NaN
4                        NaN
...                      ...
16140                    NaN
16141                    注：
16142                    NaN
16143                    NaN
16144                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                               20190603       3518
3                                               20190604       3529
4                                               20190605       3557
...                                                  ...        ...
16140                                                NaN        NaN
16141  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
16142  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
16143            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
16144                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

      Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            前结算        开盘价        最高价        最低价        收盘价        结算价
2           3515       3521       3552       3516       3529       3535
3           3535       3554       3563       3543       3557       3556
4           3556       3552       3580       3547       3569       3563
...          ...        ...        ...        ...        ...        ...
16140        NaN        NaN        NaN        NaN        NaN        NaN
16141        NaN        NaN        NaN        NaN        NaN        NaN
16142        NaN        NaN        NaN        NaN        NaN        NaN
16143        NaN        NaN        NaN        NaN        NaN        NaN
16144        NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2             14          20       12526     66425.8       30204 NaN
3             22          21       10760     57397.6       25536 NaN
4             13           7        5768     30827.4       24092 NaN
...          ...         ...         ...         ...         ...  ..
16140        NaN         NaN         NaN         NaN         NaN NaN
16141        NaN         NaN         NaN         NaN         NaN NaN
16142        NaN         NaN         NaN         NaN         NaN NaN
16143        NaN         NaN         NaN         NaN         NaN NaN
16144        NaN         NaN         NaN         NaN         NaN NaN

[16145 rows x 15 columns]
dddfff
[Unnamed: 4       3574
Unnamed: 5       3574
Unnamed: 6       3574
Unnamed: 7       3574
Unnamed: 8       3574
Unnamed: 9         18
Unnamed: 10        18
Unnamed: 11         2
Unnamed: 12    10.722
Unnamed: 13       166
Name: 88, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3574
Unnamed: 8     3574
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     166
Name: 89, dtype: object, Unnamed: 4       3615
Unnamed: 5       3615
Unnamed: 6       3606
Unnamed: 7       3606
Unnamed: 8       3610
Unnamed: 9         32
Unnamed: 10        36
Unnamed: 11         4
Unnamed: 12    21.663
Unnamed: 13       166
Name: 90, dtype: object, Unnamed: 4       3624
Unnamed: 5       3624
Unnamed: 6       3621
Unnamed: 7       3621
Unnamed: 8       3623
Unnamed: 9         11
Unnamed: 10        13
Unnamed: 11        12
Unnamed: 12    65.214
Unnamed: 13       174
Name: 91, dtype: object, Unnamed: 4      3620
Unnamed: 5      3620
Unnamed: 6      3620
Unnamed: 7      3620
Unnamed: 8      3620
Unnamed: 9        -3
Unnamed: 10       -3
Unnamed: 11        8
Unnamed: 12    43.44
Unnamed: 13      166
Name: 92, dtype: object, Unnamed: 4       3620
Unnamed: 5       3620
Unnamed: 6       3595
Unnamed: 7       3596
Unnamed: 8       3605
Unnamed: 9        -24
Unnamed: 10       -15
Unnamed: 11        12
Unnamed: 12    64.899
Unnamed: 13       162
Name: 93, dtype: object, Unnamed: 4       3588
Unnamed: 5       3596
Unnamed: 6       3588
Unnamed: 7       3596
Unnamed: 8       3592
Unnamed: 9         -9
Unnamed: 10       -13
Unnamed: 11         4
Unnamed: 12    21.552
Unnamed: 13       164
Name: 94, dtype: object, Unnamed: 4       3616
Unnamed: 5       3622
Unnamed: 6       3616
Unnamed: 7       3620
Unnamed: 8       3619
Unnamed: 9         28
Unnamed: 10        27
Unnamed: 11         6
Unnamed: 12    32.574
Unnamed: 13       164
Name: 95, dtype: object, Unnamed: 4       3642
Unnamed: 5       3644
Unnamed: 6       3642
Unnamed: 7       3644
Unnamed: 8       3643
Unnamed: 9         25
Unnamed: 10        24
Unnamed: 11         8
Unnamed: 12    43.722
Unnamed: 13       164
Name: 96, dtype: object, Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3647
Unnamed: 7       3647
Unnamed: 8       3653
Unnamed: 9          4
Unnamed: 10        10
Unnamed: 11        10
Unnamed: 12    54.804
Unnamed: 13       158
Name: 97, dtype: object, Unnamed: 4        3624
Unnamed: 5        3627
Unnamed: 6        3624
Unnamed: 7        3627
Unnamed: 8        3624
Unnamed: 9         -26
Unnamed: 10        -29
Unnamed: 11         20
Unnamed: 12    108.738
Unnamed: 13        168
Name: 98, dtype: object, Unnamed: 4       3647
Unnamed: 5       3647
Unnamed: 6       3626
Unnamed: 7       3627
Unnamed: 8       3640
Unnamed: 9          3
Unnamed: 10        16
Unnamed: 11        12
Unnamed: 12    65.523
Unnamed: 13       166
Name: 99, dtype: object, Unnamed: 4        3634
Unnamed: 5        3715
Unnamed: 6        3634
Unnamed: 7        3704
Unnamed: 8        3662
Unnamed: 9          64
Unnamed: 10         22
Unnamed: 11         24
Unnamed: 12    131.865
Unnamed: 13        166
Name: 100, dtype: object, Unnamed: 4       3706
Unnamed: 5       3724
Unnamed: 6       3706
Unnamed: 7       3724
Unnamed: 8       3718
Unnamed: 9         62
Unnamed: 10        56
Unnamed: 11         6
Unnamed: 12    33.462
Unnamed: 13       166
Name: 101, dtype: object, Unnamed: 4       3706
Unnamed: 5       3722
Unnamed: 6       3706
Unnamed: 7       3722
Unnamed: 8       3710
Unnamed: 9          4
Unnamed: 10        -8
Unnamed: 11        14
Unnamed: 12    77.928
Unnamed: 13       166
Name: 102, dtype: object, Unnamed: 4       3715
Unnamed: 5       3737
Unnamed: 6       3711
Unnamed: 7       3737
Unnamed: 8       3719
Unnamed: 9         27
Unnamed: 10         9
Unnamed: 11         8
Unnamed: 12    44.634
Unnamed: 13       164
Name: 103, dtype: object, Unnamed: 4       3698
Unnamed: 5       3698
Unnamed: 6       3698
Unnamed: 7       3698
Unnamed: 8       3698
Unnamed: 9        -21
Unnamed: 10       -21
Unnamed: 11         2
Unnamed: 12    11.094
Unnamed: 13       162
Name: 104, dtype: object, Unnamed: 4       3696
Unnamed: 5       3701
Unnamed: 6       3695
Unnamed: 7       3701
Unnamed: 8       3696
Unnamed: 9          3
Unnamed: 10        -2
Unnamed: 11        12
Unnamed: 12    66.543
Unnamed: 13       162
Name: 105, dtype: object, Unnamed: 4       3701
Unnamed: 5       3701
Unnamed: 6       3675
Unnamed: 7       3675
Unnamed: 8       3684
Unnamed: 9        -21
Unnamed: 10       -12
Unnamed: 11         6
Unnamed: 12    33.159
Unnamed: 13       162
Name: 106, dtype: object]
19
length
[3574, 3574, 3574, 3574, 3574, 0, 0, 2, 10.722, 166]
19
Unnamed: 4      3620
Unnamed: 5      3620
Unnamed: 6      3620
Unnamed: 7      3620
Unnamed: 8      3620
Unnamed: 9        -3
Unnamed: 10       -3
Unnamed: 11        8
Unnamed: 12    43.44
Unnamed: 13      166
Name: 92, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, 18.0, 18.0, 0.0, 0.0, 0.0, nan, nan, nan, 0.0, 0.0, 0.0, 0.0, -2.0, -10.722, 0.0, 41.0, 41.0, 32.0, 32.0, 36.0, 32.0, 36.0, 2.0, 10.941, 0.0, 50.0, 50.0, 47.0, 47.0, 49.0, 11.0, 13.0, 10.0, 54.492, 8.0, 0]
done
Unnamed: 4       3620
Unnamed: 5       3620
Unnamed: 6       3595
Unnamed: 7       3596
Unnamed: 8       3605
Unnamed: 9        -24
Unnamed: 10       -15
Unnamed: 11        12
Unnamed: 12    64.899
Unnamed: 13       162
Name: 93, dtype: object
[nan, nan, nan, 0.0, 0.0, 0.0, 0.0, -2.0, -10.722, 0.0, 41.0, 41.0, 32.0, 32.0, 36.0, 32.0, 36.0, 2.0, 10.941, 0.0, 50.0, 50.0, 47.0, 47.0, 49.0, 11.0, 13.0, 10.0, 54.492, 8.0, 46.0, 46.0, 46.0, 46.0, 46.0, -3.0, -3.0, 6.0, 32.717999999999996, 0.0, -24]
done
Unnamed: 4       3588
Unnamed: 5       3596
Unnamed: 6       3588
Unnamed: 7       3596
Unnamed: 8       3592
Unnamed: 9         -9
Unnamed: 10       -13
Unnamed: 11         4
Unnamed: 12    21.552
Unnamed: 13       164
Name: 94, dtype: object
[41.0, 41.0, 32.0, 32.0, 36.0, 32.0, 36.0, 2.0, 10.941, 0.0, 50.0, 50.0, 47.0, 47.0, 49.0, 11.0, 13.0, 10.0, 54.492, 8.0, 46.0, 46.0, 46.0, 46.0, 46.0, -3.0, -3.0, 6.0, 32.717999999999996, 0.0, 46.0, 46.0, 21.0, 22.0, 31.0, -24.0, -15.0, 10.0, 54.177, -4.0, 8]
done
Unnamed: 4       3616
Unnamed: 5       3622
Unnamed: 6       3616
Unnamed: 7       3620
Unnamed: 8       3619
Unnamed: 9         28
Unnamed: 10        27
Unnamed: 11         6
Unnamed: 12    32.574
Unnamed: 13       164
Name: 95, dtype: object
[50.0, 50.0, 47.0, 47.0, 49.0, 11.0, 13.0, 10.0, 54.492, 8.0, 46.0, 46.0, 46.0, 46.0, 46.0, -3.0, -3.0, 6.0, 32.717999999999996, 0.0, 46.0, 46.0, 21.0, 22.0, 31.0, -24.0, -15.0, 10.0, 54.177, -4.0, 14.0, 22.0, 14.0, 22.0, 18.0, -9.0, -13.0, 2.0, 10.83, -2.0, 4]
done
Unnamed: 4       3642
Unnamed: 5       3644
Unnamed: 6       3642
Unnamed: 7       3644
Unnamed: 8       3643
Unnamed: 9         25
Unnamed: 10        24
Unnamed: 11         8
Unnamed: 12    43.722
Unnamed: 13       164
Name: 96, dtype: object
[46.0, 46.0, 46.0, 46.0, 46.0, -3.0, -3.0, 6.0, 32.717999999999996, 0.0, 46.0, 46.0, 21.0, 22.0, 31.0, -24.0, -15.0, 10.0, 54.177, -4.0, 14.0, 22.0, 14.0, 22.0, 18.0, -9.0, -13.0, 2.0, 10.83, -2.0, 42.0, 48.0, 42.0, 46.0, 45.0, 28.0, 27.0, 4.0, 21.851999999999997, -2.0, 2]
done
Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3647
Unnamed: 7       3647
Unnamed: 8       3653
Unnamed: 9          4
Unnamed: 10        10
Unnamed: 11        10
Unnamed: 12    54.804
Unnamed: 13       158
Name: 97, dtype: object
[46.0, 46.0, 21.0, 22.0, 31.0, -24.0, -15.0, 10.0, 54.177, -4.0, 14.0, 22.0, 14.0, 22.0, 18.0, -9.0, -13.0, 2.0, 10.83, -2.0, 42.0, 48.0, 42.0, 46.0, 45.0, 28.0, 27.0, 4.0, 21.851999999999997, -2.0, 68.0, 70.0, 68.0, 70.0, 69.0, 25.0, 24.0, 6.0, 33.0, -2.0, -9]
done
Unnamed: 4        3624
Unnamed: 5        3627
Unnamed: 6        3624
Unnamed: 7        3627
Unnamed: 8        3624
Unnamed: 9         -26
Unnamed: 10        -29
Unnamed: 11         20
Unnamed: 12    108.738
Unnamed: 13        168
Name: 98, dtype: object
[14.0, 22.0, 14.0, 22.0, 18.0, -9.0, -13.0, 2.0, 10.83, -2.0, 42.0, 48.0, 42.0, 46.0, 45.0, 28.0, 27.0, 4.0, 21.851999999999997, -2.0, 68.0, 70.0, 68.0, 70.0, 69.0, 25.0, 24.0, 6.0, 33.0, -2.0, 82.0, 82.0, 73.0, 73.0, 79.0, 4.0, 10.0, 8.0, 44.082, -8.0, 3]
done
Unnamed: 4       3647
Unnamed: 5       3647
Unnamed: 6       3626
Unnamed: 7       3627
Unnamed: 8       3640
Unnamed: 9          3
Unnamed: 10        16
Unnamed: 11        12
Unnamed: 12    65.523
Unnamed: 13       166
Name: 99, dtype: object
[42.0, 48.0, 42.0, 46.0, 45.0, 28.0, 27.0, 4.0, 21.851999999999997, -2.0, 68.0, 70.0, 68.0, 70.0, 69.0, 25.0, 24.0, 6.0, 33.0, -2.0, 82.0, 82.0, 73.0, 73.0, 79.0, 4.0, 10.0, 8.0, 44.082, -8.0, 50.0, 53.0, 50.0, 53.0, 50.0, -26.0, -29.0, 18.0, 98.016, 2.0, -20]
done
Unnamed: 4        3634
Unnamed: 5        3715
Unnamed: 6        3634
Unnamed: 7        3704
Unnamed: 8        3662
Unnamed: 9          64
Unnamed: 10         22
Unnamed: 11         24
Unnamed: 12    131.865
Unnamed: 13        166
Name: 100, dtype: object
[68.0, 70.0, 68.0, 70.0, 69.0, 25.0, 24.0, 6.0, 33.0, -2.0, 82.0, 82.0, 73.0, 73.0, 79.0, 4.0, 10.0, 8.0, 44.082, -8.0, 50.0, 53.0, 50.0, 53.0, 50.0, -26.0, -29.0, 18.0, 98.016, 2.0, 73.0, 73.0, 52.0, 53.0, 66.0, 3.0, 16.0, 10.0, 54.800999999999995, 0.0, 70]
done
Unnamed: 4       3706
Unnamed: 5       3724
Unnamed: 6       3706
Unnamed: 7       3724
Unnamed: 8       3718
Unnamed: 9         62
Unnamed: 10        56
Unnamed: 11         6
Unnamed: 12    33.462
Unnamed: 13       166
Name: 101, dtype: object
[82.0, 82.0, 73.0, 73.0, 79.0, 4.0, 10.0, 8.0, 44.082, -8.0, 50.0, 53.0, 50.0, 53.0, 50.0, -26.0, -29.0, 18.0, 98.016, 2.0, 73.0, 73.0, 52.0, 53.0, 66.0, 3.0, 16.0, 10.0, 54.800999999999995, 0.0, 60.0, 141.0, 60.0, 130.0, 88.0, 64.0, 22.0, 22.0, 121.14300000000001, 0.0, 18]
done
Unnamed: 4       3706
Unnamed: 5       3722
Unnamed: 6       3706
Unnamed: 7       3722
Unnamed: 8       3710
Unnamed: 9          4
Unnamed: 10        -8
Unnamed: 11        14
Unnamed: 12    77.928
Unnamed: 13       166
Name: 102, dtype: object
[50.0, 53.0, 50.0, 53.0, 50.0, -26.0, -29.0, 18.0, 98.016, 2.0, 73.0, 73.0, 52.0, 53.0, 66.0, 3.0, 16.0, 10.0, 54.800999999999995, 0.0, 60.0, 141.0, 60.0, 130.0, 88.0, 64.0, 22.0, 22.0, 121.14300000000001, 0.0, 132.0, 150.0, 132.0, 150.0, 144.0, 62.0, 56.0, 4.0, 22.740000000000002, 0.0, 16]
done
Unnamed: 4       3715
Unnamed: 5       3737
Unnamed: 6       3711
Unnamed: 7       3737
Unnamed: 8       3719
Unnamed: 9         27
Unnamed: 10         9
Unnamed: 11         8
Unnamed: 12    44.634
Unnamed: 13       164
Name: 103, dtype: object
[73.0, 73.0, 52.0, 53.0, 66.0, 3.0, 16.0, 10.0, 54.800999999999995, 0.0, 60.0, 141.0, 60.0, 130.0, 88.0, 64.0, 22.0, 22.0, 121.14300000000001, 0.0, 132.0, 150.0, 132.0, 150.0, 144.0, 62.0, 56.0, 4.0, 22.740000000000002, 0.0, 132.0, 148.0, 132.0, 148.0, 136.0, 4.0, -8.0, 12.0, 67.206, 0.0, 22]
done
Unnamed: 4       3698
Unnamed: 5       3698
Unnamed: 6       3698
Unnamed: 7       3698
Unnamed: 8       3698
Unnamed: 9        -21
Unnamed: 10       -21
Unnamed: 11         2
Unnamed: 12    11.094
Unnamed: 13       162
Name: 104, dtype: object
[60.0, 141.0, 60.0, 130.0, 88.0, 64.0, 22.0, 22.0, 121.14300000000001, 0.0, 132.0, 150.0, 132.0, 150.0, 144.0, 62.0, 56.0, 4.0, 22.740000000000002, 0.0, 132.0, 148.0, 132.0, 148.0, 136.0, 4.0, -8.0, 12.0, 67.206, 0.0, 141.0, 163.0, 137.0, 163.0, 145.0, 27.0, 9.0, 6.0, 33.912, -2.0, 0]
done
Unnamed: 4       3696
Unnamed: 5       3701
Unnamed: 6       3695
Unnamed: 7       3701
Unnamed: 8       3696
Unnamed: 9          3
Unnamed: 10        -2
Unnamed: 11        12
Unnamed: 12    66.543
Unnamed: 13       162
Name: 105, dtype: object
[132.0, 150.0, 132.0, 150.0, 144.0, 62.0, 56.0, 4.0, 22.740000000000002, 0.0, 132.0, 148.0, 132.0, 148.0, 136.0, 4.0, -8.0, 12.0, 67.206, 0.0, 141.0, 163.0, 137.0, 163.0, 145.0, 27.0, 9.0, 6.0, 33.912, -2.0, 124.0, 124.0, 124.0, 124.0, 124.0, -21.0, -21.0, 0.0, 0.3719999999999999, -4.0, 5]
done
Unnamed: 4       3701
Unnamed: 5       3701
Unnamed: 6       3675
Unnamed: 7       3675
Unnamed: 8       3684
Unnamed: 9        -21
Unnamed: 10       -12
Unnamed: 11         6
Unnamed: 12    33.159
Unnamed: 13       162
Name: 106, dtype: object
[132.0, 148.0, 132.0, 148.0, 136.0, 4.0, -8.0, 12.0, 67.206, 0.0, 141.0, 163.0, 137.0, 163.0, 145.0, 27.0, 9.0, 6.0, 33.912, -2.0, 124.0, 124.0, 124.0, 124.0, 124.0, -21.0, -21.0, 0.0, 0.3719999999999999, -4.0, 122.0, 127.0, 121.0, 127.0, 122.0, 3.0, -2.0, 10.0, 55.821000000000005, -4.0, -26]
done
month is 7

                    所内合约行情报表  \
0      日期： 20190701-20190731
1                         合约
2                   Contract
3                     ag1907
4                        NaN
...                      ...
20641                    NaN
20642                    注：
20643                    NaN
20644                    NaN
20645                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                                   Date  pre close
3                                               20190701       3635
4                                               20190702       3570
...                                                  ...        ...
20641                                                NaN        NaN
20642  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
20643  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
20644            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
20645                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

       Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0             NaN        NaN        NaN        NaN        NaN        NaN
1             前结算        开盘价        最高价        最低价        收盘价        结算价
2      Pre settle       Open       High        Low      Close     Settle
3            3660       3570       3570       3570       3570       3570
4            3570       3570       3622       3559       3617       3599
...           ...        ...        ...        ...        ...        ...
20641         NaN        NaN        NaN        NaN        NaN        NaN
20642         NaN        NaN        NaN        NaN        NaN        NaN
20643         NaN        NaN        NaN        NaN        NaN        NaN
20644         NaN        NaN        NaN        NaN        NaN        NaN
20645         NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2            ch1         ch2      Volume      Amount          OI NaN
3            -90         -90           4       21.42         264 NaN
4             47          29          88     475.074         240 NaN
...          ...         ...         ...         ...         ...  ..
20641        NaN         NaN         NaN         NaN         NaN NaN
20642        NaN         NaN         NaN         NaN         NaN NaN
20643        NaN         NaN         NaN         NaN         NaN NaN
20644        NaN         NaN         NaN         NaN         NaN NaN
20645        NaN         NaN         NaN         NaN         NaN NaN

[20646 rows x 15 columns]
dddfff
[Unnamed: 4       3651
Unnamed: 5       3651
Unnamed: 6       3634
Unnamed: 7       3634
Unnamed: 8       3647
Unnamed: 9        -50
Unnamed: 10       -37
Unnamed: 11        10
Unnamed: 12    54.714
Unnamed: 13       154
Name: 83, dtype: object, Unnamed: 4      3658
Unnamed: 5      3666
Unnamed: 6      3658
Unnamed: 7      3662
Unnamed: 8      3662
Unnamed: 9        15
Unnamed: 10       15
Unnamed: 11       10
Unnamed: 12    54.93
Unnamed: 13      148
Name: 84, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3666
Unnamed: 8     3666
Unnamed: 9        4
Unnamed: 10       4
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     148
Name: 85, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3666
Unnamed: 8     3666
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     148
Name: 86, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3666
Unnamed: 8     3666
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     148
Name: 87, dtype: object, Unnamed: 4       3642
Unnamed: 5       3654
Unnamed: 6       3642
Unnamed: 7       3654
Unnamed: 8       3646
Unnamed: 9        -12
Unnamed: 10       -20
Unnamed: 11         6
Unnamed: 12    32.814
Unnamed: 13       144
Name: 88, dtype: object, Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3652
Unnamed: 7       3652
Unnamed: 8       3654
Unnamed: 9          6
Unnamed: 10         8
Unnamed: 11         6
Unnamed: 12    32.889
Unnamed: 13       144
Name: 89, dtype: object, Unnamed: 4       3651
Unnamed: 5       3651
Unnamed: 6       3651
Unnamed: 7       3651
Unnamed: 8       3651
Unnamed: 9         -3
Unnamed: 10        -3
Unnamed: 11         6
Unnamed: 12    32.859
Unnamed: 13       144
Name: 90, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3651
Unnamed: 8     3651
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     144
Name: 91, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3651
Unnamed: 8     3651
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     144
Name: 92, dtype: object, Unnamed: 4       3668
Unnamed: 5       3681
Unnamed: 6       3666
Unnamed: 7       3681
Unnamed: 8       3675
Unnamed: 9         30
Unnamed: 10        24
Unnamed: 11        10
Unnamed: 12    55.131
Unnamed: 13       144
Name: 93, dtype: object, Unnamed: 4       3713
Unnamed: 5       3713
Unnamed: 6       3713
Unnamed: 7       3713
Unnamed: 8       3713
Unnamed: 9         38
Unnamed: 10        38
Unnamed: 11         4
Unnamed: 12    22.278
Unnamed: 13       142
Name: 94, dtype: object, Unnamed: 4        3764
Unnamed: 5        3777
Unnamed: 6        3756
Unnamed: 7        3768
Unnamed: 8        3771
Unnamed: 9          55
Unnamed: 10         58
Unnamed: 11         56
Unnamed: 12    316.791
Unnamed: 13        154
Name: 95, dtype: object, Unnamed: 4        3822
Unnamed: 5        3895
Unnamed: 6        3822
Unnamed: 7        3875
Unnamed: 8        3869
Unnamed: 9         104
Unnamed: 10         98
Unnamed: 11         96
Unnamed: 12    557.151
Unnamed: 13        148
Name: 96, dtype: object, Unnamed: 4        3937
Unnamed: 5        3964
Unnamed: 6        3927
Unnamed: 7        3963
Unnamed: 8        3938
Unnamed: 9          94
Unnamed: 10         69
Unnamed: 11         38
Unnamed: 12    224.475
Unnamed: 13        144
Name: 97, dtype: object, Unnamed: 4        3959
Unnamed: 5        3974
Unnamed: 6        3906
Unnamed: 7        3954
Unnamed: 8        3939
Unnamed: 9          16
Unnamed: 10          1
Unnamed: 11         42
Unnamed: 12    248.211
Unnamed: 13        120
Name: 98, dtype: object, Unnamed: 4       3943
Unnamed: 5       3943
Unnamed: 6       3904
Unnamed: 7       3904
Unnamed: 8       3919
Unnamed: 9        -35
Unnamed: 10       -20
Unnamed: 11        12
Unnamed: 12    70.557
Unnamed: 13       120
Name: 99, dtype: object, Unnamed: 4        3964
Unnamed: 5        3975
Unnamed: 6        3964
Unnamed: 7        3975
Unnamed: 8        3971
Unnamed: 9          56
Unnamed: 10         52
Unnamed: 11         28
Unnamed: 12    166.815
Unnamed: 13        130
Name: 100, dtype: object, Unnamed: 4        4003
Unnamed: 5        4005
Unnamed: 6        3951
Unnamed: 7        3977
Unnamed: 8        3974
Unnamed: 9           6
Unnamed: 10          3
Unnamed: 11         56
Unnamed: 12    333.819
Unnamed: 13        120
Name: 101, dtype: object, Unnamed: 4        3954
Unnamed: 5        3968
Unnamed: 6        3940
Unnamed: 7        3941
Unnamed: 8        3952
Unnamed: 9         -33
Unnamed: 10        -22
Unnamed: 11        100
Unnamed: 12    592.923
Unnamed: 13        172
Name: 102, dtype: object, Unnamed: 4       3967
Unnamed: 5       3967
Unnamed: 6       3943
Unnamed: 7       3956
Unnamed: 8       3961
Unnamed: 9          4
Unnamed: 10         9
Unnamed: 11        80
Unnamed: 12    475.41
Unnamed: 13       140
Name: 103, dtype: object, Unnamed: 4       3959
Unnamed: 5       3964
Unnamed: 6       3950
Unnamed: 7       3964
Unnamed: 8       3961
Unnamed: 9          3
Unnamed: 10         0
Unnamed: 11        16
Unnamed: 12    95.073
Unnamed: 13       134
Name: 104, dtype: object, Unnamed: 4       3974
Unnamed: 5       3974
Unnamed: 6       3965
Unnamed: 7       3972
Unnamed: 8       3969
Unnamed: 9         11
Unnamed: 10         8
Unnamed: 11        12
Unnamed: 12    71.448
Unnamed: 13       130
Name: 105, dtype: object]
23
length
[3651, 3651, 3634, 3634, 3647, 0, 0, 10, 54.714, 154]
23
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3666
Unnamed: 8     3666
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     148
Name: 87, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, -50.0, -37.0, 0.0, 0.0, 0.0, 7.0, 15.0, 24.0, 28.0, 15.0, 15.0, 15.0, 0.0, 0.21600000000000108, -6.0, nan, nan, nan, 32.0, 19.0, 4.0, 4.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, nan]
done
Unnamed: 4       3642
Unnamed: 5       3654
Unnamed: 6       3642
Unnamed: 7       3654
Unnamed: 8       3646
Unnamed: 9        -12
Unnamed: 10       -20
Unnamed: 11         6
Unnamed: 12    32.814
Unnamed: 13       144
Name: 88, dtype: object
[7.0, 15.0, 24.0, 28.0, 15.0, 15.0, 15.0, 0.0, 0.21600000000000108, -6.0, nan, nan, nan, 32.0, 19.0, 4.0, 4.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, 12]
done
Unnamed: 4       3656
Unnamed: 5       3656
Unnamed: 6       3652
Unnamed: 7       3652
Unnamed: 8       3654
Unnamed: 9          6
Unnamed: 10         8
Unnamed: 11         6
Unnamed: 12    32.889
Unnamed: 13       144
Name: 89, dtype: object
[nan, nan, nan, 32.0, 19.0, 4.0, 4.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, -9.0, 3.0, 8.0, 20.0, -1.0, -12.0, -20.0, -4.0, -21.9, -10.0, -4]
done
Unnamed: 4       3651
Unnamed: 5       3651
Unnamed: 6       3651
Unnamed: 7       3651
Unnamed: 8       3651
Unnamed: 9         -3
Unnamed: 10        -3
Unnamed: 11         6
Unnamed: 12    32.859
Unnamed: 13       144
Name: 90, dtype: object
[nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, -9.0, 3.0, 8.0, 20.0, -1.0, -12.0, -20.0, -4.0, -21.9, -10.0, 5.0, 5.0, 18.0, 18.0, 7.0, 6.0, 8.0, -4.0, -21.824999999999996, -10.0, 0]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3651
Unnamed: 8     3651
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     144
Name: 91, dtype: object
[nan, nan, nan, 32.0, 19.0, 0.0, 0.0, -10.0, -54.714, -6.0, -9.0, 3.0, 8.0, 20.0, -1.0, -12.0, -20.0, -4.0, -21.9, -10.0, 5.0, 5.0, 18.0, 18.0, 7.0, 6.0, 8.0, -4.0, -21.824999999999996, -10.0, 0.0, 0.0, 17.0, 17.0, 4.0, -3.0, -3.0, -4.0, -21.854999999999997, -10.0, nan]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3651
Unnamed: 8     3651
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     144
Name: 92, dtype: object
[-9.0, 3.0, 8.0, 20.0, -1.0, -12.0, -20.0, -4.0, -21.9, -10.0, 5.0, 5.0, 18.0, 18.0, 7.0, 6.0, 8.0, -4.0, -21.824999999999996, -10.0, 0.0, 0.0, 17.0, 17.0, 4.0, -3.0, -3.0, -4.0, -21.854999999999997, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, nan]
done
Unnamed: 4       3668
Unnamed: 5       3681
Unnamed: 6       3666
Unnamed: 7       3681
Unnamed: 8       3675
Unnamed: 9         30
Unnamed: 10        24
Unnamed: 11        10
Unnamed: 12    55.131
Unnamed: 13       144
Name: 93, dtype: object
[5.0, 5.0, 18.0, 18.0, 7.0, 6.0, 8.0, -4.0, -21.824999999999996, -10.0, 0.0, 0.0, 17.0, 17.0, 4.0, -3.0, -3.0, -4.0, -21.854999999999997, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, 13]
done
Unnamed: 4       3713
Unnamed: 5       3713
Unnamed: 6       3713
Unnamed: 7       3713
Unnamed: 8       3713
Unnamed: 9         38
Unnamed: 10        38
Unnamed: 11         4
Unnamed: 12    22.278
Unnamed: 13       142
Name: 94, dtype: object
[0.0, 0.0, 17.0, 17.0, 4.0, -3.0, -3.0, -4.0, -21.854999999999997, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, 17.0, 30.0, 32.0, 47.0, 28.0, 30.0, 24.0, 0.0, 0.4170000000000016, -10.0, 0]
done
Unnamed: 4        3764
Unnamed: 5        3777
Unnamed: 6        3756
Unnamed: 7        3768
Unnamed: 8        3771
Unnamed: 9          55
Unnamed: 10         58
Unnamed: 11         56
Unnamed: 12    316.791
Unnamed: 13        154
Name: 95, dtype: object
[nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, 17.0, 30.0, 32.0, 47.0, 28.0, 30.0, 24.0, 0.0, 0.4170000000000016, -10.0, 62.0, 62.0, 79.0, 79.0, 66.0, 38.0, 38.0, -6.0, -32.436, -12.0, 4]
done
Unnamed: 4        3822
Unnamed: 5        3895
Unnamed: 6        3822
Unnamed: 7        3875
Unnamed: 8        3869
Unnamed: 9         104
Unnamed: 10         98
Unnamed: 11         96
Unnamed: 12    557.151
Unnamed: 13        148
Name: 96, dtype: object
[nan, nan, nan, 17.0, 4.0, 0.0, 0.0, -10.0, -54.714, -10.0, 17.0, 30.0, 32.0, 47.0, 28.0, 30.0, 24.0, 0.0, 0.4170000000000016, -10.0, 62.0, 62.0, 79.0, 79.0, 66.0, 38.0, 38.0, -6.0, -32.436, -12.0, 113.0, 126.0, 122.0, 134.0, 124.0, 55.0, 58.0, 46.0, 262.077, 0.0, 53]
done
Unnamed: 4        3937
Unnamed: 5        3964
Unnamed: 6        3927
Unnamed: 7        3963
Unnamed: 8        3938
Unnamed: 9          94
Unnamed: 10         69
Unnamed: 11         38
Unnamed: 12    224.475
Unnamed: 13        144
Name: 97, dtype: object
[17.0, 30.0, 32.0, 47.0, 28.0, 30.0, 24.0, 0.0, 0.4170000000000016, -10.0, 62.0, 62.0, 79.0, 79.0, 66.0, 38.0, 38.0, -6.0, -32.436, -12.0, 113.0, 126.0, 122.0, 134.0, 124.0, 55.0, 58.0, 46.0, 262.077, 0.0, 171.0, 244.0, 188.0, 241.0, 222.0, 104.0, 98.0, 86.0, 502.43699999999995, -6.0, 26]
done
Unnamed: 4        3959
Unnamed: 5        3974
Unnamed: 6        3906
Unnamed: 7        3954
Unnamed: 8        3939
Unnamed: 9          16
Unnamed: 10          1
Unnamed: 11         42
Unnamed: 12    248.211
Unnamed: 13        120
Name: 98, dtype: object
[62.0, 62.0, 79.0, 79.0, 66.0, 38.0, 38.0, -6.0, -32.436, -12.0, 113.0, 126.0, 122.0, 134.0, 124.0, 55.0, 58.0, 46.0, 262.077, 0.0, 171.0, 244.0, 188.0, 241.0, 222.0, 104.0, 98.0, 86.0, 502.43699999999995, -6.0, 286.0, 313.0, 293.0, 329.0, 291.0, 94.0, 69.0, 28.0, 169.761, -10.0, -5]
done
Unnamed: 4       3943
Unnamed: 5       3943
Unnamed: 6       3904
Unnamed: 7       3904
Unnamed: 8       3919
Unnamed: 9        -35
Unnamed: 10       -20
Unnamed: 11        12
Unnamed: 12    70.557
Unnamed: 13       120
Name: 99, dtype: object
[113.0, 126.0, 122.0, 134.0, 124.0, 55.0, 58.0, 46.0, 262.077, 0.0, 171.0, 244.0, 188.0, 241.0, 222.0, 104.0, 98.0, 86.0, 502.43699999999995, -6.0, 286.0, 313.0, 293.0, 329.0, 291.0, 94.0, 69.0, 28.0, 169.761, -10.0, 308.0, 323.0, 272.0, 320.0, 292.0, 16.0, 1.0, 32.0, 193.497, -34.0, -39]
done
Unnamed: 4        3964
Unnamed: 5        3975
Unnamed: 6        3964
Unnamed: 7        3975
Unnamed: 8        3971
Unnamed: 9          56
Unnamed: 10         52
Unnamed: 11         28
Unnamed: 12    166.815
Unnamed: 13        130
Name: 100, dtype: object
[171.0, 244.0, 188.0, 241.0, 222.0, 104.0, 98.0, 86.0, 502.43699999999995, -6.0, 286.0, 313.0, 293.0, 329.0, 291.0, 94.0, 69.0, 28.0, 169.761, -10.0, 308.0, 323.0, 272.0, 320.0, 292.0, 16.0, 1.0, 32.0, 193.497, -34.0, 292.0, 292.0, 270.0, 270.0, 272.0, -35.0, -20.0, 2.0, 15.843000000000004, -34.0, 11]
done
Unnamed: 4        4003
Unnamed: 5        4005
Unnamed: 6        3951
Unnamed: 7        3977
Unnamed: 8        3974
Unnamed: 9           6
Unnamed: 10          3
Unnamed: 11         56
Unnamed: 12    333.819
Unnamed: 13        120
Name: 101, dtype: object
[286.0, 313.0, 293.0, 329.0, 291.0, 94.0, 69.0, 28.0, 169.761, -10.0, 308.0, 323.0, 272.0, 320.0, 292.0, 16.0, 1.0, 32.0, 193.497, -34.0, 292.0, 292.0, 270.0, 270.0, 272.0, -35.0, -20.0, 2.0, 15.843000000000004, -34.0, 313.0, 324.0, 330.0, 341.0, 324.0, 56.0, 52.0, 18.0, 112.101, -24.0, -26]
done
Unnamed: 4        3954
Unnamed: 5        3968
Unnamed: 6        3940
Unnamed: 7        3941
Unnamed: 8        3952
Unnamed: 9         -33
Unnamed: 10        -22
Unnamed: 11        100
Unnamed: 12    592.923
Unnamed: 13        172
Name: 102, dtype: object
[308.0, 323.0, 272.0, 320.0, 292.0, 16.0, 1.0, 32.0, 193.497, -34.0, 292.0, 292.0, 270.0, 270.0, 272.0, -35.0, -20.0, 2.0, 15.843000000000004, -34.0, 313.0, 324.0, 330.0, 341.0, 324.0, 56.0, 52.0, 18.0, 112.101, -24.0, 352.0, 354.0, 317.0, 343.0, 327.0, 6.0, 3.0, 46.0, 279.105, -34.0, -13]
done
Unnamed: 4       3967
Unnamed: 5       3967
Unnamed: 6       3943
Unnamed: 7       3956
Unnamed: 8       3961
Unnamed: 9          4
Unnamed: 10         9
Unnamed: 11        80
Unnamed: 12    475.41
Unnamed: 13       140
Name: 103, dtype: object
[292.0, 292.0, 270.0, 270.0, 272.0, -35.0, -20.0, 2.0, 15.843000000000004, -34.0, 313.0, 324.0, 330.0, 341.0, 324.0, 56.0, 52.0, 18.0, 112.101, -24.0, 352.0, 354.0, 317.0, 343.0, 327.0, 6.0, 3.0, 46.0, 279.105, -34.0, 303.0, 317.0, 306.0, 307.0, 305.0, -33.0, -22.0, 90.0, 538.2090000000001, 18.0, -11]
done
Unnamed: 4       3959
Unnamed: 5       3964
Unnamed: 6       3950
Unnamed: 7       3964
Unnamed: 8       3961
Unnamed: 9          3
Unnamed: 10         0
Unnamed: 11        16
Unnamed: 12    95.073
Unnamed: 13       134
Name: 104, dtype: object
[313.0, 324.0, 330.0, 341.0, 324.0, 56.0, 52.0, 18.0, 112.101, -24.0, 352.0, 354.0, 317.0, 343.0, 327.0, 6.0, 3.0, 46.0, 279.105, -34.0, 303.0, 317.0, 306.0, 307.0, 305.0, -33.0, -22.0, 90.0, 538.2090000000001, 18.0, 316.0, 316.0, 309.0, 322.0, 314.0, 4.0, 9.0, 70.0, 420.696, -14.0, 5]
done
Unnamed: 4       3974
Unnamed: 5       3974
Unnamed: 6       3965
Unnamed: 7       3972
Unnamed: 8       3969
Unnamed: 9         11
Unnamed: 10         8
Unnamed: 11        12
Unnamed: 12    71.448
Unnamed: 13       130
Name: 105, dtype: object
[352.0, 354.0, 317.0, 343.0, 327.0, 6.0, 3.0, 46.0, 279.105, -34.0, 303.0, 317.0, 306.0, 307.0, 305.0, -33.0, -22.0, 90.0, 538.2090000000001, 18.0, 316.0, 316.0, 309.0, 322.0, 314.0, 4.0, 9.0, 70.0, 420.696, -14.0, 308.0, 313.0, 316.0, 330.0, 314.0, 3.0, 0.0, 6.0, 40.358999999999995, -20.0, -2]
done
month is 8

          所内合约行情报表                                         Unnamed: 1  \
0       Daily Data                                                NaN
1               合约                                                 日期
2         Contract                                               Date
3           ag1908                                           20190801
4              NaN                                           20190802
...            ...                                                ...
20335          NaN                                                NaN
20336          注：   1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...
20337          NaN  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...
20338          NaN            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算
20339          NaN                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算

      Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0            NaN         NaN        NaN        NaN        NaN        NaN
1            前收盘         前结算        开盘价        最高价        最低价        收盘价
2      pre close  Pre settle       Open       High        Low      Close
3           3930        3934       3860       3860       3821       3821
4           3821        3827       3810       3810       3810       3810
...          ...         ...        ...        ...        ...        ...
20335        NaN         NaN        NaN        NaN        NaN        NaN
20336        NaN         NaN        NaN        NaN        NaN        NaN
20337        NaN         NaN        NaN        NaN        NaN        NaN
20338        NaN         NaN        NaN        NaN        NaN        NaN
20339        NaN         NaN        NaN        NaN        NaN        NaN

      Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN        NaN         NaN         NaN         NaN         NaN
1            结算价        涨跌1         涨跌2         成交量        成交金额         持仓量
2         Settle        ch1         ch2      Volume      Amount          OI
3           3827       -113        -107          24      137.79          88
4           3810        -17         -17          40       228.6         108
...          ...        ...         ...         ...         ...         ...
20335        NaN        NaN         NaN         NaN         NaN         NaN
20336        NaN        NaN         NaN         NaN         NaN         NaN
20337        NaN        NaN         NaN         NaN         NaN         NaN
20338        NaN        NaN         NaN         NaN         NaN         NaN
20339        NaN        NaN         NaN         NaN         NaN         NaN

[20340 rows x 14 columns]
dddfff
[Unnamed: 4       3920
Unnamed: 5       3920
Unnamed: 6       3904
Unnamed: 7       3904
Unnamed: 8       3912
Unnamed: 9        -65
Unnamed: 10       -57
Unnamed: 11         4
Unnamed: 12    23.472
Unnamed: 13       128
Name: 58, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     3912
Unnamed: 8     3912
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     128
Name: 59, dtype: object, Unnamed: 4       3927
Unnamed: 5       4100
Unnamed: 6       3901
Unnamed: 7       4076
Unnamed: 8       4045
Unnamed: 9        164
Unnamed: 10       133
Unnamed: 11       116
Unnamed: 12    703.95
Unnamed: 13       172
Name: 60, dtype: object, Unnamed: 4        4053
Unnamed: 5        4072
Unnamed: 6        4030
Unnamed: 7        4030
Unnamed: 8        4053
Unnamed: 9         -15
Unnamed: 10          8
Unnamed: 11         30
Unnamed: 12    182.421
Unnamed: 13        166
Name: 61, dtype: object, Unnamed: 4        4072
Unnamed: 5        4147
Unnamed: 6        4072
Unnamed: 7        4117
Unnamed: 8        4115
Unnamed: 9          64
Unnamed: 10         62
Unnamed: 11         70
Unnamed: 12    432.144
Unnamed: 13        146
Name: 62, dtype: object, Unnamed: 4        4181
Unnamed: 5        4244
Unnamed: 6        4167
Unnamed: 7        4212
Unnamed: 8        4209
Unnamed: 9          97
Unnamed: 10         94
Unnamed: 11        124
Unnamed: 12    783.057
Unnamed: 13        140
Name: 63, dtype: object, Unnamed: 4       4163
Unnamed: 5       4226
Unnamed: 6       4158
Unnamed: 7       4226
Unnamed: 8       4171
Unnamed: 9         17
Unnamed: 10       -38
Unnamed: 11        14
Unnamed: 12    87.609
Unnamed: 13       134
Name: 64, dtype: object, Unnamed: 4        4149
Unnamed: 5        4189
Unnamed: 6        4149
Unnamed: 7        4160
Unnamed: 8        4169
Unnamed: 9         -11
Unnamed: 10         -2
Unnamed: 11         20
Unnamed: 12    125.076
Unnamed: 13        126
Name: 65, dtype: object, Unnamed: 4        4183
Unnamed: 5        4320
Unnamed: 6        4171
Unnamed: 7        4320
Unnamed: 8        4218
Unnamed: 9         151
Unnamed: 10         49
Unnamed: 11         60
Unnamed: 12    379.707
Unnamed: 13        162
Name: 66, dtype: object, Unnamed: 4        4292
Unnamed: 5        4292
Unnamed: 6        4132
Unnamed: 7        4162
Unnamed: 8        4182
Unnamed: 9         -56
Unnamed: 10        -36
Unnamed: 11         32
Unnamed: 12    200.778
Unnamed: 13        144
Name: 67, dtype: object, Unnamed: 4        4220
Unnamed: 5        4272
Unnamed: 6        4191
Unnamed: 7        4216
Unnamed: 8        4224
Unnamed: 9          34
Unnamed: 10         42
Unnamed: 11         38
Unnamed: 12    240.786
Unnamed: 13        150
Name: 68, dtype: object, Unnamed: 4       4222
Unnamed: 5       4240
Unnamed: 6       4211
Unnamed: 7       4211
Unnamed: 8       4226
Unnamed: 9        -13
Unnamed: 10         2
Unnamed: 11        26
Unnamed: 12    164.82
Unnamed: 13       140
Name: 69, dtype: object, Unnamed: 4       4222
Unnamed: 5       4222
Unnamed: 6       4179
Unnamed: 7       4191
Unnamed: 8       4206
Unnamed: 9        -35
Unnamed: 10       -20
Unnamed: 11        12
Unnamed: 12    75.708
Unnamed: 13       140
Name: 70, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4206
Unnamed: 8     4206
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     140
Name: 71, dtype: object, Unnamed: 4       4203
Unnamed: 5       4205
Unnamed: 6       4199
Unnamed: 7       4199
Unnamed: 8       4202
Unnamed: 9         -7
Unnamed: 10        -4
Unnamed: 11         8
Unnamed: 12    50.427
Unnamed: 13       140
Name: 72, dtype: object, Unnamed: 4       4201
Unnamed: 5       4202
Unnamed: 6       4201
Unnamed: 7       4202
Unnamed: 8       4201
Unnamed: 9          0
Unnamed: 10        -1
Unnamed: 11         4
Unnamed: 12    25.209
Unnamed: 13       142
Name: 73, dtype: object, Unnamed: 4        4211
Unnamed: 5        4219
Unnamed: 6        4190
Unnamed: 7        4190
Unnamed: 8        4202
Unnamed: 9         -11
Unnamed: 10          1
Unnamed: 11         16
Unnamed: 12    100.851
Unnamed: 13        146
Name: 74, dtype: object, Unnamed: 4        4223
Unnamed: 5        4405
Unnamed: 6        4222
Unnamed: 7        4396
Unnamed: 8        4340
Unnamed: 9         194
Unnamed: 10        138
Unnamed: 11         78
Unnamed: 12    507.831
Unnamed: 13        170
Name: 75, dtype: object, Unnamed: 4        4399
Unnamed: 5        4412
Unnamed: 6        4399
Unnamed: 7        4412
Unnamed: 8        4407
Unnamed: 9          72
Unnamed: 10         67
Unnamed: 11         16
Unnamed: 12    105.783
Unnamed: 13        172
Name: 76, dtype: object, Unnamed: 4        4494
Unnamed: 5        4585
Unnamed: 6        4476
Unnamed: 7        4520
Unnamed: 8        4519
Unnamed: 9         113
Unnamed: 10        112
Unnamed: 11         30
Unnamed: 12    203.355
Unnamed: 13        176
Name: 77, dtype: object, Unnamed: 4        4549
Unnamed: 5        4601
Unnamed: 6        4535
Unnamed: 7        4600
Unnamed: 8        4563
Unnamed: 9          81
Unnamed: 10         44
Unnamed: 11         28
Unnamed: 12    191.685
Unnamed: 13        180
Name: 78, dtype: object, Unnamed: 4        4628
Unnamed: 5        4628
Unnamed: 6        4497
Unnamed: 7        4574
Unnamed: 8        4570
Unnamed: 9          11
Unnamed: 10          7
Unnamed: 11         48
Unnamed: 12    329.067
Unnamed: 13        178
Name: 79, dtype: object]
22
length
[3920, 3920, 3904, 3904, 3912, 0, 0, 4, 23.472, 128]
22
Unnamed: 4        4072
Unnamed: 5        4147
Unnamed: 6        4072
Unnamed: 7        4117
Unnamed: 8        4115
Unnamed: 9          64
Unnamed: 10         62
Unnamed: 11         70
Unnamed: 12    432.144
Unnamed: 13        146
Name: 62, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, -65.0, -57.0, 0.0, 0.0, 0.0, nan, nan, nan, 8.0, 0.0, 0.0, 0.0, -4.0, -23.472, 0.0, 7.0, 180.0, -3.0, 172.0, 133.0, 164.0, 133.0, 112.0, 680.4780000000001, 44.0, 133.0, 152.0, 126.0, 126.0, 141.0, -15.0, 8.0, 26.0, 158.94899999999998, 38.0, 45]
done
Unnamed: 4        4181
Unnamed: 5        4244
Unnamed: 6        4167
Unnamed: 7        4212
Unnamed: 8        4209
Unnamed: 9          97
Unnamed: 10         94
Unnamed: 11        124
Unnamed: 12    783.057
Unnamed: 13        140
Name: 63, dtype: object
[nan, nan, nan, 8.0, 0.0, 0.0, 0.0, -4.0, -23.472, 0.0, 7.0, 180.0, -3.0, 172.0, 133.0, 164.0, 133.0, 112.0, 680.4780000000001, 44.0, 133.0, 152.0, 126.0, 126.0, 141.0, -15.0, 8.0, 26.0, 158.94899999999998, 38.0, 152.0, 227.0, 168.0, 213.0, 203.0, 64.0, 62.0, 66.0, 408.672, 18.0, 31]
done
Unnamed: 4       4163
Unnamed: 5       4226
Unnamed: 6       4158
Unnamed: 7       4226
Unnamed: 8       4171
Unnamed: 9         17
Unnamed: 10       -38
Unnamed: 11        14
Unnamed: 12    87.609
Unnamed: 13       134
Name: 64, dtype: object
[7.0, 180.0, -3.0, 172.0, 133.0, 164.0, 133.0, 112.0, 680.4780000000001, 44.0, 133.0, 152.0, 126.0, 126.0, 141.0, -15.0, 8.0, 26.0, 158.94899999999998, 38.0, 152.0, 227.0, 168.0, 213.0, 203.0, 64.0, 62.0, 66.0, 408.672, 18.0, 261.0, 324.0, 263.0, 308.0, 297.0, 97.0, 94.0, 120.0, 759.585, 12.0, 63]
done
Unnamed: 4        4149
Unnamed: 5        4189
Unnamed: 6        4149
Unnamed: 7        4160
Unnamed: 8        4169
Unnamed: 9         -11
Unnamed: 10         -2
Unnamed: 11         20
Unnamed: 12    125.076
Unnamed: 13        126
Name: 65, dtype: object
[133.0, 152.0, 126.0, 126.0, 141.0, -15.0, 8.0, 26.0, 158.94899999999998, 38.0, 152.0, 227.0, 168.0, 213.0, 203.0, 64.0, 62.0, 66.0, 408.672, 18.0, 261.0, 324.0, 263.0, 308.0, 297.0, 97.0, 94.0, 120.0, 759.585, 12.0, 243.0, 306.0, 254.0, 322.0, 259.0, 17.0, -38.0, 10.0, 64.137, 6.0, 11]
done
Unnamed: 4        4183
Unnamed: 5        4320
Unnamed: 6        4171
Unnamed: 7        4320
Unnamed: 8        4218
Unnamed: 9         151
Unnamed: 10         49
Unnamed: 11         60
Unnamed: 12    379.707
Unnamed: 13        162
Name: 66, dtype: object
[152.0, 227.0, 168.0, 213.0, 203.0, 64.0, 62.0, 66.0, 408.672, 18.0, 261.0, 324.0, 263.0, 308.0, 297.0, 97.0, 94.0, 120.0, 759.585, 12.0, 243.0, 306.0, 254.0, 322.0, 259.0, 17.0, -38.0, 10.0, 64.137, 6.0, 229.0, 269.0, 245.0, 256.0, 257.0, -11.0, -2.0, 16.0, 101.60399999999998, -2.0, 137]
done
Unnamed: 4        4292
Unnamed: 5        4292
Unnamed: 6        4132
Unnamed: 7        4162
Unnamed: 8        4182
Unnamed: 9         -56
Unnamed: 10        -36
Unnamed: 11         32
Unnamed: 12    200.778
Unnamed: 13        144
Name: 67, dtype: object
[261.0, 324.0, 263.0, 308.0, 297.0, 97.0, 94.0, 120.0, 759.585, 12.0, 243.0, 306.0, 254.0, 322.0, 259.0, 17.0, -38.0, 10.0, 64.137, 6.0, 229.0, 269.0, 245.0, 256.0, 257.0, -11.0, -2.0, 16.0, 101.60399999999998, -2.0, 263.0, 400.0, 267.0, 416.0, 306.0, 151.0, 49.0, 56.0, 356.235, 34.0, -130]
done
Unnamed: 4        4220
Unnamed: 5        4272
Unnamed: 6        4191
Unnamed: 7        4216
Unnamed: 8        4224
Unnamed: 9          34
Unnamed: 10         42
Unnamed: 11         38
Unnamed: 12    240.786
Unnamed: 13        150
Name: 68, dtype: object
[243.0, 306.0, 254.0, 322.0, 259.0, 17.0, -38.0, 10.0, 64.137, 6.0, 229.0, 269.0, 245.0, 256.0, 257.0, -11.0, -2.0, 16.0, 101.60399999999998, -2.0, 263.0, 400.0, 267.0, 416.0, 306.0, 151.0, 49.0, 56.0, 356.235, 34.0, 372.0, 372.0, 228.0, 258.0, 270.0, -56.0, -36.0, 28.0, 177.30599999999998, 16.0, -4]
done
Unnamed: 4       4222
Unnamed: 5       4240
Unnamed: 6       4211
Unnamed: 7       4211
Unnamed: 8       4226
Unnamed: 9        -13
Unnamed: 10         2
Unnamed: 11        26
Unnamed: 12    164.82
Unnamed: 13       140
Name: 69, dtype: object
[229.0, 269.0, 245.0, 256.0, 257.0, -11.0, -2.0, 16.0, 101.60399999999998, -2.0, 263.0, 400.0, 267.0, 416.0, 306.0, 151.0, 49.0, 56.0, 356.235, 34.0, 372.0, 372.0, 228.0, 258.0, 270.0, -56.0, -36.0, 28.0, 177.30599999999998, 16.0, 300.0, 352.0, 287.0, 312.0, 312.0, 34.0, 42.0, 34.0, 217.314, 22.0, -11]
done
Unnamed: 4       4222
Unnamed: 5       4222
Unnamed: 6       4179
Unnamed: 7       4191
Unnamed: 8       4206
Unnamed: 9        -35
Unnamed: 10       -20
Unnamed: 11        12
Unnamed: 12    75.708
Unnamed: 13       140
Name: 70, dtype: object
[263.0, 400.0, 267.0, 416.0, 306.0, 151.0, 49.0, 56.0, 356.235, 34.0, 372.0, 372.0, 228.0, 258.0, 270.0, -56.0, -36.0, 28.0, 177.30599999999998, 16.0, 300.0, 352.0, 287.0, 312.0, 312.0, 34.0, 42.0, 34.0, 217.314, 22.0, 302.0, 320.0, 307.0, 307.0, 314.0, -13.0, 2.0, 22.0, 141.34799999999998, 12.0, -31]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4206
Unnamed: 8     4206
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     140
Name: 71, dtype: object
[372.0, 372.0, 228.0, 258.0, 270.0, -56.0, -36.0, 28.0, 177.30599999999998, 16.0, 300.0, 352.0, 287.0, 312.0, 312.0, 34.0, 42.0, 34.0, 217.314, 22.0, 302.0, 320.0, 307.0, 307.0, 314.0, -13.0, 2.0, 22.0, 141.34799999999998, 12.0, 302.0, 302.0, 275.0, 287.0, 294.0, -35.0, -20.0, 8.0, 52.236, 12.0, nan]
done
Unnamed: 4       4203
Unnamed: 5       4205
Unnamed: 6       4199
Unnamed: 7       4199
Unnamed: 8       4202
Unnamed: 9         -7
Unnamed: 10        -4
Unnamed: 11         8
Unnamed: 12    50.427
Unnamed: 13       140
Name: 72, dtype: object
[300.0, 352.0, 287.0, 312.0, 312.0, 34.0, 42.0, 34.0, 217.314, 22.0, 302.0, 320.0, 307.0, 307.0, 314.0, -13.0, 2.0, 22.0, 141.34799999999998, 12.0, 302.0, 302.0, 275.0, 287.0, 294.0, -35.0, -20.0, 8.0, 52.236, 12.0, nan, nan, nan, 302.0, 294.0, 0.0, 0.0, -4.0, -23.472, 12.0, -4]
done
Unnamed: 4       4201
Unnamed: 5       4202
Unnamed: 6       4201
Unnamed: 7       4202
Unnamed: 8       4201
Unnamed: 9          0
Unnamed: 10        -1
Unnamed: 11         4
Unnamed: 12    25.209
Unnamed: 13       142
Name: 73, dtype: object
[302.0, 320.0, 307.0, 307.0, 314.0, -13.0, 2.0, 22.0, 141.34799999999998, 12.0, 302.0, 302.0, 275.0, 287.0, 294.0, -35.0, -20.0, 8.0, 52.236, 12.0, nan, nan, nan, 302.0, 294.0, 0.0, 0.0, -4.0, -23.472, 12.0, 283.0, 285.0, 295.0, 295.0, 290.0, -7.0, -4.0, 4.0, 26.955, 12.0, 1]
done
Unnamed: 4        4211
Unnamed: 5        4219
Unnamed: 6        4190
Unnamed: 7        4190
Unnamed: 8        4202
Unnamed: 9         -11
Unnamed: 10          1
Unnamed: 11         16
Unnamed: 12    100.851
Unnamed: 13        146
Name: 74, dtype: object
[302.0, 302.0, 275.0, 287.0, 294.0, -35.0, -20.0, 8.0, 52.236, 12.0, nan, nan, nan, 302.0, 294.0, 0.0, 0.0, -4.0, -23.472, 12.0, 283.0, 285.0, 295.0, 295.0, 290.0, -7.0, -4.0, 4.0, 26.955, 12.0, 281.0, 282.0, 297.0, 298.0, 289.0, 0.0, -1.0, 0.0, 1.7369999999999983, 14.0, -21]
done
Unnamed: 4        4223
Unnamed: 5        4405
Unnamed: 6        4222
Unnamed: 7        4396
Unnamed: 8        4340
Unnamed: 9         194
Unnamed: 10        138
Unnamed: 11         78
Unnamed: 12    507.831
Unnamed: 13        170
Name: 75, dtype: object
[nan, nan, nan, 302.0, 294.0, 0.0, 0.0, -4.0, -23.472, 12.0, 283.0, 285.0, 295.0, 295.0, 290.0, -7.0, -4.0, 4.0, 26.955, 12.0, 281.0, 282.0, 297.0, 298.0, 289.0, 0.0, -1.0, 0.0, 1.7369999999999983, 14.0, 291.0, 299.0, 286.0, 286.0, 290.0, -11.0, 1.0, 12.0, 77.37899999999999, 18.0, 173]
done
Unnamed: 4        4399
Unnamed: 5        4412
Unnamed: 6        4399
Unnamed: 7        4412
Unnamed: 8        4407
Unnamed: 9          72
Unnamed: 10         67
Unnamed: 11         16
Unnamed: 12    105.783
Unnamed: 13        172
Name: 76, dtype: object
[283.0, 285.0, 295.0, 295.0, 290.0, -7.0, -4.0, 4.0, 26.955, 12.0, 281.0, 282.0, 297.0, 298.0, 289.0, 0.0, -1.0, 0.0, 1.7369999999999983, 14.0, 291.0, 299.0, 286.0, 286.0, 290.0, -11.0, 1.0, 12.0, 77.37899999999999, 18.0, 303.0, 485.0, 318.0, 492.0, 428.0, 194.0, 138.0, 74.0, 484.35900000000004, 42.0, 13]
done
Unnamed: 4        4494
Unnamed: 5        4585
Unnamed: 6        4476
Unnamed: 7        4520
Unnamed: 8        4519
Unnamed: 9         113
Unnamed: 10        112
Unnamed: 11         30
Unnamed: 12    203.355
Unnamed: 13        176
Name: 77, dtype: object
[281.0, 282.0, 297.0, 298.0, 289.0, 0.0, -1.0, 0.0, 1.7369999999999983, 14.0, 291.0, 299.0, 286.0, 286.0, 290.0, -11.0, 1.0, 12.0, 77.37899999999999, 18.0, 303.0, 485.0, 318.0, 492.0, 428.0, 194.0, 138.0, 74.0, 484.35900000000004, 42.0, 479.0, 492.0, 495.0, 508.0, 495.0, 72.0, 67.0, 12.0, 82.311, 44.0, 26]
done
Unnamed: 4        4549
Unnamed: 5        4601
Unnamed: 6        4535
Unnamed: 7        4600
Unnamed: 8        4563
Unnamed: 9          81
Unnamed: 10         44
Unnamed: 11         28
Unnamed: 12    191.685
Unnamed: 13        180
Name: 78, dtype: object
[291.0, 299.0, 286.0, 286.0, 290.0, -11.0, 1.0, 12.0, 77.37899999999999, 18.0, 303.0, 485.0, 318.0, 492.0, 428.0, 194.0, 138.0, 74.0, 484.35900000000004, 42.0, 479.0, 492.0, 495.0, 508.0, 495.0, 72.0, 67.0, 12.0, 82.311, 44.0, 574.0, 665.0, 572.0, 616.0, 607.0, 113.0, 112.0, 26.0, 179.88299999999998, 48.0, 51]
done
Unnamed: 4        4628
Unnamed: 5        4628
Unnamed: 6        4497
Unnamed: 7        4574
Unnamed: 8        4570
Unnamed: 9          11
Unnamed: 10          7
Unnamed: 11         48
Unnamed: 12    329.067
Unnamed: 13        178
Name: 79, dtype: object
[303.0, 485.0, 318.0, 492.0, 428.0, 194.0, 138.0, 74.0, 484.35900000000004, 42.0, 479.0, 492.0, 495.0, 508.0, 495.0, 72.0, 67.0, 12.0, 82.311, 44.0, 574.0, 665.0, 572.0, 616.0, 607.0, 113.0, 112.0, 26.0, 179.88299999999998, 48.0, 629.0, 681.0, 631.0, 696.0, 651.0, 81.0, 44.0, 24.0, 168.213, 52.0, -54]
done
month is 9

          所内合约行情报表                                         Unnamed: 1  \
0       Daily Data                                                NaN
1               合约                                                 日期
2         Contract                                               Date
3           ag1909                                           20190902
4              NaN                                           20190903
...            ...                                                ...
18407          NaN                                                NaN
18408          注：   1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...
18409          NaN  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...
18410          NaN            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算
18411          NaN                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算

      Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0            NaN         NaN        NaN        NaN        NaN        NaN
1            前收盘         前结算        开盘价        最高价        最低价        收盘价
2      pre close  Pre settle       Open       High        Low      Close
3           4457        4530       4533       4533       4501       4502
4           4502        4511       4512       4560       4509       4560
...          ...         ...        ...        ...        ...        ...
18407        NaN         NaN        NaN        NaN        NaN        NaN
18408        NaN         NaN        NaN        NaN        NaN        NaN
18409        NaN         NaN        NaN        NaN        NaN        NaN
18410        NaN         NaN        NaN        NaN        NaN        NaN
18411        NaN         NaN        NaN        NaN        NaN        NaN

      Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN        NaN         NaN         NaN         NaN         NaN
1            结算价        涨跌1         涨跌2         成交量        成交金额         持仓量
2         Settle        ch1         ch2      Volume      Amount          OI
3           4511        -28         -19         126     852.699         944
4           4527         49          16          44     298.818         944
...          ...        ...         ...         ...         ...         ...
18407        NaN        NaN         NaN         NaN         NaN         NaN
18408        NaN        NaN         NaN         NaN         NaN         NaN
18409        NaN        NaN         NaN         NaN         NaN         NaN
18410        NaN        NaN         NaN         NaN         NaN         NaN
18411        NaN        NaN         NaN         NaN         NaN         NaN

[18412 rows x 14 columns]
dddfff
[Unnamed: 4       4552
Unnamed: 5       4578
Unnamed: 6       4534
Unnamed: 7       4553
Unnamed: 8       4561
Unnamed: 9        -17
Unnamed: 10        -9
Unnamed: 11        72
Unnamed: 12    492.69
Unnamed: 13       170
Name: 33, dtype: object, Unnamed: 4        4537
Unnamed: 5        4611
Unnamed: 6        4535
Unnamed: 7        4602
Unnamed: 8        4591
Unnamed: 9          41
Unnamed: 10         30
Unnamed: 11        442
Unnamed: 12    3043.95
Unnamed: 13        268
Name: 34, dtype: object, Unnamed: 4        4611
Unnamed: 5        4820
Unnamed: 6        4611
Unnamed: 7        4789
Unnamed: 8        4689
Unnamed: 9         198
Unnamed: 10         98
Unnamed: 11        236
Unnamed: 12    1660.11
Unnamed: 13        220
Name: 35, dtype: object, Unnamed: 4        4839
Unnamed: 5        4839
Unnamed: 6        4778
Unnamed: 7        4792
Unnamed: 8        4806
Unnamed: 9         103
Unnamed: 10        117
Unnamed: 11         64
Unnamed: 12    461.391
Unnamed: 13        216
Name: 36, dtype: object, Unnamed: 4        4772
Unnamed: 5        4772
Unnamed: 6        4565
Unnamed: 7        4565
Unnamed: 8        4657
Unnamed: 9        -241
Unnamed: 10       -149
Unnamed: 11        122
Unnamed: 12    852.243
Unnamed: 13        238
Name: 37, dtype: object, Unnamed: 4        4565
Unnamed: 5        4643
Unnamed: 6        4418
Unnamed: 7        4452
Unnamed: 8        4578
Unnamed: 9        -205
Unnamed: 10        -79
Unnamed: 11        422
Unnamed: 12    2897.98
Unnamed: 13        386
Name: 38, dtype: object, Unnamed: 4        4488
Unnamed: 5        4488
Unnamed: 6        4382
Unnamed: 7        4404
Unnamed: 8        4431
Unnamed: 9        -174
Unnamed: 10       -147
Unnamed: 11        170
Unnamed: 12    1130.07
Unnamed: 13        404
Name: 39, dtype: object, Unnamed: 4        4444
Unnamed: 5        4488
Unnamed: 6        4436
Unnamed: 7        4476
Unnamed: 8        4469
Unnamed: 9          45
Unnamed: 10         38
Unnamed: 11         90
Unnamed: 12    603.414
Unnamed: 13        394
Name: 40, dtype: object, Unnamed: 4        4458
Unnamed: 5        4459
Unnamed: 6        4423
Unnamed: 7        4448
Unnamed: 8        4441
Unnamed: 9         -21
Unnamed: 10        -28
Unnamed: 11         46
Unnamed: 12    306.447
Unnamed: 13        376
Name: 41, dtype: object, Unnamed: 4        4402
Unnamed: 5        4405
Unnamed: 6        4385
Unnamed: 7        4395
Unnamed: 8        4392
Unnamed: 9         -46
Unnamed: 10        -49
Unnamed: 11         32
Unnamed: 12    210.849
Unnamed: 13        372
Name: 42, dtype: object, Unnamed: 4      4379
Unnamed: 5      4412
Unnamed: 6      4373
Unnamed: 7      4381
Unnamed: 8      4391
Unnamed: 9       -11
Unnamed: 10       -1
Unnamed: 11      136
Unnamed: 12    895.8
Unnamed: 13      362
Name: 43, dtype: object, Unnamed: 4        4404
Unnamed: 5        4430
Unnamed: 6        4396
Unnamed: 7        4399
Unnamed: 8        4419
Unnamed: 9           8
Unnamed: 10         28
Unnamed: 11         60
Unnamed: 12    397.785
Unnamed: 13        388
Name: 44, dtype: object, Unnamed: 4        4411
Unnamed: 5        4416
Unnamed: 6        4340
Unnamed: 7        4357
Unnamed: 8        4364
Unnamed: 9         -62
Unnamed: 10        -55
Unnamed: 11         42
Unnamed: 12    274.962
Unnamed: 13        370
Name: 45, dtype: object, Unnamed: 4        4402
Unnamed: 5        4412
Unnamed: 6        4266
Unnamed: 7        4403
Unnamed: 8        4392
Unnamed: 9          39
Unnamed: 10         28
Unnamed: 11         84
Unnamed: 12    553.512
Unnamed: 13        382
Name: 46, dtype: object, Unnamed: 4        4394
Unnamed: 5        4527
Unnamed: 6        4394
Unnamed: 7        4510
Unnamed: 8        4486
Unnamed: 9         118
Unnamed: 10         94
Unnamed: 11        116
Unnamed: 12    780.624
Unnamed: 13        374
Name: 47, dtype: object, Unnamed: 4        4577
Unnamed: 5        4596
Unnamed: 6        4565
Unnamed: 7        4570
Unnamed: 8        4572
Unnamed: 9          84
Unnamed: 10         86
Unnamed: 11        238
Unnamed: 12    1632.53
Unnamed: 13        372
Name: 48, dtype: object, Unnamed: 4        4564
Unnamed: 5        4587
Unnamed: 6        4516
Unnamed: 7        4555
Unnamed: 8        4563
Unnamed: 9         -17
Unnamed: 10         -9
Unnamed: 11         50
Unnamed: 12    342.282
Unnamed: 13        356
Name: 49, dtype: object, Unnamed: 4       4438
Unnamed: 5       4443
Unnamed: 6       4437
Unnamed: 7       4438
Unnamed: 8       4439
Unnamed: 9       -125
Unnamed: 10      -124
Unnamed: 11        12
Unnamed: 12    79.917
Unnamed: 13       350
Name: 50, dtype: object, Unnamed: 4        4417
Unnamed: 5        4439
Unnamed: 6        4325
Unnamed: 7        4325
Unnamed: 8        4404
Unnamed: 9        -114
Unnamed: 10        -35
Unnamed: 11        214
Unnamed: 12    1413.86
Unnamed: 13        350
Name: 51, dtype: object, Unnamed: 4        4300
Unnamed: 5        4300
Unnamed: 6        4237
Unnamed: 7        4259
Unnamed: 8        4267
Unnamed: 9        -145
Unnamed: 10       -137
Unnamed: 11        138
Unnamed: 12    883.395
Unnamed: 13        338
Name: 52, dtype: object]
20
length
[4552, 4578, 4534, 4553, 4561, 0, 0, 72, 492.69, 170]
20
Unnamed: 4        4772
Unnamed: 5        4772
Unnamed: 6        4565
Unnamed: 7        4565
Unnamed: 8        4657
Unnamed: 9        -241
Unnamed: 10       -149
Unnamed: 11        122
Unnamed: 12    852.243
Unnamed: 13        238
Name: 37, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, -17.0, -9.0, 0.0, 0.0, 0.0, -15.0, 33.0, 1.0, 49.0, 30.0, 41.0, 30.0, 370.0, 2551.263, 98.0, 59.0, 242.0, 77.0, 236.0, 128.0, 198.0, 98.0, 164.0, 1167.417, 50.0, 287.0, 261.0, 244.0, 239.0, 245.0, 103.0, 117.0, -8.0, -31.298999999999978, 46.0, -207]
done
Unnamed: 4        4565
Unnamed: 5        4643
Unnamed: 6        4418
Unnamed: 7        4452
Unnamed: 8        4578
Unnamed: 9        -205
Unnamed: 10        -79
Unnamed: 11        422
Unnamed: 12    2897.98
Unnamed: 13        386
Name: 38, dtype: object
[-15.0, 33.0, 1.0, 49.0, 30.0, 41.0, 30.0, 370.0, 2551.263, 98.0, 59.0, 242.0, 77.0, 236.0, 128.0, 198.0, 98.0, 164.0, 1167.417, 50.0, 287.0, 261.0, 244.0, 239.0, 245.0, 103.0, 117.0, -8.0, -31.298999999999978, 46.0, 220.0, 194.0, 31.0, 12.0, 96.0, -241.0, -149.0, 50.0, 359.55300000000005, 68.0, -113]
done
Unnamed: 4        4488
Unnamed: 5        4488
Unnamed: 6        4382
Unnamed: 7        4404
Unnamed: 8        4431
Unnamed: 9        -174
Unnamed: 10       -147
Unnamed: 11        170
Unnamed: 12    1130.07
Unnamed: 13        404
Name: 39, dtype: object
[59.0, 242.0, 77.0, 236.0, 128.0, 198.0, 98.0, 164.0, 1167.417, 50.0, 287.0, 261.0, 244.0, 239.0, 245.0, 103.0, 117.0, -8.0, -31.298999999999978, 46.0, 220.0, 194.0, 31.0, 12.0, 96.0, -241.0, -149.0, 50.0, 359.55300000000005, 68.0, 13.0, 65.0, -116.0, -101.0, 17.0, -205.0, -79.0, 350.0, 2405.2889999999998, 216.0, -84]
done
Unnamed: 4        4444
Unnamed: 5        4488
Unnamed: 6        4436
Unnamed: 7        4476
Unnamed: 8        4469
Unnamed: 9          45
Unnamed: 10         38
Unnamed: 11         90
Unnamed: 12    603.414
Unnamed: 13        394
Name: 40, dtype: object
[287.0, 261.0, 244.0, 239.0, 245.0, 103.0, 117.0, -8.0, -31.298999999999978, 46.0, 220.0, 194.0, 31.0, 12.0, 96.0, -241.0, -149.0, 50.0, 359.55300000000005, 68.0, 13.0, 65.0, -116.0, -101.0, 17.0, -205.0, -79.0, 350.0, 2405.2889999999998, 216.0, -64.0, -90.0, -152.0, -149.0, -130.0, -174.0, -147.0, 98.0, 637.377, 234.0, 32]
done
Unnamed: 4        4458
Unnamed: 5        4459
Unnamed: 6        4423
Unnamed: 7        4448
Unnamed: 8        4441
Unnamed: 9         -21
Unnamed: 10        -28
Unnamed: 11         46
Unnamed: 12    306.447
Unnamed: 13        376
Name: 41, dtype: object
[220.0, 194.0, 31.0, 12.0, 96.0, -241.0, -149.0, 50.0, 359.55300000000005, 68.0, 13.0, 65.0, -116.0, -101.0, 17.0, -205.0, -79.0, 350.0, 2405.2889999999998, 216.0, -64.0, -90.0, -152.0, -149.0, -130.0, -174.0, -147.0, 98.0, 637.377, 234.0, -108.0, -90.0, -98.0, -77.0, -92.0, 45.0, 38.0, 18.0, 110.72399999999999, 224.0, -10]
done
Unnamed: 4        4402
Unnamed: 5        4405
Unnamed: 6        4385
Unnamed: 7        4395
Unnamed: 8        4392
Unnamed: 9         -46
Unnamed: 10        -49
Unnamed: 11         32
Unnamed: 12    210.849
Unnamed: 13        372
Name: 42, dtype: object
[13.0, 65.0, -116.0, -101.0, 17.0, -205.0, -79.0, 350.0, 2405.2889999999998, 216.0, -64.0, -90.0, -152.0, -149.0, -130.0, -174.0, -147.0, 98.0, 637.377, 234.0, -108.0, -90.0, -98.0, -77.0, -92.0, 45.0, 38.0, 18.0, 110.72399999999999, 224.0, -94.0, -119.0, -111.0, -105.0, -120.0, -21.0, -28.0, -26.0, -186.243, 206.0, -7]
done
Unnamed: 4      4379
Unnamed: 5      4412
Unnamed: 6      4373
Unnamed: 7      4381
Unnamed: 8      4391
Unnamed: 9       -11
Unnamed: 10       -1
Unnamed: 11      136
Unnamed: 12    895.8
Unnamed: 13      362
Name: 43, dtype: object
[-64.0, -90.0, -152.0, -149.0, -130.0, -174.0, -147.0, 98.0, 637.377, 234.0, -108.0, -90.0, -98.0, -77.0, -92.0, 45.0, 38.0, 18.0, 110.72399999999999, 224.0, -94.0, -119.0, -111.0, -105.0, -120.0, -21.0, -28.0, -26.0, -186.243, 206.0, -150.0, -173.0, -149.0, -158.0, -169.0, -46.0, -49.0, -40.0, -281.841, 202.0, 2]
done
Unnamed: 4        4404
Unnamed: 5        4430
Unnamed: 6        4396
Unnamed: 7        4399
Unnamed: 8        4419
Unnamed: 9           8
Unnamed: 10         28
Unnamed: 11         60
Unnamed: 12    397.785
Unnamed: 13        388
Name: 44, dtype: object
[-108.0, -90.0, -98.0, -77.0, -92.0, 45.0, 38.0, 18.0, 110.72399999999999, 224.0, -94.0, -119.0, -111.0, -105.0, -120.0, -21.0, -28.0, -26.0, -186.243, 206.0, -150.0, -173.0, -149.0, -158.0, -169.0, -46.0, -49.0, -40.0, -281.841, 202.0, -173.0, -166.0, -161.0, -172.0, -170.0, -11.0, -1.0, 64.0, 403.10999999999996, 192.0, -5]
done
Unnamed: 4        4411
Unnamed: 5        4416
Unnamed: 6        4340
Unnamed: 7        4357
Unnamed: 8        4364
Unnamed: 9         -62
Unnamed: 10        -55
Unnamed: 11         42
Unnamed: 12    274.962
Unnamed: 13        370
Name: 45, dtype: object
[-94.0, -119.0, -111.0, -105.0, -120.0, -21.0, -28.0, -26.0, -186.243, 206.0, -150.0, -173.0, -149.0, -158.0, -169.0, -46.0, -49.0, -40.0, -281.841, 202.0, -173.0, -166.0, -161.0, -172.0, -170.0, -11.0, -1.0, 64.0, 403.10999999999996, 192.0, -148.0, -148.0, -138.0, -154.0, -142.0, 8.0, 28.0, -12.0, -94.90499999999997, 218.0, -54]
done
Unnamed: 4        4402
Unnamed: 5        4412
Unnamed: 6        4266
Unnamed: 7        4403
Unnamed: 8        4392
Unnamed: 9          39
Unnamed: 10         28
Unnamed: 11         84
Unnamed: 12    553.512
Unnamed: 13        382
Name: 46, dtype: object
[-150.0, -173.0, -149.0, -158.0, -169.0, -46.0, -49.0, -40.0, -281.841, 202.0, -173.0, -166.0, -161.0, -172.0, -170.0, -11.0, -1.0, 64.0, 403.10999999999996, 192.0, -148.0, -148.0, -138.0, -154.0, -142.0, 8.0, 28.0, -12.0, -94.90499999999997, 218.0, -141.0, -162.0, -194.0, -196.0, -197.0, -62.0, -55.0, -30.0, -217.728, 200.0, 1]
done
Unnamed: 4        4394
Unnamed: 5        4527
Unnamed: 6        4394
Unnamed: 7        4510
Unnamed: 8        4486
Unnamed: 9         118
Unnamed: 10         94
Unnamed: 11        116
Unnamed: 12    780.624
Unnamed: 13        374
Name: 47, dtype: object
[-173.0, -166.0, -161.0, -172.0, -170.0, -11.0, -1.0, 64.0, 403.10999999999996, 192.0, -148.0, -148.0, -138.0, -154.0, -142.0, 8.0, 28.0, -12.0, -94.90499999999997, 218.0, -141.0, -162.0, -194.0, -196.0, -197.0, -62.0, -55.0, -30.0, -217.728, 200.0, -150.0, -166.0, -268.0, -150.0, -169.0, 39.0, 28.0, 12.0, 60.821999999999946, 212.0, 116]
done
Unnamed: 4        4577
Unnamed: 5        4596
Unnamed: 6        4565
Unnamed: 7        4570
Unnamed: 8        4572
Unnamed: 9          84
Unnamed: 10         86
Unnamed: 11        238
Unnamed: 12    1632.53
Unnamed: 13        372
Name: 48, dtype: object
[-148.0, -148.0, -138.0, -154.0, -142.0, 8.0, 28.0, -12.0, -94.90499999999997, 218.0, -141.0, -162.0, -194.0, -196.0, -197.0, -62.0, -55.0, -30.0, -217.728, 200.0, -150.0, -166.0, -268.0, -150.0, -169.0, 39.0, 28.0, 12.0, 60.821999999999946, 212.0, -158.0, -51.0, -140.0, -43.0, -75.0, 118.0, 94.0, 44.0, 287.934, 204.0, -7]
done
Unnamed: 4        4564
Unnamed: 5        4587
Unnamed: 6        4516
Unnamed: 7        4555
Unnamed: 8        4563
Unnamed: 9         -17
Unnamed: 10         -9
Unnamed: 11         50
Unnamed: 12    342.282
Unnamed: 13        356
Name: 49, dtype: object
[-141.0, -162.0, -194.0, -196.0, -197.0, -62.0, -55.0, -30.0, -217.728, 200.0, -150.0, -166.0, -268.0, -150.0, -169.0, 39.0, 28.0, 12.0, 60.821999999999946, 212.0, -158.0, -51.0, -140.0, -43.0, -75.0, 118.0, 94.0, 44.0, 287.934, 204.0, 25.0, 18.0, 31.0, 17.0, 11.0, 84.0, 86.0, 166.0, 1139.841, 202.0, -9]
done
Unnamed: 4       4438
Unnamed: 5       4443
Unnamed: 6       4437
Unnamed: 7       4438
Unnamed: 8       4439
Unnamed: 9       -125
Unnamed: 10      -124
Unnamed: 11        12
Unnamed: 12    79.917
Unnamed: 13       350
Name: 50, dtype: object
[-150.0, -166.0, -268.0, -150.0, -169.0, 39.0, 28.0, 12.0, 60.821999999999946, 212.0, -158.0, -51.0, -140.0, -43.0, -75.0, 118.0, 94.0, 44.0, 287.934, 204.0, 25.0, 18.0, 31.0, 17.0, 11.0, 84.0, 86.0, 166.0, 1139.841, 202.0, 12.0, 9.0, -18.0, 2.0, 2.0, -17.0, -9.0, -22.0, -150.40800000000002, 186.0, 0]
done
Unnamed: 4        4417
Unnamed: 5        4439
Unnamed: 6        4325
Unnamed: 7        4325
Unnamed: 8        4404
Unnamed: 9        -114
Unnamed: 10        -35
Unnamed: 11        214
Unnamed: 12    1413.86
Unnamed: 13        350
Name: 51, dtype: object
[-158.0, -51.0, -140.0, -43.0, -75.0, 118.0, 94.0, 44.0, 287.934, 204.0, 25.0, 18.0, 31.0, 17.0, 11.0, 84.0, 86.0, 166.0, 1139.841, 202.0, 12.0, 9.0, -18.0, 2.0, 2.0, -17.0, -9.0, -22.0, -150.40800000000002, 186.0, -114.0, -135.0, -97.0, -115.0, -122.0, -125.0, -124.0, -60.0, -412.773, 180.0, -92]
done
Unnamed: 4        4300
Unnamed: 5        4300
Unnamed: 6        4237
Unnamed: 7        4259
Unnamed: 8        4267
Unnamed: 9        -145
Unnamed: 10       -137
Unnamed: 11        138
Unnamed: 12    883.395
Unnamed: 13        338
Name: 52, dtype: object
[25.0, 18.0, 31.0, 17.0, 11.0, 84.0, 86.0, 166.0, 1139.841, 202.0, 12.0, 9.0, -18.0, 2.0, 2.0, -17.0, -9.0, -22.0, -150.40800000000002, 186.0, -114.0, -135.0, -97.0, -115.0, -122.0, -125.0, -124.0, -60.0, -412.773, 180.0, -135.0, -139.0, -209.0, -228.0, -157.0, -114.0, -35.0, 142.0, 921.165, 180.0, -41]
done
month is 10

                    所内合约行情报表  \
0      日期： 20191001-20191031
1                         合约
2                   Contract
3                     ag1910
4                        NaN
...                      ...
16831                    NaN
16832                    注：
16833                    NaN
16834                    NaN
16835                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                                   Date  pre close
3                                               20191008       4180
4                                               20191009       4260
...                                                  ...        ...
16831                                                NaN        NaN
16832  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
16833  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
16834            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
16835                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

       Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0             NaN        NaN        NaN        NaN        NaN        NaN
1             前结算        开盘价        最高价        最低价        收盘价        结算价
2      Pre settle       Open       High        Low      Close     Settle
3            4222       4260       4260       4260       4260       4260
4            4260       4374       4375       4370       4371       4372
...           ...        ...        ...        ...        ...        ...
16831         NaN        NaN        NaN        NaN        NaN        NaN
16832         NaN        NaN        NaN        NaN        NaN        NaN
16833         NaN        NaN        NaN        NaN        NaN        NaN
16834         NaN        NaN        NaN        NaN        NaN        NaN
16835         NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2            ch1         ch2      Volume      Amount          OI NaN
3             38          38           4       25.56         856 NaN
4            111         112          36     236.094         856 NaN
...          ...         ...         ...         ...         ...  ..
16831        NaN         NaN         NaN         NaN         NaN NaN
16832        NaN         NaN         NaN         NaN         NaN NaN
16833        NaN         NaN         NaN         NaN         NaN NaN
16834        NaN         NaN         NaN         NaN         NaN NaN
16835        NaN         NaN         NaN         NaN         NaN NaN

[16836 rows x 15 columns]
dddfff
[Unnamed: 4        4297
Unnamed: 5        4297
Unnamed: 6        4276
Unnamed: 7        4276
Unnamed: 8        4283
Unnamed: 9           9
Unnamed: 10         16
Unnamed: 11         16
Unnamed: 12    102.801
Unnamed: 13        330
Name: 9, dtype: object, Unnamed: 4        4339
Unnamed: 5        4425
Unnamed: 6        4339
Unnamed: 7        4425
Unnamed: 8        4394
Unnamed: 9         142
Unnamed: 10        111
Unnamed: 11         90
Unnamed: 12    593.265
Unnamed: 13        332
Name: 10, dtype: object, Unnamed: 4        4406
Unnamed: 5        4411
Unnamed: 6        4370
Unnamed: 7        4370
Unnamed: 8        4387
Unnamed: 9         -24
Unnamed: 10         -7
Unnamed: 11         18
Unnamed: 12    118.458
Unnamed: 13        330
Name: 11, dtype: object, Unnamed: 4        4340
Unnamed: 5        4345
Unnamed: 6        4289
Unnamed: 7        4340
Unnamed: 8        4326
Unnamed: 9         -47
Unnamed: 10        -61
Unnamed: 11         38
Unnamed: 12    246.603
Unnamed: 13        318
Name: 12, dtype: object, Unnamed: 4        4314
Unnamed: 5        4315
Unnamed: 6        4247
Unnamed: 7        4280
Unnamed: 8        4292
Unnamed: 9         -46
Unnamed: 10        -34
Unnamed: 11         18
Unnamed: 12    115.887
Unnamed: 13        312
Name: 13, dtype: object, Unnamed: 4       4332
Unnamed: 5       4344
Unnamed: 6       4323
Unnamed: 7       4323
Unnamed: 8       4335
Unnamed: 9         31
Unnamed: 10        43
Unnamed: 11        10
Unnamed: 12    65.031
Unnamed: 13       312
Name: 14, dtype: object, Unnamed: 4        4290
Unnamed: 5        4301
Unnamed: 6        4235
Unnamed: 7        4235
Unnamed: 8        4253
Unnamed: 9        -100
Unnamed: 10        -82
Unnamed: 11         50
Unnamed: 12    318.981
Unnamed: 13        344
Name: 15, dtype: object, Unnamed: 4        4300
Unnamed: 5        4300
Unnamed: 6        4258
Unnamed: 7        4258
Unnamed: 8        4266
Unnamed: 9           5
Unnamed: 10         13
Unnamed: 11         24
Unnamed: 12    153.606
Unnamed: 13        348
Name: 16, dtype: object, Unnamed: 4        4301
Unnamed: 5        4331
Unnamed: 6        4251
Unnamed: 7        4293
Unnamed: 8        4297
Unnamed: 9          27
Unnamed: 10         31
Unnamed: 11         54
Unnamed: 12    348.066
Unnamed: 13        338
Name: 17, dtype: object, Unnamed: 4       4291
Unnamed: 5       4351
Unnamed: 6       4291
Unnamed: 7       4351
Unnamed: 8       4308
Unnamed: 9         54
Unnamed: 10        11
Unnamed: 11        12
Unnamed: 12    77.559
Unnamed: 13       334
Name: 18, dtype: object, Unnamed: 4        4361
Unnamed: 5        4380
Unnamed: 6        4297
Unnamed: 7        4310
Unnamed: 8        4319
Unnamed: 9           2
Unnamed: 10         11
Unnamed: 11         64
Unnamed: 12    414.687
Unnamed: 13        304
Name: 19, dtype: object, Unnamed: 4       4285
Unnamed: 5       4303
Unnamed: 6       4285
Unnamed: 7       4299
Unnamed: 8       4295
Unnamed: 9        -20
Unnamed: 10       -24
Unnamed: 11         8
Unnamed: 12    51.543
Unnamed: 13       300
Name: 20, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4295
Unnamed: 8     4295
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     300
Name: 21, dtype: object, Unnamed: 4       4355
Unnamed: 5       4408
Unnamed: 6       4352
Unnamed: 7       4390
Unnamed: 8       4369
Unnamed: 9         95
Unnamed: 10        74
Unnamed: 11        12
Unnamed: 12    78.651
Unnamed: 13       300
Name: 22, dtype: object, Unnamed: 4       4391
Unnamed: 5       4414
Unnamed: 6       4377
Unnamed: 7       4414
Unnamed: 8       4394
Unnamed: 9         45
Unnamed: 10        25
Unnamed: 11         6
Unnamed: 12    39.546
Unnamed: 13       298
Name: 23, dtype: object, Unnamed: 4        4343
Unnamed: 5        4379
Unnamed: 6        4320
Unnamed: 7        4323
Unnamed: 8        4339
Unnamed: 9         -71
Unnamed: 10        -55
Unnamed: 11         60
Unnamed: 12    390.588
Unnamed: 13        326
Name: 24, dtype: object, Unnamed: 4        4314
Unnamed: 5        4374
Unnamed: 6        4314
Unnamed: 7        4321
Unnamed: 8        4324
Unnamed: 9         -18
Unnamed: 10        -15
Unnamed: 11         98
Unnamed: 12    635.703
Unnamed: 13        324
Name: 25, dtype: object, Unnamed: 4        4290
Unnamed: 5        4377
Unnamed: 6        4239
Unnamed: 7        4330
Unnamed: 8        4302
Unnamed: 9           6
Unnamed: 10        -22
Unnamed: 11        190
Unnamed: 12    1226.23
Unnamed: 13        312
Name: 26, dtype: object]
18
length
[4297, 4297, 4276, 4276, 4283, 0, 0, 16, 102.801, 330]
18
Unnamed: 4        4314
Unnamed: 5        4315
Unnamed: 6        4247
Unnamed: 7        4280
Unnamed: 8        4292
Unnamed: 9         -46
Unnamed: 10        -34
Unnamed: 11         18
Unnamed: 12    115.887
Unnamed: 13        312
Name: 13, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, 9.0, 16.0, 0.0, 0.0, 0.0, 42.0, 128.0, 63.0, 149.0, 111.0, 142.0, 111.0, 74.0, 490.464, 2.0, 109.0, 114.0, 94.0, 94.0, 104.0, -24.0, -7.0, 2.0, 15.656999999999996, 0.0, 43.0, 48.0, 13.0, 64.0, 43.0, -47.0, -61.0, 22.0, 143.80200000000002, -12.0, -34]
done
Unnamed: 4       4332
Unnamed: 5       4344
Unnamed: 6       4323
Unnamed: 7       4323
Unnamed: 8       4335
Unnamed: 9         31
Unnamed: 10        43
Unnamed: 11        10
Unnamed: 12    65.031
Unnamed: 13       312
Name: 14, dtype: object
[42.0, 128.0, 63.0, 149.0, 111.0, 142.0, 111.0, 74.0, 490.464, 2.0, 109.0, 114.0, 94.0, 94.0, 104.0, -24.0, -7.0, 2.0, 15.656999999999996, 0.0, 43.0, 48.0, 13.0, 64.0, 43.0, -47.0, -61.0, 22.0, 143.80200000000002, -12.0, 17.0, 18.0, -29.0, 4.0, 9.0, -46.0, -34.0, 2.0, 13.085999999999999, -18.0, -9]
done
Unnamed: 4        4290
Unnamed: 5        4301
Unnamed: 6        4235
Unnamed: 7        4235
Unnamed: 8        4253
Unnamed: 9        -100
Unnamed: 10        -82
Unnamed: 11         50
Unnamed: 12    318.981
Unnamed: 13        344
Name: 15, dtype: object
[109.0, 114.0, 94.0, 94.0, 104.0, -24.0, -7.0, 2.0, 15.656999999999996, 0.0, 43.0, 48.0, 13.0, 64.0, 43.0, -47.0, -61.0, 22.0, 143.80200000000002, -12.0, 17.0, 18.0, -29.0, 4.0, 9.0, -46.0, -34.0, 2.0, 13.085999999999999, -18.0, 35.0, 47.0, 47.0, 47.0, 52.0, 31.0, 43.0, -6.0, -37.769999999999996, -18.0, -55]
done
Unnamed: 4        4300
Unnamed: 5        4300
Unnamed: 6        4258
Unnamed: 7        4258
Unnamed: 8        4266
Unnamed: 9           5
Unnamed: 10         13
Unnamed: 11         24
Unnamed: 12    153.606
Unnamed: 13        348
Name: 16, dtype: object
[43.0, 48.0, 13.0, 64.0, 43.0, -47.0, -61.0, 22.0, 143.80200000000002, -12.0, 17.0, 18.0, -29.0, 4.0, 9.0, -46.0, -34.0, 2.0, 13.085999999999999, -18.0, 35.0, 47.0, 47.0, 47.0, 52.0, 31.0, 43.0, -6.0, -37.769999999999996, -18.0, -7.0, 4.0, -41.0, -41.0, -30.0, -100.0, -82.0, 34.0, 216.18, 14.0, -42]
done
Unnamed: 4        4301
Unnamed: 5        4331
Unnamed: 6        4251
Unnamed: 7        4293
Unnamed: 8        4297
Unnamed: 9          27
Unnamed: 10         31
Unnamed: 11         54
Unnamed: 12    348.066
Unnamed: 13        338
Name: 17, dtype: object
[17.0, 18.0, -29.0, 4.0, 9.0, -46.0, -34.0, 2.0, 13.085999999999999, -18.0, 35.0, 47.0, 47.0, 47.0, 52.0, 31.0, 43.0, -6.0, -37.769999999999996, -18.0, -7.0, 4.0, -41.0, -41.0, -30.0, -100.0, -82.0, 34.0, 216.18, 14.0, 3.0, 3.0, -18.0, -18.0, -17.0, 5.0, 13.0, 8.0, 50.80499999999999, 18.0, -8]
done
Unnamed: 4       4291
Unnamed: 5       4351
Unnamed: 6       4291
Unnamed: 7       4351
Unnamed: 8       4308
Unnamed: 9         54
Unnamed: 10        11
Unnamed: 11        12
Unnamed: 12    77.559
Unnamed: 13       334
Name: 18, dtype: object
[35.0, 47.0, 47.0, 47.0, 52.0, 31.0, 43.0, -6.0, -37.769999999999996, -18.0, -7.0, 4.0, -41.0, -41.0, -30.0, -100.0, -82.0, 34.0, 216.18, 14.0, 3.0, 3.0, -18.0, -18.0, -17.0, 5.0, 13.0, 8.0, 50.80499999999999, 18.0, 4.0, 34.0, -25.0, 17.0, 14.0, 27.0, 31.0, 38.0, 245.265, 8.0, 60]
done
Unnamed: 4        4361
Unnamed: 5        4380
Unnamed: 6        4297
Unnamed: 7        4310
Unnamed: 8        4319
Unnamed: 9           2
Unnamed: 10         11
Unnamed: 11         64
Unnamed: 12    414.687
Unnamed: 13        304
Name: 19, dtype: object
[-7.0, 4.0, -41.0, -41.0, -30.0, -100.0, -82.0, 34.0, 216.18, 14.0, 3.0, 3.0, -18.0, -18.0, -17.0, 5.0, 13.0, 8.0, 50.80499999999999, 18.0, 4.0, 34.0, -25.0, 17.0, 14.0, 27.0, 31.0, 38.0, 245.265, 8.0, -6.0, 54.0, 15.0, 75.0, 25.0, 54.0, 11.0, -4.0, -25.242000000000004, 4.0, -51]
done
Unnamed: 4       4285
Unnamed: 5       4303
Unnamed: 6       4285
Unnamed: 7       4299
Unnamed: 8       4295
Unnamed: 9        -20
Unnamed: 10       -24
Unnamed: 11         8
Unnamed: 12    51.543
Unnamed: 13       300
Name: 20, dtype: object
[3.0, 3.0, -18.0, -18.0, -17.0, 5.0, 13.0, 8.0, 50.80499999999999, 18.0, 4.0, 34.0, -25.0, 17.0, 14.0, 27.0, 31.0, 38.0, 245.265, 8.0, -6.0, 54.0, 15.0, 75.0, 25.0, 54.0, 11.0, -4.0, -25.242000000000004, 4.0, 64.0, 83.0, 21.0, 34.0, 36.0, 2.0, 11.0, 48.0, 311.886, -26.0, 14]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4295
Unnamed: 8     4295
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     300
Name: 21, dtype: object
[4.0, 34.0, -25.0, 17.0, 14.0, 27.0, 31.0, 38.0, 245.265, 8.0, -6.0, 54.0, 15.0, 75.0, 25.0, 54.0, 11.0, -4.0, -25.242000000000004, 4.0, 64.0, 83.0, 21.0, 34.0, 36.0, 2.0, 11.0, 48.0, 311.886, -26.0, -12.0, 6.0, 9.0, 23.0, 12.0, -20.0, -24.0, -8.0, -51.258, -30.0, nan]
done
Unnamed: 4       4355
Unnamed: 5       4408
Unnamed: 6       4352
Unnamed: 7       4390
Unnamed: 8       4369
Unnamed: 9         95
Unnamed: 10        74
Unnamed: 11        12
Unnamed: 12    78.651
Unnamed: 13       300
Name: 22, dtype: object
[-6.0, 54.0, 15.0, 75.0, 25.0, 54.0, 11.0, -4.0, -25.242000000000004, 4.0, 64.0, 83.0, 21.0, 34.0, 36.0, 2.0, 11.0, 48.0, 311.886, -26.0, -12.0, 6.0, 9.0, 23.0, 12.0, -20.0, -24.0, -8.0, -51.258, -30.0, nan, nan, nan, 19.0, 12.0, 0.0, 0.0, -16.0, -102.801, -30.0, 35]
done
Unnamed: 4       4391
Unnamed: 5       4414
Unnamed: 6       4377
Unnamed: 7       4414
Unnamed: 8       4394
Unnamed: 9         45
Unnamed: 10        25
Unnamed: 11         6
Unnamed: 12    39.546
Unnamed: 13       298
Name: 23, dtype: object
[64.0, 83.0, 21.0, 34.0, 36.0, 2.0, 11.0, 48.0, 311.886, -26.0, -12.0, 6.0, 9.0, 23.0, 12.0, -20.0, -24.0, -8.0, -51.258, -30.0, nan, nan, nan, 19.0, 12.0, 0.0, 0.0, -16.0, -102.801, -30.0, 58.0, 111.0, 76.0, 114.0, 86.0, 95.0, 74.0, -4.0, -24.150000000000006, -30.0, 23]
done
Unnamed: 4        4343
Unnamed: 5        4379
Unnamed: 6        4320
Unnamed: 7        4323
Unnamed: 8        4339
Unnamed: 9         -71
Unnamed: 10        -55
Unnamed: 11         60
Unnamed: 12    390.588
Unnamed: 13        326
Name: 24, dtype: object
[-12.0, 6.0, 9.0, 23.0, 12.0, -20.0, -24.0, -8.0, -51.258, -30.0, nan, nan, nan, 19.0, 12.0, 0.0, 0.0, -16.0, -102.801, -30.0, 58.0, 111.0, 76.0, 114.0, 86.0, 95.0, 74.0, -4.0, -24.150000000000006, -30.0, 94.0, 117.0, 101.0, 138.0, 111.0, 45.0, 25.0, -10.0, -63.255, -32.0, -20]
done
Unnamed: 4        4314
Unnamed: 5        4374
Unnamed: 6        4314
Unnamed: 7        4321
Unnamed: 8        4324
Unnamed: 9         -18
Unnamed: 10        -15
Unnamed: 11         98
Unnamed: 12    635.703
Unnamed: 13        324
Name: 25, dtype: object
[nan, nan, nan, 19.0, 12.0, 0.0, 0.0, -16.0, -102.801, -30.0, 58.0, 111.0, 76.0, 114.0, 86.0, 95.0, 74.0, -4.0, -24.150000000000006, -30.0, 94.0, 117.0, 101.0, 138.0, 111.0, 45.0, 25.0, -10.0, -63.255, -32.0, 46.0, 82.0, 44.0, 47.0, 56.0, -71.0, -55.0, 44.0, 287.78700000000003, -4.0, 7]
done
Unnamed: 4        4290
Unnamed: 5        4377
Unnamed: 6        4239
Unnamed: 7        4330
Unnamed: 8        4302
Unnamed: 9           6
Unnamed: 10        -22
Unnamed: 11        190
Unnamed: 12    1226.23
Unnamed: 13        312
Name: 26, dtype: object
[58.0, 111.0, 76.0, 114.0, 86.0, 95.0, 74.0, -4.0, -24.150000000000006, -30.0, 94.0, 117.0, 101.0, 138.0, 111.0, 45.0, 25.0, -10.0, -63.255, -32.0, 46.0, 82.0, 44.0, 47.0, 56.0, -71.0, -55.0, 44.0, 287.78700000000003, -4.0, 17.0, 77.0, 38.0, 45.0, 41.0, -18.0, -15.0, 82.0, 532.9019999999999, -6.0, 40]
done
month is 11

                    所内合约行情报表  \
0      日期： 20191101-20191130
1                         合约
2                   Contract
3                     ag1911
4                        NaN
...                      ...
19584                    NaN
19585                    注：
19586                    NaN
19587                    NaN
19588                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                                   Date  pre close
3                                               20191101       4330
4                                               20191104       4377
...                                                  ...        ...
19584                                                NaN        NaN
19585  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
19586  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
19587            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
19588                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

       Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0             NaN        NaN        NaN        NaN        NaN        NaN
1             前结算        开盘价        最高价        最低价        收盘价        结算价
2      Pre settle       Open       High        Low      Close     Settle
3            4302       4345       4396       4308       4377       4370
4            4370       4359       4407       4359       4375       4373
...           ...        ...        ...        ...        ...        ...
19584         NaN        NaN        NaN        NaN        NaN        NaN
19585         NaN        NaN        NaN        NaN        NaN        NaN
19586         NaN        NaN        NaN        NaN        NaN        NaN
19587         NaN        NaN        NaN        NaN        NaN        NaN
19588         NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2            ch1         ch2      Volume      Amount          OI NaN
3             75          68         128     839.136         312 NaN
4              5           3          48     314.898         348 NaN
...          ...         ...         ...         ...         ...  ..
19584        NaN         NaN         NaN         NaN         NaN NaN
19585        NaN         NaN         NaN         NaN         NaN NaN
19586        NaN         NaN         NaN         NaN         NaN NaN
19587        NaN         NaN         NaN         NaN         NaN NaN
19588        NaN         NaN         NaN         NaN         NaN NaN

[19589 rows x 15 columns]
dddfff
[Unnamed: 4        4345
Unnamed: 5        4396
Unnamed: 6        4308
Unnamed: 7        4377
Unnamed: 8        4370
Unnamed: 9          75
Unnamed: 10         68
Unnamed: 11        128
Unnamed: 12    839.136
Unnamed: 13        312
Name: 3, dtype: object, Unnamed: 4        4359
Unnamed: 5        4407
Unnamed: 6        4359
Unnamed: 7        4375
Unnamed: 8        4373
Unnamed: 9           5
Unnamed: 10          3
Unnamed: 11         48
Unnamed: 12    314.898
Unnamed: 13        348
Name: 4, dtype: object, Unnamed: 4        4354
Unnamed: 5        4361
Unnamed: 6        4337
Unnamed: 7        4337
Unnamed: 8        4349
Unnamed: 9         -36
Unnamed: 10        -24
Unnamed: 11         52
Unnamed: 12    339.252
Unnamed: 13        328
Name: 5, dtype: object, Unnamed: 4       4138
Unnamed: 5       4138
Unnamed: 6       4138
Unnamed: 7       4138
Unnamed: 8       4138
Unnamed: 9       -211
Unnamed: 10      -211
Unnamed: 11         4
Unnamed: 12    24.828
Unnamed: 13       332
Name: 6, dtype: object, Unnamed: 4        4191
Unnamed: 5        4280
Unnamed: 6        4191
Unnamed: 7        4260
Unnamed: 8        4236
Unnamed: 9         122
Unnamed: 10         98
Unnamed: 11         28
Unnamed: 12    177.918
Unnamed: 13        336
Name: 7, dtype: object, Unnamed: 4      4260
Unnamed: 5      4260
Unnamed: 6      4260
Unnamed: 7      4260
Unnamed: 8      4260
Unnamed: 9        24
Unnamed: 10       24
Unnamed: 11        4
Unnamed: 12    25.56
Unnamed: 13      332
Name: 8, dtype: object, Unnamed: 4       4069
Unnamed: 5       4069
Unnamed: 6       4069
Unnamed: 7       4069
Unnamed: 8       4069
Unnamed: 9       -191
Unnamed: 10      -191
Unnamed: 11        12
Unnamed: 12    73.242
Unnamed: 13       332
Name: 9, dtype: object, Unnamed: 4      4020
Unnamed: 5      4050
Unnamed: 6      4020
Unnamed: 7      4050
Unnamed: 8      4035
Unnamed: 9       -19
Unnamed: 10      -34
Unnamed: 11        8
Unnamed: 12    48.42
Unnamed: 13      336
Name: 10, dtype: object, Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4035
Unnamed: 8     4035
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     336
Name: 11, dtype: object, Unnamed: 4      4010
Unnamed: 5      4050
Unnamed: 6      4010
Unnamed: 7      4050
Unnamed: 8      4030
Unnamed: 9        15
Unnamed: 10       -5
Unnamed: 11        8
Unnamed: 12    48.36
Unnamed: 13      336
Name: 12, dtype: object, Unnamed: 4       4116
Unnamed: 5       4116
Unnamed: 6       4098
Unnamed: 7       4098
Unnamed: 8       4111
Unnamed: 9         68
Unnamed: 10        81
Unnamed: 11        16
Unnamed: 12    98.676
Unnamed: 13       324
Name: 13, dtype: object]
11
length
[4345, 4396, 4308, 4377, 4370, 0, 0, 128, 839.136, 312]
11
Unnamed: 4        4191
Unnamed: 5        4280
Unnamed: 6        4191
Unnamed: 7        4260
Unnamed: 8        4236
Unnamed: 9         122
Unnamed: 10         98
Unnamed: 11         28
Unnamed: 12    177.918
Unnamed: 13        336
Name: 7, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, 75.0, 68.0, 0.0, 0.0, 0.0, 14.0, 11.0, 51.0, -2.0, 3.0, 5.0, 3.0, -80.0, -524.2379999999999, 36.0, 9.0, -35.0, 29.0, -40.0, -21.0, -36.0, -24.0, -76.0, -499.88399999999996, 16.0, -207.0, -258.0, -170.0, -239.0, -232.0, -211.0, -211.0, -124.0, -814.308, 20.0, 69]
done
Unnamed: 4      4260
Unnamed: 5      4260
Unnamed: 6      4260
Unnamed: 7      4260
Unnamed: 8      4260
Unnamed: 9        24
Unnamed: 10       24
Unnamed: 11        4
Unnamed: 12    25.56
Unnamed: 13      332
Name: 8, dtype: object
[14.0, 11.0, 51.0, -2.0, 3.0, 5.0, 3.0, -80.0, -524.2379999999999, 36.0, 9.0, -35.0, 29.0, -40.0, -21.0, -36.0, -24.0, -76.0, -499.88399999999996, 16.0, -207.0, -258.0, -170.0, -239.0, -232.0, -211.0, -211.0, -124.0, -814.308, 20.0, -154.0, -116.0, -117.0, -117.0, -134.0, 122.0, 98.0, -100.0, -661.218, 24.0, 0]
done
Unnamed: 4       4069
Unnamed: 5       4069
Unnamed: 6       4069
Unnamed: 7       4069
Unnamed: 8       4069
Unnamed: 9       -191
Unnamed: 10      -191
Unnamed: 11        12
Unnamed: 12    73.242
Unnamed: 13       332
Name: 9, dtype: object
[9.0, -35.0, 29.0, -40.0, -21.0, -36.0, -24.0, -76.0, -499.88399999999996, 16.0, -207.0, -258.0, -170.0, -239.0, -232.0, -211.0, -211.0, -124.0, -814.308, 20.0, -154.0, -116.0, -117.0, -117.0, -134.0, 122.0, 98.0, -100.0, -661.218, 24.0, -85.0, -136.0, -48.0, -117.0, -110.0, 24.0, 24.0, -124.0, -813.576, 20.0, 0]
done
Unnamed: 4      4020
Unnamed: 5      4050
Unnamed: 6      4020
Unnamed: 7      4050
Unnamed: 8      4035
Unnamed: 9       -19
Unnamed: 10      -34
Unnamed: 11        8
Unnamed: 12    48.42
Unnamed: 13      336
Name: 10, dtype: object
[-207.0, -258.0, -170.0, -239.0, -232.0, -211.0, -211.0, -124.0, -814.308, 20.0, -154.0, -116.0, -117.0, -117.0, -134.0, 122.0, 98.0, -100.0, -661.218, 24.0, -85.0, -136.0, -48.0, -117.0, -110.0, 24.0, 24.0, -124.0, -813.576, 20.0, -276.0, -327.0, -239.0, -308.0, -301.0, -191.0, -191.0, -116.0, -765.894, 20.0, 30]
done
Unnamed: 4      NaN
Unnamed: 5      NaN
Unnamed: 6      NaN
Unnamed: 7     4035
Unnamed: 8     4035
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13     336
Name: 11, dtype: object
[-154.0, -116.0, -117.0, -117.0, -134.0, 122.0, 98.0, -100.0, -661.218, 24.0, -85.0, -136.0, -48.0, -117.0, -110.0, 24.0, 24.0, -124.0, -813.576, 20.0, -276.0, -327.0, -239.0, -308.0, -301.0, -191.0, -191.0, -116.0, -765.894, 20.0, -325.0, -346.0, -288.0, -327.0, -335.0, -19.0, -34.0, -120.0, -790.716, 24.0, nan]
done
Unnamed: 4      4010
Unnamed: 5      4050
Unnamed: 6      4010
Unnamed: 7      4050
Unnamed: 8      4030
Unnamed: 9        15
Unnamed: 10       -5
Unnamed: 11        8
Unnamed: 12    48.36
Unnamed: 13      336
Name: 12, dtype: object
[-85.0, -136.0, -48.0, -117.0, -110.0, 24.0, 24.0, -124.0, -813.576, 20.0, -276.0, -327.0, -239.0, -308.0, -301.0, -191.0, -191.0, -116.0, -765.894, 20.0, -325.0, -346.0, -288.0, -327.0, -335.0, -19.0, -34.0, -120.0, -790.716, 24.0, nan, nan, nan, -342.0, -335.0, 0.0, 0.0, -128.0, -839.136, 24.0, 40]
done
Unnamed: 4       4116
Unnamed: 5       4116
Unnamed: 6       4098
Unnamed: 7       4098
Unnamed: 8       4111
Unnamed: 9         68
Unnamed: 10        81
Unnamed: 11        16
Unnamed: 12    98.676
Unnamed: 13       324
Name: 13, dtype: object
[-276.0, -327.0, -239.0, -308.0, -301.0, -191.0, -191.0, -116.0, -765.894, 20.0, -325.0, -346.0, -288.0, -327.0, -335.0, -19.0, -34.0, -120.0, -790.716, 24.0, nan, nan, nan, -342.0, -335.0, 0.0, 0.0, -128.0, -839.136, 24.0, -335.0, -346.0, -298.0, -327.0, -340.0, 15.0, -5.0, -120.0, -790.776, 24.0, -18]
done
month is 12

                    所内合约行情报表  \
0      日期： 20191201-20191231
1                         合约
2                   Contract
3                     ag1912
4                        NaN
...                      ...
22380                    NaN
22381                    注：
22382                    NaN
22383                    NaN
22384                    NaN

                                              Unnamed: 1 Unnamed: 2  \
0                                                    NaN        NaN
1                                                     日期        前收盘
2                                                   Date  pre close
3                                               20191202       4104
4                                               20191203       4095
...                                                  ...        ...
22380                                                NaN        NaN
22381  1、 合约单位：铜、铝、锌、天然橡胶为5吨/手，天然橡胶(1208开始)、燃料油、沥青、螺纹...        NaN
22382  2、 报价单位：铜、铝、锌、铅、螺纹钢、线材、热轧卷板、天然橡胶、燃料油、沥青为元/吨；黄金...        NaN
22383            3、 成交量、持仓量、持仓变化单位为手，双边计算；成交金额单位为万元，双边计算        NaN
22384                        4、 涨跌1=收盘价-前结算； 涨跌2=结算价-前结算        NaN

       Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0             NaN        NaN        NaN        NaN        NaN        NaN
1             前结算        开盘价        最高价        最低价        收盘价        结算价
2      Pre settle       Open       High        Low      Close     Settle
3            4107       4097       4125       4051       4095       4100
4            4100       4097       4113       4092       4101       4102
...           ...        ...        ...        ...        ...        ...
22380         NaN        NaN        NaN        NaN        NaN        NaN
22381         NaN        NaN        NaN        NaN        NaN        NaN
22382         NaN        NaN        NaN        NaN        NaN        NaN
22383         NaN        NaN        NaN        NaN        NaN        NaN
22384         NaN        NaN        NaN        NaN        NaN        NaN

      Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13
0            NaN         NaN         NaN         NaN         NaN NaN
1            涨跌1         涨跌2         成交量        成交金额         持仓量 NaN
2            ch1         ch2      Volume      Amount          OI NaN
3            -12          -7       19774      121616       99956 NaN
4              1           2       12744     78419.2       94600 NaN
...          ...         ...         ...         ...         ...  ..
22380        NaN         NaN         NaN         NaN         NaN NaN
22381        NaN         NaN         NaN         NaN         NaN NaN
22382        NaN         NaN         NaN         NaN         NaN NaN
22383        NaN         NaN         NaN         NaN         NaN NaN
22384        NaN         NaN         NaN         NaN         NaN NaN

[22385 rows x 15 columns]
dddfff

In [13]:
import csv
with open('ag/duplicated_ag1911.csv', 'w') as f:
      
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for i in duplicated:
        write.writerow(i)

In [35]:
tosubtract = [result[0][0], result[0][1], result[0][2], result[0][3], result[0][4], 0, 0, result[0][7], result[0][8], result[0][9]]
print(tosubtract)

[5838, 5875, 5800, 5823, 5839, 0, 0, 68, 595.602, 331]

In [38]:
duplicated = []
print(len(result))
for i in range(len(result)-4):
    print(result[4+i])
    toadd = (result[0+i] - tosubtract).tolist() + (result[1+i]- tosubtract).tolist()  + (result[2+i]- tosubtract).tolist() + (result[3+i]- tosubtract).tolist() + [result[4+i][3] - result[4+i][0]]
    print(toadd)
    print("done")
    duplicated.append(toadd)

20
Unnamed: 4        5737
Unnamed: 5        5779
Unnamed: 6        5714
Unnamed: 7        5717
Unnamed: 8        5748
Unnamed: 9         -36
Unnamed: 10         -5
Unnamed: 11         23
Unnamed: 12    198.336
Unnamed: 13        314
Name: 157, dtype: object
[0.0, 0.0, 0.0, 0.0, 0.0, 97.0, 113.0, 0.0, 0.0, 0.0, 0.0, 24.0, -43.0, 10.0, 11.0, -6.0, 11.0, -1.0, -7.663499999999999, 0.0, 35.0, 3.0, 9.0, -14.0, -4.0, -41.0, -15.0, 31.0, 271.04100000000005, -12.0, -29.0, -45.0, -139.0, -25.0, -86.0, -37.0, -82.0, 9.0, 68.98350000000005, -16.0, -20]
done
Unnamed: 4          5620
Unnamed: 5          5646
Unnamed: 6          5186
Unnamed: 7          5239
Unnamed: 8          5391
Unnamed: 9          -509
Unnamed: 10         -357
Unnamed: 11          201
Unnamed: 12    1625.6115
Unnamed: 13          308
Name: 158, dtype: object
[0.0, 24.0, -43.0, 10.0, 11.0, -6.0, 11.0, -1.0, -7.663499999999999, 0.0, 35.0, 3.0, 9.0, -14.0, -4.0, -41.0, -15.0, 31.0, 271.04100000000005, -12.0, -29.0, -45.0, -139.0, -25.0, -86.0, -37.0, -82.0, 9.0, 68.98350000000005, -16.0, -101.0, -96.0, -86.0, -106.0, -91.0, -36.0, -5.0, -45.0, -397.26599999999996, -17.0, -381]
done
Unnamed: 4        5226
Unnamed: 5        5372
Unnamed: 6        5172
Unnamed: 7        5372
Unnamed: 8        5254
Unnamed: 9         -19
Unnamed: 10       -137
Unnamed: 11        126
Unnamed: 12    993.171
Unnamed: 13        300
Name: 159, dtype: object
[35.0, 3.0, 9.0, -14.0, -4.0, -41.0, -15.0, 31.0, 271.04100000000005, -12.0, -29.0, -45.0, -139.0, -25.0, -86.0, -37.0, -82.0, 9.0, 68.98350000000005, -16.0, -101.0, -96.0, -86.0, -106.0, -91.0, -36.0, -5.0, -45.0, -397.26599999999996, -17.0, -218.0, -229.0, -614.0, -584.0, -448.0, -509.0, -357.0, 133.0, 1030.0095000000001, -23.0, 146]
done
Unnamed: 4         5328
Unnamed: 5         5387
Unnamed: 6         5295
Unnamed: 7         5362
Unnamed: 8         5336
Unnamed: 9          108
Unnamed: 10          82
Unnamed: 11          70
Unnamed: 12    560.3805
Unnamed: 13         284
Name: 160, dtype: object
[-29.0, -45.0, -139.0, -25.0, -86.0, -37.0, -82.0, 9.0, 68.98350000000005, -16.0, -101.0, -96.0, -86.0, -106.0, -91.0, -36.0, -5.0, -45.0, -397.26599999999996, -17.0, -218.0, -229.0, -614.0, -584.0, -448.0, -509.0, -357.0, 133.0, 1030.0095000000001, -23.0, -612.0, -503.0, -628.0, -451.0, -585.0, -19.0, -137.0, 58.0, 397.5690000000001, -31.0, 34]
done
Unnamed: 4         5307
Unnamed: 5         5361
Unnamed: 6         5285
Unnamed: 7         5310
Unnamed: 8         5319
Unnamed: 9          -26
Unnamed: 10         -17
Unnamed: 11          79
Unnamed: 12    630.3315
Unnamed: 13         304
Name: 161, dtype: object
[-101.0, -96.0, -86.0, -106.0, -91.0, -36.0, -5.0, -45.0, -397.26599999999996, -17.0, -218.0, -229.0, -614.0, -584.0, -448.0, -509.0, -357.0, 133.0, 1030.0095000000001, -23.0, -612.0, -503.0, -628.0, -451.0, -585.0, -19.0, -137.0, 58.0, 397.5690000000001, -31.0, -510.0, -488.0, -505.0, -461.0, -503.0, 108.0, 82.0, 2.0, -35.22149999999999, -47.0, 3]
done
Unnamed: 4         5331
Unnamed: 5         5444
Unnamed: 6         5313
Unnamed: 7         5328
Unnamed: 8         5382
Unnamed: 9            9
Unnamed: 10          63
Unnamed: 11         121
Unnamed: 12    976.9515
Unnamed: 13         302
Name: 162, dtype: object
[-218.0, -229.0, -614.0, -584.0, -448.0, -509.0, -357.0, 133.0, 1030.0095000000001, -23.0, -612.0, -503.0, -628.0, -451.0, -585.0, -19.0, -137.0, 58.0, 397.5690000000001, -31.0, -510.0, -488.0, -505.0, -461.0, -503.0, 108.0, 82.0, 2.0, -35.22149999999999, -47.0, -531.0, -514.0, -515.0, -513.0, -520.0, -26.0, -17.0, 11.0, 34.72950000000003, -27.0, -3]
done
Unnamed: 4         5318
Unnamed: 5         5350
Unnamed: 6         5188
Unnamed: 7         5322
Unnamed: 8         5266
Unnamed: 9          -60
Unnamed: 10        -116
Unnamed: 11         127
Unnamed: 12    1003.362
Unnamed: 13         309
Name: 163, dtype: object
[-612.0, -503.0, -628.0, -451.0, -585.0, -19.0, -137.0, 58.0, 397.5690000000001, -31.0, -510.0, -488.0, -505.0, -461.0, -503.0, 108.0, 82.0, 2.0, -35.22149999999999, -47.0, -531.0, -514.0, -515.0, -513.0, -520.0, -26.0, -17.0, 11.0, 34.72950000000003, -27.0, -507.0, -431.0, -487.0, -495.0, -457.0, 9.0, 63.0, 53.0, 381.34950000000003, -29.0, 4]
done
Unnamed: 4         5306
Unnamed: 5         5390
Unnamed: 6         5290
Unnamed: 7         5344
Unnamed: 8         5354
Unnamed: 9           78
Unnamed: 10          88
Unnamed: 11          59
Unnamed: 12    473.8515
Unnamed: 13         301
Name: 164, dtype: object
[-510.0, -488.0, -505.0, -461.0, -503.0, 108.0, 82.0, 2.0, -35.22149999999999, -47.0, -531.0, -514.0, -515.0, -513.0, -520.0, -26.0, -17.0, 11.0, 34.72950000000003, -27.0, -507.0, -431.0, -487.0, -495.0, -457.0, 9.0, 63.0, 53.0, 381.34950000000003, -29.0, -520.0, -525.0, -612.0, -501.0, -573.0, -60.0, -116.0, 59.0, 407.76, -22.0, 38]
done
Unnamed: 4         5320
Unnamed: 5         5406
Unnamed: 6         5300
Unnamed: 7         5397
Unnamed: 8         5347
Unnamed: 9           43
Unnamed: 10          -7
Unnamed: 11          60
Unnamed: 12    481.2705
Unnamed: 13         309
Name: 165, dtype: object
[-531.0, -514.0, -515.0, -513.0, -520.0, -26.0, -17.0, 11.0, 34.72950000000003, -27.0, -507.0, -431.0, -487.0, -495.0, -457.0, 9.0, 63.0, 53.0, 381.34950000000003, -29.0, -520.0, -525.0, -612.0, -501.0, -573.0, -60.0, -116.0, 59.0, 407.76, -22.0, -532.0, -485.0, -510.0, -479.0, -485.0, 78.0, 88.0, -9.0, -121.75049999999999, -30.0, 77]
done
Unnamed: 4        5344
Unnamed: 5        5499
Unnamed: 6        5307
Unnamed: 7        5475
Unnamed: 8        5428
Unnamed: 9         128
Unnamed: 10         81
Unnamed: 11         94
Unnamed: 12    765.357
Unnamed: 13        305
Name: 166, dtype: object
[-507.0, -431.0, -487.0, -495.0, -457.0, 9.0, 63.0, 53.0, 381.34950000000003, -29.0, -520.0, -525.0, -612.0, -501.0, -573.0, -60.0, -116.0, 59.0, 407.76, -22.0, -532.0, -485.0, -510.0, -479.0, -485.0, 78.0, 88.0, -9.0, -121.75049999999999, -30.0, -518.0, -469.0, -500.0, -426.0, -492.0, 43.0, -7.0, -8.0, -114.33149999999995, -22.0, 131]
done
Unnamed: 4         5426
Unnamed: 5         5472
Unnamed: 6         5349
Unnamed: 7         5386
Unnamed: 8         5423
Unnamed: 9          -42
Unnamed: 10          -5
Unnamed: 11          98
Unnamed: 12    797.2335
Unnamed: 13         302
Name: 167, dtype: object
[-520.0, -525.0, -612.0, -501.0, -573.0, -60.0, -116.0, 59.0, 407.76, -22.0, -532.0, -485.0, -510.0, -479.0, -485.0, 78.0, 88.0, -9.0, -121.75049999999999, -30.0, -518.0, -469.0, -500.0, -426.0, -492.0, 43.0, -7.0, -8.0, -114.33149999999995, -22.0, -494.0, -376.0, -493.0, -348.0, -411.0, 128.0, 81.0, 26.0, 169.755, -26.0, -40]
done
Unnamed: 4          5329
Unnamed: 5          5431
Unnamed: 6          5293
Unnamed: 7          5404
Unnamed: 8          5346
Unnamed: 9           -19
Unnamed: 10          -77
Unnamed: 11          148
Unnamed: 12    1186.8225
Unnamed: 13          349
Name: 168, dtype: object
[-532.0, -485.0, -510.0, -479.0, -485.0, 78.0, 88.0, -9.0, -121.75049999999999, -30.0, -518.0, -469.0, -500.0, -426.0, -492.0, 43.0, -7.0, -8.0, -114.33149999999995, -22.0, -494.0, -376.0, -493.0, -348.0, -411.0, 128.0, 81.0, 26.0, 169.755, -26.0, -412.0, -403.0, -451.0, -437.0, -416.0, -42.0, -5.0, 30.0, 201.63150000000007, -29.0, 75]
done
Unnamed: 4        5404
Unnamed: 5        5450
Unnamed: 6        5331
Unnamed: 7        5339
Unnamed: 8        5391
Unnamed: 9          -7
Unnamed: 10         45
Unnamed: 11        110
Unnamed: 12    889.668
Unnamed: 13        366
Name: 169, dtype: object
[-518.0, -469.0, -500.0, -426.0, -492.0, 43.0, -7.0, -8.0, -114.33149999999995, -22.0, -494.0, -376.0, -493.0, -348.0, -411.0, 128.0, 81.0, 26.0, 169.755, -26.0, -412.0, -403.0, -451.0, -437.0, -416.0, -42.0, -5.0, 30.0, 201.63150000000007, -29.0, -509.0, -444.0, -507.0, -419.0, -493.0, -19.0, -77.0, 80.0, 591.2205, 18.0, -65]
done
Unnamed: 4         5339
Unnamed: 5         5404
Unnamed: 6         5313
Unnamed: 7         5341
Unnamed: 8         5357
Unnamed: 9          -50
Unnamed: 10         -34
Unnamed: 11          73
Unnamed: 12    586.6005
Unnamed: 13         380
Name: 170, dtype: object
[-494.0, -376.0, -493.0, -348.0, -411.0, 128.0, 81.0, 26.0, 169.755, -26.0, -412.0, -403.0, -451.0, -437.0, -416.0, -42.0, -5.0, 30.0, 201.63150000000007, -29.0, -509.0, -444.0, -507.0, -419.0, -493.0, -19.0, -77.0, 80.0, 591.2205, 18.0, -434.0, -425.0, -469.0, -484.0, -448.0, -7.0, 45.0, 42.0, 294.06600000000003, 35.0, 2]
done
Unnamed: 4        5287
Unnamed: 5        5361
Unnamed: 6        5233
Unnamed: 7        5304
Unnamed: 8        5297
Unnamed: 9         -53
Unnamed: 10        -60
Unnamed: 11        183
Unnamed: 12    1454.04
Unnamed: 13        416
Name: 171, dtype: object
[-412.0, -403.0, -451.0, -437.0, -416.0, -42.0, -5.0, 30.0, 201.63150000000007, -29.0, -509.0, -444.0, -507.0, -419.0, -493.0, -19.0, -77.0, 80.0, 591.2205, 18.0, -434.0, -425.0, -469.0, -484.0, -448.0, -7.0, 45.0, 42.0, 294.06600000000003, 35.0, -499.0, -471.0, -487.0, -482.0, -482.0, -50.0, -34.0, 5.0, -9.001499999999965, 49.0, 17]
done
Unnamed: 4          5323
Unnamed: 5          5596
Unnamed: 6          5317
Unnamed: 7          5535
Unnamed: 8          5468
Unnamed: 9           238
Unnamed: 10          171
Unnamed: 11          720
Unnamed: 12    5905.8435
Unnamed: 13          659
Name: 172, dtype: object
[-509.0, -444.0, -507.0, -419.0, -493.0, -19.0, -77.0, 80.0, 591.2205, 18.0, -434.0, -425.0, -469.0, -484.0, -448.0, -7.0, 45.0, 42.0, 294.06600000000003, 35.0, -499.0, -471.0, -487.0, -482.0, -482.0, -50.0, -34.0, 5.0, -9.001499999999965, 49.0, -551.0, -514.0, -567.0, -519.0, -542.0, -53.0, -60.0, 115.0, 858.438, 85.0, 212]
done

In [39]:
import csv
with open('duplicated_ag1912.csv', 'w') as f:
      
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for i in duplicated:
        write.writerow(i)